{
    "swagger": "2.0",
    "info": {
        "version": "v1.0",
        "title": "WSO2 API Manager - Publisher API",
        "description": "This specifies a **RESTful API** for WSO2 **API Manager** - Publisher.\n\nPlease see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification.\n",
        "contact": {
            "name": "WSO2",
            "url": "http://wso2.com/products/api-manager/",
            "email": "architecture@wso2.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        }
    },
    "schemes": [
        "https",
        "http"
    ],
    "host": "apis.wso2.com",
    "basePath": "/api/am/publisher/v1.0",
    "securityDefinitions": {
        "OAuth2Security": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "https://localhost:9443/token",
            "scopes": {
                "apim:api_view": "View API",
                "apim:api_create": "Create API",
                "apim:api_update": "Update API",
                "apim:api_delete": "Delete API",
                "apim:api_publish": "Publish API",
                "apim:subscription_view": "View Subscription",
                "apim:subscription_block": "Block Subscription",
                "apim:dedicated_gateway": "Update Dedicated Gateway",
                "apim:external_services_discover": "Discover External Services",
                "apim:threat_protection_policy_create": "Create threat protection policies",
                "apim:threat_protection_policy_manage": "Update and delete threat protection policies",
                "apim:document_create": "Create API documents",
                "apim:document_manage": "Update and delete API documents",
                "apim:mediation_policy_view": "View mediation policies",
                "apim:mediation_policy_create": "Create mediation policies",
                "apim:mediation_policy_manage": "Update and delete mediation policies",
                "apim:client_certificates_view": "View client certificates",
                "apim:client_certificates_add": "Add client certificates",
                "apim:client_certificates_update": "Update and delete client certificates",
                "apim:ep_certificates_view": "View backend endpoint certificates",
                "apim:ep_certificates_add": "Add backend endpoint certificates",
                "apim:ep_certificates_update": "Update and delete backend endpoint certificates",
                "apim:publisher_setting": "Retrieve store settings"
            }
        }
    },
    "security": [
        {
            "OAuth2Security": [
                "apim:api_view"
            ]
        }
    ],
    "paths": {
        "/apis": {
            "get": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9443/api/am/publisher/v1.0/apis",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"previous\": \"\",\n   \"list\":    [\n            {\n         \"provider\": \"admin\",\n         \"version\": \"1.0.0\",\n         \"description\": \"This sample API provides Account Status Validation\",\n         \"name\": \"AccountVal\",\n         \"context\": \"/account\",\n         \"id\": \"2e81f147-c8a8-4f68-b4f0-69e0e7510b01\",\n         \"lifeCycleStatus\": \"PUBLISHED\"\n      },\n            [...]",
                "summary": "Retrieve/Search APIs\n",
                "description": "This operation provides you a list of available APIs qualifying under a given search condition.\n\nEach retrieved API is represented with a minimal amount of attributes. If you want to get complete details of an API, you need to use **Get details of an API** operation.\n",
                "tags": [
                    "API (Collection)"
                ]
            },
            "head": {
                "x-wso2-curl": "curl -I -k -X HEAD \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/publisher/v1.0/apis?query=name%3AapiName",
                "x-wso2-request": "HEAD https://localhost:9443/api/am/publisher/v1.0/apis?query=name%3AapiName HTTP/1.1\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK Connection: keep-alive Content-Length: 0",
                "summary": "Check given API attibute name is already exist\n",
                "description": "Using this operation, you can check a given API context is already used. You need to provide the context name you want to check.\n",
                "tags": [
                    "API (Collection)"
                ]
            },
            "post": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -H \"Content-Type: application/json\" -X POST -d @data.json https://127.0.0.1:9443/api/am/publisher/v1.0/apis",
                "x-wso2-request": "POST https://127.0.0.1:9443/api/am/publisher/v1.0/apis\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n\n{\r\n   \"name\": \"PizzaShackAPI\",\r\n   \"description\": \"This document describe a RESTFul API for Pizza Shack online pizza delivery store.\\r\\n\",\r\n   \"context\": \"/pizzashack\",\r\n   \"version\": \"1.0.0\",\r\n   \"provider\": \"admin\",\r\n   \"wsdlUri\": null,\r\n   \"lifeCycleStatus\": \"PUBLISHED\",\r\n   \"responseCaching\": \"D[...]",
                "x-wso2-response": "HTTP/1.1 201 Created\nLocation: https://127.0.0.1:9443/api/am/publisher/v1.0/apis/7a2298c4-c905-403f-8fac-38c73301631f\nContent-Type: application/json\n\n{\r\n   \"id\": \"7a2298c4-c905-403f-8fac-38c73301631f\",\r\n   \"name\": \"PizzaShackAPI\",\r\n   \"description\": \"This document describe a RESTFul API for Pizza Shack online pizza delivery store.\\r\\n\",\r\n   \"context\": \"/pizzashack\",\r\n   \"version\": \"1.0.0\",\r\n   \"provider\": \"admin\",\r\n [...]",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "summary": "Create a new API",
                "description": "This operation can be used to create a new API specifying the details of the API in the payload. The new API will be in `CREATED` state.\n\nThere is a special capability for a user who has `APIM Admin` permission such that he can create APIs on behalf of other users. For that he can to specify `\"provider\" : \"some_other_user\"` in the payload so that the API's creator will be shown as `some_other_user` in the UI.\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/{apiId}": {
            "get": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9443/api/am/publisher/v1.0/apis/7a2298c4-c905-403f-8fac-38c73301631f",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/7a2298c4-c905-403f-8fac-38c73301631f\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\r\n   \"id\": \"7a2298c4-c905-403f-8fac-38c73301631f\",\r\n   \"name\": \"PizzaShackAPI\",\r\n   \"description\": \"This document describe a RESTFul API for Pizza Shack online pizza delivery store.\\r\\n\",\r\n   \"context\": \"/pizzashack\",\r\n   \"version\": \"1.0.0\",\r\n   \"provider\": \"admin\",\r\n   \"endpointId\": \"{\\\"paths\\\":{\\\"/order\\\":{\\\"post\\\":{\\\"x-auth-type\\\":\\\"Application &[...]",
                "summary": "Get details of an API",
                "description": "Using this operation, you can retrieve complete details of a single API. You need to provide the Id of the API to retrive it.\n",
                "tags": [
                    "API (Individual)"
                ]
            },
            "put": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -H \"Content-Type: application/json\" -X PUT -d @data.json https://127.0.0.1:9443/api/am/publisher/v1.0/apis/7a2298c4-c905-403f-8fac-38c73301631f",
                "x-wso2-request": "PUT https://127.0.0.1:9443/api/am/publisher/v1.0/apis/7a2298c4-c905-403f-8fac-38c73301631f\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\nContent-Type: application/json\n\n{\r\n   \"id\": \"7a2298c4-c905-403f-8fac-38c73301631f\",\r\n   \"name\": \"PizzaShackAPI\",\r\n   \"description\": \"This document describe a RESTFul API for Pizza Shack online pizza delivery store.\\r\\n\",\r\n   \"context\": \"/pizzashack\",\r\n   \"version\": \"1.0.0\",\r\n [...]",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\r\n   \"id\": \"7a2298c4-c905-403f-8fac-38c73301631f\",\r\n   \"name\": \"PizzaShackAPI\",\r\n   \"description\": \"This document describe a RESTFul API for Pizza Shack online pizza delivery store.\\r\\n\",\r\n   \"context\": \"/pizzashack\",\r\n   \"version\": \"1.0.0\",\r\n   \"provider\": \"admin\",\r\n   \"endpointId\": \"{\\\"paths\\\":{\\\"/order\\\":{\\\"post\\\":{\\\"x-auth-type\\\":\\\"Application &[...]",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_update"
                        ]
                    }
                ],
                "summary": "Update an API",
                "description": "This operation can be used to update an existing API.\nBut the properties `name`, `version`, `context`, `provider`, `state` will not be changed by this operation.\n",
                "tags": [
                    "API (Individual)"
                ]
            },
            "delete": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X DELETE https://127.0.0.1:9443/api/am/publisher/v1.0/apis/6fb74674-4ab8-4b52-9886-f9a376985060",
                "x-wso2-request": "DELETE https://127.0.0.1:9443/api/am/publisher/v1.0/apis/6fb74674-4ab8-4b52-9886-f9a376985060\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_delete"
                        ]
                    }
                ],
                "summary": "Delete an API",
                "description": "This operation can be used to delete an existing API proving the Id of the API.\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/{apiId}/swagger": {
            "get": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/swagger",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/swagger\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\nContent-Length: 329\n\n{\n   \"paths\": {\"/*\": {\"get\":    {\n      \"x-auth-type\": \"Application\",\n      \"x-throttling-policy\": \"Unlimited\",\n      \"responses\": {\"200\": {\"description\": \"OK\"}}\n   }}},\n   \"swagger\": \"2.0\",\n   \"info\":    {\n      \"title\": \"PhoneVerification\",\n      \"description\": \"Verify a phone number\",\n      \"contact\":       {\n         \"email\": \"xx@ee.c[...]",
                "summary": "Get swagger definition",
                "description": "This operation can be used to retrieve the swagger definition of an API.\n",
                "tags": [
                    "API (Individual)"
                ]
            },
            "put": {
                "x-wso2-curl": "curl -k -H \"Authorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\" -F endpointId=\"{\\\"paths\\\":{\\\"\\/*\\\":{\\\"get\\\":{\\\"x-auth-type\\\":\\\"Application\\\",\\\"x-throttling-policy\\\":\\\"Unlimited\\\",\\\"responses\\\":{\\\"200\\\":{\\\"description\\\":\\\"OK\\\"}}}}},\\\"swagger\\\":\\\"2.0\\\",\\\"info\\\":{\\\"title\\\":\\\"PhoneVerification\\\",\\\"description\\\":\\\"Verify a phone number\\\",\\\"contact\\\":{\\\"email\\\":\\\"xx@ee.com\\\",\[...]",
                "x-wso2-request": "PUT https://127.0.0.1:9443/api/am/publisher/v1.0/apis/8848faaa-7fd1-478a-baa2-48a4ebb92c98/swagger\nAuthorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\nContent-Length: 477\nContent-Type: multipart/form-data; boundary=------------------------4f51e636c0003d99\n\n--------------------------4f51e636c0003d99\nContent-Disposition: form-data; name=\"apiDefinition\"\n\n{\"paths\":{\"\\/*\":{\"get\":{\"x-auth-type\":\"Application\",\"x-throttling-policy\":\"Unlimi[...]",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"paths\": {\"/*\": {\"get\":    {\n      \"x-auth-type\": \"Application\",\n      \"x-throttling-policy\": \"Unlimited\",\n      \"responses\": {\"200\": {\"description\": \"OK\"}}\n   }}},\n   \"swagger\": \"2.0\",\n   \"info\":    {\n      \"title\": \"PhoneVerification\",\n      \"description\": \"Verify a phone number\",\n      \"contact\":       {\n         \"email\": \"xx@ee.com\",\n         \"nam[...]",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_update"
                        ]
                    }
                ],
                "summary": "Update swagger definition",
                "description": "This operation can be used to update the swagger definition of an existing API. Swagger definition to be updated is passed as a form data parameter `apiDefinition`.\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/{apiId}/resource-policies": {
            "get": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/publisher/v0.14/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/resource-policies",
                "x-wso2-request": "GET https://localhost:9443/api/am/publisher/v0.14/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/resource-policies\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\r\n    \"list\": [\r\n        {\r\n            \"id\": \"1990b54c-6685-4058-a08c-8fd5353056a6\",\r\n            \"httpVerb\": \"get\",\r\n            \"resourcePath\": \"checkPhoneNumbers\",\r\n            \"content\": \"<header description=\\\"SOAPAction\\\" name=\\\"SOAPAction\\\" scope=\\\"transport\\\" value=\\\"http://ws.cdyne.com/PhoneVerify/query/CheckPhoneNumber\\\"/>\"\r\n        }\r\n    ],\r\n    [...]",
                "summary": "Get the resource policy (inflow/outflow) definitions",
                "description": "This operation can be used to retrieve conversion policy resource definitions of an API.\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/{apiId}/resource-policies/{resourcePolicyId}": {
            "get": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/publisher/v0.14/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/resource-policies/0bcb7f05-599d-4e1a-adce-5cb89bfe58d5",
                "x-wso2-request": "GET https://localhost:9443/api/am/publisher/v0.14/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/resource-policies/0bcb7f05-599d-4e1a-adce-5cb89bfe58d5\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\r\n            \"id\": \"6c735e1d-8041-4f1e-b246-d28edaa650b0\",\r\n            \"httpVerb\": \"post\",\r\n            \"resourcePath\": \"checkPhoneNumbers\",\r\n            \"content\": \"<header description=\\\"SOAPAction\\\" name=\\\"SOAPAction\\\" scope=\\\"transport\\\" value=\\\"http://ws.cdyne.com/PhoneVerify/query/CheckPhoneNumber\\\"/>\"\r\n}",
                "summary": "Get the resource policy (inflow/outflow) definition for a given resource identifier.",
                "description": "This operation can be used to retrieve conversion policy resource definitions of an API given the resource identifier.\n",
                "tags": [
                    "API (Individual)"
                ]
            },
            "put": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\" -F apiDefinition=\"{\\\"paths\\\":{\\\"\\/*\\\":{\\\"get\\\":{\\\"x-auth-type\\\":\\\"Application\\\",\\\"x-throttling-tier\\\":\\\"Unlimited\\\",\\\"responses\\\":{\\\"200\\\":{\\\"description\\\":\\\"OK\\\"}}}}},\\\"x-wso2-security\\\":{\\\"apim\\\":{\\\"x-wso2-scopes\\\":[]}},\\\"swagger\\\":\\\"2.0\\\",\\\"info\\\":{\\\"title\\\":\\\"PhoneVerification\\\",\\\"description\\\":\\\"Verify a [...]",
                "x-wso2-request": "PUT https://localhost:9443/api/am/publisher/v0.14/apis/8848faaa-7fd1-478a-baa2-48a4ebb92c98/resource-policies/0bcb7f05-599d-4e1a-adce-5cb89bfe58d5\nAuthorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\nContent-Length: 477\nContent-Type: application/json; boundary=------------------------4f51e636c0003d99\n--------------------------4f51e636c0003d99\n{ \"content\": \"<header description=\\\"SOAPAction\\\" name=\\\"SOAPAction\\\" scope=\\\"transport\\\" value=[...]",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\r\n            \"id\": \"6c735e1d-8041-4f1e-b246-d28edaa650b0\",\r\n            \"httpVerb\": \"post\",\r\n            \"resourcePath\": \"checkPhoneNumbers\",\r\n            \"content\": \"<header description=\\\"SOAPAction\\\" name=\\\"SOAPAction\\\" scope=\\\"transport\\\" value=\\\"http://ws.cdyne.com/PhoneVerify/query/CheckPhoneNumber\\\"/>\"\r\n}",
                "summary": "Update the resource policy(inflow/outflow) definition for the given resource identifier",
                "description": "This operation can be used to update the resource policy(inflow/outflow) definition for the given resource identifier of an existing API. resource policy definition to be updated is passed as a body parameter `content`.\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/{apiId}/gateway-config": {
            "get": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/swagger",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/swagger\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\nContent-Length: 329\n\n{\n   \"paths\": {\"/*\": {\"get\":    {\n      \"x-auth-type\": \"Application\",\n      \"x-throttling-policy\": \"Unlimited\",\n      \"responses\": {\"200\": {\"description\": \"OK\"}}\n   }}},\n   \"swagger\": \"2.0\",\n   \"info\":    {\n      \"title\": \"PhoneVerification\",\n      \"description\": \"Verify a phone number\",\n      \"contact\":       {\n         \"email\": \"xx@ee.c[...]",
                "summary": "Get gateway definition",
                "description": "This operation can be used to retrieve the gateway configuration of an API.\n",
                "tags": [
                    "API (Individual)"
                ]
            },
            "put": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_update"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\" -F endpointId=\"{\\\"paths\\\":{\\\"\\/*\\\":{\\\"get\\\":{\\\"x-auth-type\\\":\\\"Application\\\",\\\"x-throttling-policy\\\":\\\"Unlimited\\\",\\\"responses\\\":{\\\"200\\\":{\\\"description\\\":\\\"OK\\\"}}}}},\\\"swagger\\\":\\\"2.0\\\",\\\"info\\\":{\\\"title\\\":\\\"PhoneVerification\\\",\\\"description\\\":\\\"Verify a phone number\\\",\\\"contact\\\":{\\\"email\\\":\\\"xx@ee.com\\\",\[...]",
                "x-wso2-request": "PUT https://127.0.0.1:9443/api/am/publisher/v1.0/apis/8848faaa-7fd1-478a-baa2-48a4ebb92c98/swagger\nAuthorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\nContent-Length: 477\nContent-Type: multipart/form-data; boundary=------------------------4f51e636c0003d99\n\n--------------------------4f51e636c0003d99\nContent-Disposition: form-data; name=\"apiDefinition\"\n\n{\"paths\":{\"\\/*\":{\"get\":{\"x-auth-type\":\"Application\",\"x-throttling-policy\":\"Unlimi[...]",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"paths\": {\"/*\": {\"get\":    {\n      \"x-auth-type\": \"Application\",\n      \"x-throttling-policy\": \"Unlimited\",\n      \"responses\": {\"200\": {\"description\": \"OK\"}}\n   }}},\n   \"swagger\": \"2.0\",\n   \"info\":    {\n      \"title\": \"PhoneVerification\",\n      \"description\": \"Verify a phone number\",\n      \"contact\":       {\n         \"email\": \"xx@ee.com\",\n         \"nam[...]",
                "summary": "Update gateway configuration",
                "description": "This operation can be used to update the gateway configuration of an existing API. gateway configuration to be updated is passed as a form data parameter `gatewayConfig`.\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/{apiId}/thumbnail": {
            "get": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer d34baf74-3f02-3929-814e-88b27f750ba9\" https://127.0.0.1:9443/api/am/publisher/v1.0/apis/29c9ec3d-f590-467e-83e6-96d43517080f/thumbnail > image.jpg",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/29c9ec3d-f590-467e-83e6-96d43517080f/thumbnail\nAuthorization: Bearer d34baf74-3f02-3929-814e-88b27f750ba9\n",
                "x-wso2-response": "HTTP/1.1 200 OK\r\nContent-Type: image/jpeg\r\n\r\n[image content]",
                "summary": "Get thumbnail image",
                "description": "This operation can be used to download a thumbnail image of an API.\n",
                "tags": [
                    "API (Individual)"
                ]
            },
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_update"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X POST -H \"Authorization: Bearer d34baf74-3f02-3929-814e-88b27f750ba9\" https://127.0.0.1:9443/api/am/publisher/v1.0/apis/29c9ec3d-f590-467e-83e6-96d43517080f/thumbnail -F file=@image.jpg",
                "x-wso2-request": "POST https://127.0.0.1:9443/api/am/publisher/v1.0/apis/8848faaa-7fd1-478a-baa2-48a4ebb92c98/thumbnail\nAuthorization: Bearer d34baf74-3f02-3929-814e-88b27f750ba9\nContent-Type: multipart/form-data; boundary=------------------------5e542e0e5b50e1e4\nContent-Length: 18333\n\n--------------------------5e542e0e5b50e1e4\nContent-Disposition: form-data; name=\"file\"; filename=\"image.jpg\"\nContent-Type: image/jpeg\n\n[image content]\n\n--------------------------5e5[...]",
                "x-wso2-response": "HTTP/1.1 201 Created\r\nLocation: https://127.0.0.1:9443/api/am/publisher/v1.0/apis/8848faaa-7fd1-478a-baa2-48a4ebb92c98/thumbnail\r\nContent-Type: application/json\r\n\r\n{\r\n   \"relativePath\": \"/apis/8848faaa-7fd1-478a-baa2-48a4ebb92c98/thumbnail\",\r\n   \"mediaType\": \"image/jpeg\"\r\n}",
                "summary": "Upload a thumbnail image",
                "description": "This operation can be used to upload a thumbnail image of an API. The thumbnail to be uploaded should be given as a form data parameter `file`.\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/{apiId}/threat-protection-policies": {
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:threat_protection_policy_create"
                        ]
                    }
                ],
                "summary": "Add a threat protection policy to an API",
                "tags": [
                    "API (Individual)"
                ]
            },
            "get": {
                "summary": "Get all threat protection policies associated with an API",
                "tags": [
                    "API (Individual)"
                ]
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:threat_protection_policy_manage"
                        ]
                    }
                ],
                "summary": "Delete a threat protection policy from an API",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/copy-api": {
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X POST \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/copy-api?apiId=890a4f4d-09eb-4877-a323-57f6ce2ed79b&newVersion=2.0.0\"",
                "x-wso2-request": "POST https://127.0.0.1:9443/api/am/publisher/v1.0/apis/copy-api?apiId=890a4f4d-09eb-4877-a323-57f6ce2ed79b&newVersion=2.0.0\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 201 Created\nLocation: https://127.0.0.1:9443/api/am/publisher/v1.0/apis/25a84fc9-38c0-4578-95e8-29fb6b1c4771\nContent-Type: application/json\n\n{\r\n   \"id\": \"25a84fc9-38c0-4578-95e8-29fb6b1c4771\",\r\n   \"name\": \"PizzaShackAPI\",\r\n   \"description\": \"This document describe a RESTFul API for Pizza Shack online pizza delivery store.\\r\\n\",\r\n   \"context\": \"/pizzashack\",\r\n   \"version\": \"2.0.0\",\r\n   \"provider\": \"admin\",\r\n [...]",
                "summary": "Create a new API version",
                "description": "This operation can be used to create a new version of an existing API. The new version is specified as `newVersion` query parameter. New API will be in `CREATED` state.\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/change-lifecycle": {
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_publish"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X POST \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/change-lifecycle?apiId=890a4f4d-09eb-4877-a323-57f6ce2ed79b&action=Publish\"",
                "x-wso2-request": "POST https://127.0.0.1:9443/api/am/publisher/v1.0/apis/change-lifecycle?apiId=890a4f4d-09eb-4877-a323-57f6ce2ed79b&action=Publish\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK",
                "summary": "Change API Status",
                "description": "This operation is used to change the lifecycle of an API. Eg: Publish an API which is in `CREATED` state. In order to change the lifecycle, we need to provide the lifecycle `action` as a query parameter.\n\nFor example, to Publish an API, `action` should be `Publish`. Note that the `Re-publish` action is available only after calling `Block`.\n\nSome actions supports providing additional paramters which should be provided as `lifecycleChecklist` parameter. Please s[...]",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/{apiId}/lifecycle-history": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_publish"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer f8828f52-175a-4cb2-b246-02b1e6054f97\" https://127.0.0.1:9443/api/am/publisher/v1.0/apis/0527a55e-8dcf-4ce5-bddf-c77e8418be8a/lifecycle-history",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/lifecycle-history\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\n Content-Type: application/json \n Content-Encoding: gzip \n Transfer-Encoding: chunked \n\n [ { \"postState\" : \"Created\",\n    \"updatedTime\" : \"Feb 23, 2017 5:17:02 PM\",\n\"user\" : \"admin\"\n  },\n { \"postState\" : \"Published\",\n    \"previousState\" : \"Created\",\n    \"updatedTime\" : \"Feb 23, 2017 5:17:17 PM\",\n    \"user\" : \"admin\"\n }\n]",
                "summary": "Get Lifecycle state change history of the API.",
                "description": "This operation can be used to retrieve Lifecycle state change history of the API.\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/{apiId}/lifecycle": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_publish"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer f8828f52-175a-4cb2-b246-02b1e6054f97\" https://127.0.0.1:9443/api/am/publisher/v1.0/apis/0527a55e-8dcf-4ce5-bddf-c77e8418be8a/lifecycle",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/lifecycle\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\n Content-Type: application/json \n Content-Encoding: gzip \n Transfer-Encoding: chunked \n\n {  \n   \"lcName\":\"API_LIFECYCLE\",\n   \"state\":\"Published\",\n   \"lifecycleId\":\"2febf145f07e457c9643100b6ec60679\",\n   \"checkItemBeanList\":[  \n\n   ],\n   \"inputBeanList\":[  \n\n   ],\n   \"customCodeBeanList\":[  \n      {  \n         \"classObject\":{  \n\n         },\n         \"targetName\":\"Maintenance\"\n      },\n      {  \n     [...]",
                "summary": "Get Lifecycle state data of the API.",
                "description": "This operation can be used to retrieve Lifecycle state data of the API.\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/{apiId}/lifecycle/lifecycle-pending-task": {
            "delete": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer f8828f52-175a-4cb2-b246-02b1e6054f97\" -X DELETE https://127.0.0.1:9443/api/am/publisher/v1.0/apis/0527a55e-8dcf-4ce5-bddf-c77e8418be8a/lifecycle/lifecycle-pending-task",
                "x-wso2-request": "DELETE https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/lifecycle/lifecycle-pending-task\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_publish"
                        ]
                    }
                ],
                "summary": "Delete pending lifecycle state change tasks.",
                "description": "This operation can be used to remove pending lifecycle state change requests that are in pending state\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/import-definition": {
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "summary": "Import API Definition",
                "description": "This operation can be used to create api from api definition.\n\nAPI definition can be either Swagger or a WSDL\n\nWSDL can be speficied as a single file or a ZIP archive with WSDLs and reference XSDs etc.\nWhen the type is WSDL, it is a **must** to specify additionalProperties with API's name, version, context and endpoints. See the example for additionalProperties.\n",
                "tags": [
                    "API (Collection)"
                ]
            }
        },
        "/apis/validate-definition": {
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "summary": "Validate API definition and retrieve a summary",
                "description": "This operation can be used to validate a swagger or WSDL definition and retrieve a summary.\n",
                "tags": [
                    "API (Collection)"
                ]
            }
        },
        "/apis/{apiId}/documents": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/documents\"",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/documents\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"previous\": \"\",\n   \"list\":    [\n            {\n         \"visibility\": \"API_LEVEL\",\n         \"sourceType\": \"INLINE\",\n         \"sourceUrl\": null,\n         \"otherTypeName\": null,\n         \"documentId\": \"0bcb7f05-599d-4e1a-adce-5cb89bfe58d5\",\n         \"summary\": \"This is a sample documentation for v1.0.0\",\n         \"name\": \"PhoneVerification API Documentation\",\n        [...]",
                "summary": "Get a list of documents of an API",
                "description": "This operation can be used to retrieve a list of documents belonging to an API by providing the id of the API.\n",
                "tags": [
                    "Document (Collection)"
                ]
            },
            "post": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -H \"Content-Type: application/json\" -X POST -d @data.json \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/96077508-fd01-4fae-bc64-5de0e2baf43c/documents\"",
                "x-wso2-request": "POST https://127.0.0.1:9443/api/am/publisher/v1.0/apis/96077508-fd01-4fae-bc64-5de0e2baf43c/documents\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\nContent-Type: application/json\n\n{\n    \"visibility\": \"API_LEVEL\",\n    \"sourceType\": \"INLINE\",\n    \"sourceUrl\": null,\n    \"otherTypeName\": null,\n    \"summary\": \"This is a sample documentation\",\n    \"name\": \"Introduction to PhoneVerification API\",\n    \"type\": \"HOWTO\"\n}",
                "x-wso2-response": "HTTP/1.1 201 Created\nLocation: https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/documents/ffd5790d-b7a9-4cb6-b76a-f8b83ecdd058\nContent-Type: application/json\n\n{\n   \"visibility\": \"API_LEVEL\",\n   \"sourceType\": \"INLINE\",\n   \"sourceUrl\": null,\n   \"otherTypeName\": null,\n   \"documentId\": \"ffd5790d-b7a9-4cb6-b76a-f8b83ecdd058\",\n   \"summary\": \"This is a sample documentation\",\n   \"name\": \"Introduct[...]",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:document_create"
                        ]
                    }
                ],
                "summary": "Add a new document to an API",
                "description": "This operation can be used to add a new documentation to an API. This operation only adds the metadata of a document. To add the actual content we need to use **Upload the content of an API document ** API once we obtain a document Id by this operation.\n",
                "tags": [
                    "Document (Collection)"
                ]
            }
        },
        "/apis/{apiId}/documents/{documentId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/documents/0bcb7f05-599d-4e1a-adce-5cb89bfe58d5\"",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/documents/0bcb7f05-599d-4e1a-adce-5cb89bfe58d5\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"visibility\": \"API_LEVEL\",\n   \"sourceType\": \"INLINE\",\n   \"sourceUrl\": null,\n   \"otherTypeName\": null,\n   \"documentId\": \"0bcb7f05-599d-4e1a-adce-5cb89bfe58d5\",\n   \"summary\": \"This is a sample documentation\",\n   \"name\": \"PhoneVerification API Documentation\",\n   \"type\": \"HOWTO\"\n}",
                "summary": "Get a document of an API",
                "description": "This operation can be used to retrieve a particular document's metadata associated with an API.\n",
                "tags": [
                    "Document (Individual)"
                ]
            },
            "put": {
                "x-wso2-curl": "curl -k -H \"Authorization:Bearer b0982cd2aacd463ff5f63cd5ebe58f4a\" -H \"Content-Type: application/json\" -X PUT -d data.json \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/96077508-fd01-4fae-bc64-5de0e2baf43c/documents/0bcb7f05-599d-4e1a-adce-5cb89bfe58d5\"",
                "x-wso2-request": "PUT https://127.0.0.1:9443/api/am/publisher/v1.0/apis/96077508-fd01-4fae-bc64-5de0e2baf43c/documents/0bcb7f05-599d-4e1a-adce-5cb89bfe58d5\nAuthorization:Bearer b0982cd2aacd463ff5f63cd5ebe58f4a\nContent-Type: application/json\n\n{\n   \"visibility\": \"API_LEVEL\",\n   \"sourceType\": \"INLINE\",\n   \"sourceUrl\": null,\n   \"otherTypeName\": null,\n   \"documentId\": \"0bcb7f05-599d-4e1a-adce-5cb89bfe58d5\",\n   \"summary\": \"This is a sample documentation fo[...]",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"visibility\": \"API_LEVEL\",\n   \"sourceType\": \"INLINE\",\n   \"sourceUrl\": null,\n   \"otherTypeName\": null,\n   \"documentId\": \"0bcb7f05-599d-4e1a-adce-5cb89bfe58d5\",\n   \"summary\": \"This is a sample documentation for v1.0.0\",\n   \"name\": \"PhoneVerification API Documentation\",\n   \"type\": \"HOWTO\"\n}",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:document_manage"
                        ]
                    }
                ],
                "summary": "Update a document of an API",
                "description": "This operation can be used to update metadata of an API's document.\n",
                "tags": [
                    "Document (Individual)"
                ]
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:document_manage"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X DELETE https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/documents/ffd5790d-b7a9-4cb6-b76a-f8b83ecdd058",
                "x-wso2-request": "DELETE https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/documents/ffd5790d-b7a9-4cb6-b76a-f8b83ecdd058\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK",
                "summary": "Delete a document of an API",
                "description": "This operation can be used to delete a document associated with an API.\n",
                "tags": [
                    "Document (Individual)"
                ]
            }
        },
        "/apis/{apiId}/documents/{documentId}/content": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization:Bearer b0982cd2aacd463ff5f63cd5ebe58f4a\" \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/documents/daf732d3-bda2-46da-b381-2c39d901ea61/content\" > sample.pdf",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/documents/daf732d3-bda2-46da-b381-2c39d901ea61/content\nAuthorization:Bearer b0982cd2aacd463ff5f63cd5ebe58f4a\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Disposition: attachment; filename=\"sample.pdf\"\nContent-Type: application/octet-stream\nContent-Length: 7802\n\n%PDF-1.4\n%äüöß\n2 0 obj\n<</Length 3 0 R/Filter/FlateDecode>>\nstream\n..\n>>\nstartxref\n7279\n%%EOF",
                "summary": "Get the content of an API document",
                "description": "This operation can be used to retrive the content of an API's document.\n\nThe document can be of 3 types. In each cases responses are different.\n\n1. **Inline type**:\n   The content of the document will be retrieved in `text/plain` content type\n\n   _Sample cURL_ : `curl -k -H \"Authorization:Bearer 579f0af4-37be-35c7-81a4-f1f1e9ee7c51\" -F inlineContent=@\"docs.txt\" -X POST \"https://localhost:9443/api/am/publisher/v1/apis/995a4972-3178-4b17-a374-756e0e19127[...]",
                "tags": [
                    "Document (Individual)"
                ]
            },
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:document_create"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization:Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -F file=@\"sample.pdf\" -X POST \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/documents/daf732d3-bda2-46da-b381-2c39d901ea61/content\"",
                "x-wso2-request": "POST https://127.0.0.1:9443/api/am/publisher/v1.0/apis/8848faaa-7fd1-478a-baa2-48a4ebb92c98/documents/b3a79270-02bb-4e39-9ac1-90ce8f6c84af/content\nAuthorization:Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\nContent-Length: 8004\nContent-Type: multipart/form-data; boundary=------------------------7b9a53f1ffa452b9\n\n--------------------------7b9a53f1ffa452b9\nContent-Disposition: form-data; name=\"file\"; filename=\"sample.pdf\"\nContent-Type: application/octet-[...]",
                "x-wso2-response": "HTTP/1.1 201 Created\nLocation: https://127.0.0.1:9443/api/am/publisher/v1.0/apis/8848faaa-7fd1-478a-baa2-48a4ebb92c98/documents/b3a79270-02bb-4e39-9ac1-90ce8f6c84af/content\nContent-Type: application/json\n\n{\n    \"visibility\":\"API_LEVEL\",\n    \"sourceType\":\"FILE\",\n    \"sourceUrl\":null,\n    \"otherTypeName\":null,\n    \"documentId\":\"daf732d3-bda2-46da-b381-2c39d901ea61\",\n    \"summary\":\"This is a sample documentation pdf\",\n    \"name\":\[...]",
                "summary": "Upload the content of an API document",
                "description": "Thid operation can be used to upload a file or add inline content to an API document.\n\n**IMPORTANT:**\n* Either **file** or **inlineContent** form data parameters should be specified at one time.\n* Document's source type should be **FILE** in order to upload a file to the document using **file** parameter.\n* Document's source type should be **INLINE** in order to add inline content to the document using **inlineContent** parameter.\n",
                "tags": [
                    "Document (Individual)"
                ]
            }
        },
        "/apis/{apiId}/policies/mediation": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:mediation_policy_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer fb2a0784-f60c-3276-8fde-5b0f70e61ecc\" https://localhost:9443/api/am/publisher/v0.14/apis/40082986-6488-4b86-801a-b0b069d4588c/policies/mediation",
                "x-wso2-request": "GET https://localhost:9443/api/am/publisher/v0.14/apis/40082986-6488-4b86-801a-b0b069d4588c/policies/mediation\r\nAuthorization: Bearer fb2a0784-f60c-3276-8fde-5b0f70e61ecc",
                "x-wso2-response": "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\r\n   \"count\": 1,\r\n   \"next\": null,\r\n   \"previous\": null,\r\n   \"list\": [   {\r\n      \"name\": \"add_custom_header_fault\",\r\n      \"id\": \"6460d7e6-4272-4e3a-9879-437228d83123\",\r\n      \"type\": \"fault\"\r\n   }]\r\n}",
                "summary": "Get all mediation policies of an API\n",
                "description": "This operation provides you a list of available mediation policies of an API.\n",
                "tags": [
                    "Mediation Policy (Collection)"
                ]
            },
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:mediation_policy_create"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer 6cea3696-0151-3282-bf79-a0c4db6f308a\" -H \"Content-Type: application/json\" -X POST -d @data.json \"https://localhost:9443/api/am/publisher/v0.14/apis/40082986-6488-4b86-801a-b0b069d4588c/policies/mediation\"",
                "x-wso2-request": "POST https://localhost:9443/api/am/publisher/v0.14/apis/40082986-6488-4b86-801a-b0b069d4588c/policies/mediation\r\nContent-Type: application/json\r\nAuthorization: Bearer 6cea3696-0151-3282-bf79-a0c4db6f308a\r\n\r\n{\r\n   \"name\": \"add_custom_header_fault\",\r\n   \"type\": \"fault\",\r\n   \"config\": \"<sequence xmlns=\\\"http://ws.apache.org/ns/synapse\\\" name=\\\"add_custom_header_fault\\\">\\n    <property name=\\\"CustomHeader\\\" scope=\\\"transport\[...]",
                "x-wso2-response": "HTTP/1.1 201 Created\r\nLocation: https://localhost:9443/api/am/publisher/v0.14/registry/resource/_system/governance/apimgt/applicationdata/provider/admin/hello/1.0.0/fault/add_custom_header_fault.xml\r\nContent-Type: application/json\r\n\r\n{  \r\n   \"id\":\"624b9f7d-bfaf-484b-94cc-e84491f5d725\",\r\n   \"name\":\"add_custom_header_fault\",\r\n   \"type\":\"fault\",\r\n   \"config\":\"<sequence xmlns=\\\"http://ws.apache.org/ns/synapse\\\" name=\\\"add_custo[...]",
                "summary": "Add an API specific mediation policy",
                "description": "This operation can be used to add an API specifc mediation policy.\n",
                "tags": [
                    "Mediation Policy (Collection)"
                ]
            }
        },
        "/apis/{apiId}/policies/mediation/{mediationPolicyId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer 5aa0acc0-0ce3-3a0b-8cc8-db5ef696ee23\" https://localhost:9443/api/am/publisher/v0.14/apis/40082986-6488-4b86-801a-b0b069d4588c/policies/mediation/624b9f7d-bfaf-484b-94cc-e84491f5d725",
                "x-wso2-request": "GET https://localhost:9443/api/am/publisher/v0.14/apis/40082986-6488-4b86-801a-b0b069d4588c/policies/mediation/624b9f7d-bfaf-484b-94cc-e84491f5d725\r\nAuthorization: Bearer 5aa0acc0-0ce3-3a0b-8cc8-db5ef696ee23",
                "x-wso2-response": "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\r\n   \"id\": \"624b9f7d-bfaf-484b-94cc-e84491f5d725\",\r\n   \"name\": \"add_custom_header_fault\",\r\n   \"type\": \"fault\",\r\n   \"config\": \"<sequence xmlns=\\\"http://ws.apache.org/ns/synapse\\\" name=\\\"add_custom_header_fault\\\">\\n    <property name=\\\"CustomHeader\\\" scope=\\\"transport\\\" value=\\\"example\\\"/>\\n<\\/sequence>\\n\"\r\n}",
                "summary": "Get an API specific mediation policy",
                "description": "This operation can be used to retrieve a particular API specific mediation policy.\n",
                "tags": [
                    "Mediation Policy (Individual)"
                ]
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:mediation_policy_manage"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer fb2a0784-f60c-3276-8fde-5b0f70e61ecc\" -X DELETE https://localhost:9443/api/am/publisher/v0.14/apis/40082986-6488-4b86-801a-b0b069d4588c/policies/mediation/60f5146d-1774-405d-86b3-9b040ac266d5",
                "x-wso2-request": "DELETE https://localhost:9443/api/am/publisher/v0.14/apis/40082986-6488-4b86-801a-b0b069d4588c/policies/mediation/60f5146d-1774-405d-86b3-9b040ac266d5\r\nAuthorization: Bearer fb2a0784-f60c-3276-8fde-5b0f70e61ecc",
                "x-wso2-response": "HTTP/1.1 200 OK",
                "summary": "Delete an API specific mediation policy",
                "description": "This operation can be used to delete an existing API specific mediation policy providing the Id of the API and the Id of the mediation policy.\n",
                "tags": [
                    "Mediation Policy (Individual)"
                ]
            },
            "put": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:mediation_policy_manage"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer 9e41fae2-3ada-3dd1-8f12-2077202f4285\" -H \"Content-Type: application/json\" -X PUT -d @data.json https://localhost:9443/api/am/publisher/v0.14/apis/40082986-6488-4b86-801a-b0b069d4588c/policies/mediation/820fdcf7-7258-42b5-809e-674b893644d1",
                "x-wso2-request": "PUT https://localhost:9443/api/am/publisher/v0.14/apis/40082986-6488-4b86-801a-b0b069d4588c/policies/mediation/820fdcf7-7258-42b5-809e-674b893644d1\r\nContent-Type: application/json\r\nAuthorization: Bearer 9e41fae2-3ada-3dd1-8f12-2077202f4285\r\n\r\n{\r\n   \"name\": \"add_custom_header_fault\",\r\n   \"type\": \"fault\",\r\n   \"config\": \"<sequence xmlns=\\\"http://ws.apache.org/ns/synapse\\\" name=\\\"add_custom_header_fault\\\">\\n    <property name=\\\"C[...]",
                "x-wso2-response": "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\r\n   \"id\": \"a7365481-5b3f-463c-a646-a498895ac210\",\r\n   \"name\": \"add_custom_header_fault\",\r\n   \"type\": \"fault\",\r\n   \"config\": \"<sequence xmlns=\\\"http://ws.apache.org/ns/synapse\\\" name=\\\"add_custom_header_fault\\\">\\n    <property name=\\\"CustomHeader\\\" scope=\\\"transport\\\" value=\\\"example\\\"/>\\n<\\/sequence>\\n\"\r\n}",
                "summary": "Update an API specific mediation policy",
                "description": "This operation can be used to update an existing mediation policy of an API.\n",
                "tags": [
                    "Mediation Policy (Individual)"
                ]
            }
        },
        "/apis/{apiId}/wsdl": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/wsdl",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/wsdl\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\nContent-Length: 329\n\n{\n   \"paths\": {\"/*\": {\"get\":    {\n      \"x-auth-type\": \"Application\",\n      \"x-throttling-policy\": \"Unlimited\",\n      \"responses\": {\"200\": {\"description\": \"OK\"}}\n   }}},\n   \"x-wso2-security\": {\"apim\": {\"x-wso2-scopes\": []}},\n   \"swagger\": \"2.0\",\n   \"info\":    {\n      \"title\": \"PhoneVerification\",\n      \"description\": \"Verify a phone number[...]",
                "summary": "Get WSDL definition",
                "description": "This operation can be used to retrieve the WSDL definition of an API.\n",
                "tags": [
                    "API (Individual)"
                ]
            },
            "put": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_update"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\" -F inlineContent=\"{\\\"paths\\\":{\\\"\\/*\\\":{\\\"get\\\":{\\\"x-auth-type\\\":\\\"Application\\\",\\\"x-throttling-policy\\\":\\\"Unlimited\\\",\\\"responses\\\":{\\\"200\\\":{\\\"description\\\":\\\"OK\\\"}}}}},\\\"x-wso2-security\\\":{\\\"apim\\\":{\\\"x-wso2-scopes\\\":[]}},\\\"swagger\\\":\\\"2.0\\\",\\\"info\\\":{\\\"title\\\":\\\"PhoneVerification\\\",\\\"description\\\":\\\"Verify [...]",
                "x-wso2-request": "PUT https://127.0.0.1:9443/api/am/publisher/v1.0/apis/8848faaa-7fd1-478a-baa2-48a4ebb92c98/wsdl\nAuthorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\nContent-Length: 477\nContent-Type: multipart/form-data; boundary=------------------------4f51e636c0003d99\n\n--------------------------4f51e636c0003d99\nContent-Disposition: form-data; name=\"apiDefinition\"\n\n{\"paths\":{\"\\/*\":{\"get\":{\"x-auth-type\":\"Application\",\"x-throttling-policy\":\"Unlimited[...]",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"paths\": {\"/*\": {\"get\":    {\n      \"x-auth-type\": \"Application\",\n      \"x-throttling-policy\": \"Unlimited\",\n      \"responses\": {\"200\": {\"description\": \"OK\"}}\n   }}},\n   \"x-wso2-security\": {\"apim\": {\"x-wso2-scopes\": []}},\n   \"swagger\": \"2.0\",\n   \"info\":    {\n      \"title\": \"PhoneVerification\",\n      \"description\": \"Verify a phone number\",\n      \"contact\[...]",
                "summary": "Update WSDL definition",
                "description": "This operation can be used to update the WSDL definition of an existing API. WSDL to be updated is passed as a form data parameter `inlineContent`.\n",
                "tags": [
                    "API (Individual)"
                ]
            }
        },
        "/apis/{apiId}/scopes": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/scopes\"",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/scopes\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json",
                "summary": "Get a list of scopes of an API",
                "description": "This operation can be used to retrieve a list of scopes belonging to an API by providing the id of the API.\n",
                "tags": [
                    "Scope (Collection)"
                ]
            },
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -H \"Content-Type: application/json\" -X POST -d @data.json \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/96077508-fd01-4fae-bc64-5de0e2baf43c/scopes\"",
                "x-wso2-request": "POST https://127.0.0.1:9443/api/am/publisher/v1.0/apis/96077508-fd01-4fae-bc64-5de0e2baf43c/scopes\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\nContent-Type: application/json",
                "x-wso2-response": "HTTP/1.1 201 Created\nLocation: https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/scopes/ffd5790d-b7a9-4cb6-b76a-f8b83ecdd058\nContent-Type: application/json",
                "summary": "Add a new scope to an API",
                "description": "This operation can be used to add a new scope to an API.\n",
                "tags": [
                    "Scope (Collection)"
                ]
            }
        },
        "/apis/{apiId}/scopes/{name}": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/scopes/read\"",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/scopes/read\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n",
                "summary": "Get a scope of an API",
                "description": "This operation can be used to retrieve a particular scope's metadata associated with an API.\n",
                "tags": [
                    "Scope (Individual)"
                ]
            },
            "put": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_update"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization:Bearer b0982cd2aacd463ff5f63cd5ebe58f4a\" -H \"Content-Type: application/json\" -X PUT -d data.json \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/96077508-fd01-4fae-bc64-5de0e2baf43c/scopes/read\"",
                "x-wso2-request": "PUT https://127.0.0.1:9443/api/am/publisher/v1.0/apis/96077508-fd01-4fae-bc64-5de0e2baf43c/scopes/read\nAuthorization:Bearer b0982cd2aacd463ff5f63cd5ebe58f4a\nContent-Type: application/json\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n",
                "summary": "Update a Scope of an API",
                "description": "This operation can be used to update scope of an API\n",
                "tags": [
                    "Scope (Individual)"
                ]
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_update"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X DELETE https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/scopes/ffd5790d-b7a9-4cb6-b76a-f8b83ecdd058",
                "x-wso2-request": "DELETE https://127.0.0.1:9443/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/scopes/ffd5790d-b7a9-4cb6-b76a-f8b83ecdd058\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK",
                "summary": "Delete a scope of an API",
                "description": "This operation can be used to delete a scope associated with an API.\n",
                "tags": [
                    "Scope (Individual)"
                ]
            }
        },
        "/subscriptions": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:subscription_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" \"https://127.0.0.1:9443/api/am/publisher/v1.0/subscriptions?apiId=890a4f4d-09eb-4877-a323-57f6ce2ed79b\"",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/subscriptions?apiId=890a4f4d-09eb-4877-a323-57f6ce2ed79b\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n \n{\n   \"previous\": \"\",\n   \"list\":    [\n            {\n         \"subscriptionId\": \"64eca60b-2e55-4c38-8603-e9e6bad7d809\",\n         \"policy\": \"Gold\",\n         \"apiIdentifier\": \"admin-PhoneVerification-1.0.0\",\n         \"applicationId\": \"896658a0-b4ee-4535-bbfa-806c894a4015\",\n         \"lifeCycleStatus\": \"UNBLOCKED\"\n      },\n            {\n         \"subscriptionId\": \"7ac22c34-87[...]",
                "summary": "Get all Subscriptions",
                "description": "This operation can be used to retrieve a list of subscriptions of the user associated with the provided access token. This operation is capable of\n\n1. Retrieving all subscriptions for the user's APIs.\n`GET https://127.0.0.1:9443/api/am/publisher/v1.0/subscriptions`\n\n2. Retrieving subscriptions for a specific API.\n`GET https://127.0.0.1:9443/api/am/publisher/v1.0/subscriptions?apiId=c43a325c-260b-4302-81cb-768eafaa3aed`\n",
                "tags": [
                    "Subscription (Collection)"
                ]
            }
        },
        "/subscriptions/{subscriptionId}": {
            "get": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9443/api/am/publisher/v1.0/subscriptions/64eca60b-2e55-4c38-8603-e9e6bad7d809",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/subscriptions/64eca60b-2e55-4c38-8603-e9e6bad7d809\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"subscriptionId\": \"64eca60b-2e55-4c38-8603-e9e6bad7d809\",\n   \"policy\": \"Gold\",\n   \"apiIdentifier\": \"admin-PhoneVerification-1.0.0\",\n   \"applicationId\": \"896658a0-b4ee-4535-bbfa-806c894a4015\",\n   \"lifeCycleStatus\": \"UNBLOCKED\"\n}",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:subscription_view"
                        ]
                    }
                ],
                "summary": "Get details of a subscription",
                "description": "This operation can be used to get details of a single subscription.\n",
                "tags": [
                    "Subscription (Individual)"
                ]
            }
        },
        "/subscriptions/block-subscription": {
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:subscription_block"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X POST \"https://127.0.0.1:9443/api/am/publisher/v1.0/subscriptions/block-subscription?subscriptionId=64eca60b-2e55-4c38-8603-e9e6bad7d809&blockState=PROD_ONLY_BLOCKED\"",
                "x-wso2-request": "POST https://127.0.0.1:9443/api/am/publisher/v1.0/subscriptions/block-subscription?subscriptionId=64eca60b-2e55-4c38-8603-e9e6bad7d809&blockState=PROD_ONLY_BLOCKED\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n \n{\n   \"subscriptionId\": \"64eca60b-2e55-4c38-8603-e9e6bad7d809\",\n   \"policy\": \"Gold\",\n   \"apiIdentifier\": \"admin-PhoneVerification-1.0.0\",\n   \"applicationId\": \"896658a0-b4ee-4535-bbfa-806c894a4015\",\n   \"lifeCycleStatus\": \"PROD_ONLY_BLOCKED\"\n}",
                "summary": "Block a subscription",
                "description": "This operation can be used to block a subscription. Along with the request, `blockState` must be specified as a query parameter.\n\n1. `BLOCKED` : Subscription is completely blocked for both Production and Sandbox environments.\n2. `PROD_ONLY_BLOCKED` : Subscription is blocked for Production environment only.\n",
                "tags": [
                    "Subscription (Individual)"
                ]
            }
        },
        "/subscriptions/unblock-subscription": {
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:subscription_block"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X POST \"https://127.0.0.1:9443/api/am/publisher/v1.0/subscriptions/unblock-subscription?subscriptionId=64eca60b-2e55-4c38-8603-e9e6bad7d809\"",
                "x-wso2-request": "POST https://127.0.0.1:9443/api/am/publisher/v1.0/subscriptions/unblock-subscription?subscriptionId=64eca60b-2e55-4c38-8603-e9e6bad7d809\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8`\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"subscriptionId\": \"64eca60b-2e55-4c38-8603-e9e6bad7d809\",\n   \"policy\": \"Gold\",\n   \"apiIdentifier\": \"admin-PhoneVerification-1.0.0\",\n   \"applicationId\": \"896658a0-b4ee-4535-bbfa-806c894a4015\",\n   \"lifeCycleStatus\": \"UNBLOCKED\"\n} ",
                "summary": "Unblock a Subscription",
                "description": "This operation can be used to unblock a subscription specifying the subscription Id. The subscription will be fully unblocked after performing this operation.\n",
                "tags": [
                    "Subscription (Individual)"
                ]
            }
        },
        "/policies/{policyLevel}": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9443/api/am/publisher/v1.0/policies/api",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/policies/api\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n\n{\n   \"previous\": \"\",\n   \"list\":    [\n            {\n         \"unitTime\": 60000,\n         \"tierPlan\": \"FREE\",\n         \"tierLevel\": \"api\",\n         \"stopOnQuotaReach\": true,\n         \"requestCount\": 1,\n         \"description\": \"Allows 1 request(s) per minute.\",\n         \"name\": \"Bronze\",\n         \"attributes\": {}\n      },\n            {\n         \"unitTime\": 60000,\n [...]",
                "summary": "Get all policies",
                "description": "This operation can be used to list the available policies for a given policy level. Tier level should be specified as a path parameter and should be one of `api`, `application` and `resource`.\n",
                "tags": [
                    "Throttling Tier (Collection)"
                ]
            }
        },
        "/policies/{policyLevel}/{policyName}": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9443/api/am/publisher/v1.0/policies/api/Bronze",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/policies/api/Bronze\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"unitTime\": 60000,\n   \"tierPlan\": \"FREE\",\n   \"policyLevel\": \"api\",\n   \"stopOnQuotaReach\": true,\n   \"requestCount\": 1,\n   \"description\": \"Allows 1 request(s) per minute.\",\n   \"name\": \"Bronze\",\n   \"attributes\": {}\n}",
                "summary": "Get details of a policy",
                "description": "This operation can be used to retrieve details of a single policy by specifying the policy level and policy name.\n",
                "tags": [
                    "Throttling Tier (Individual)"
                ]
            }
        },
        "/environments": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" \"https://localhost:9443/api/am/publisher/v0.14/environments\"",
                "x-wso2-request": "GET https://localhost:9443/api/am/publisher/v0.14/environments\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"list\": [   {\n      \"showInApiConsole\": true,\n      \"serverUrl\": \"https://localhost:9443/services/\",\n      \"endpoints\":       {\n         \"http\": \"http://localhost:8280\",\n         \"https\": \"https://localhost:8243\"\n      },\n      \"name\": \"Production and Sandbox\",\n      \"type\": \"hybrid\"\n   }],\n   \"count\": 1\n}",
                "summary": "Get all gateway environments",
                "description": "This operation can be used to retrieve the list of gateway environments available.\n",
                "tags": [
                    "Environment (Collection)"
                ]
            }
        },
        "/policies/mediation": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:mediation_policy_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/publisher/v0.14/policies/mediation",
                "x-wso2-request": "GET https://localhost:9443/api/am/publisher/v0.14/policies/mediation\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\r\n   \"count\": 10,\r\n   \"next\": null,\r\n   \"previous\": null,\r\n   \"list\":    [\r\n            {\r\n         \"name\": \"debug_json_fault\",\r\n         \"id\": \"563de8f3-dd1d-4ec7-afc2-d158c663ed34\",\r\n         \"type\": \"fault\"\r\n      },\r\n            {\r\n         \"name\": \"json_fault\",\r\n         \"id\": \"f9c36f4d-a2b6-41e7-b311-d358a47916be\",\r\n         \"type\": \"fault\"[...]",
                "summary": "Get all global level mediation policies\n",
                "description": "This operation provides you a list of available all global level mediation policies.\n",
                "tags": [
                    "Mediation Policy (Collection)"
                ]
            }
        },
        "/client-certificates": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:client_certificates_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X GET https://localhost:9443/api/am/publisher/v0.14/client-certificates -H 'authorization: Bearer f80b8c34-01bc-3ac2-99b6-4873e45c861c'",
                "x-wso2-request": "GET https://localhost:9443/api/am/publisher/v0.14/client-certificates  -H 'authorization: Bearer f80b8c34-01bc-3ac2-99b6-4873e45c861c'",
                "x-wso2-response": "HTTP/1.1 200 OK {\"count\":1,\"next\":\"\",\"previous\":\"\",\"certificates\":[{\"alias\":\"newtest1\", \"apiId\":\"admin-mesting12da1-1.0.0\",\"tier\":\"Bronze\"}],\"pagination\":{\"total\":1, \"offset\":0,\"limit\":25}}",
                "summary": "Retrieve/ Search uploaded Client Certificates.",
                "description": "This operation can be used to retrieve and search the uploaded client certificates.\n",
                "tags": [
                    "ClientCertificates (Collection)"
                ]
            },
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:client_certificates_add"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X POST https://localhost:9443/api/am/publisher/v0.14/client-certificates -H 'authorization: Bearer f2f562bd-f6d9-3fad-b48d-72ab5702c98a' -H 'content-type: multipart/form-data' -F certificate=@test.crt -F alias=alias -F apiId=fea749dd-d548-4a8b-b308-34903b39a34b -F tier=Gold",
                "x-wso2-request": "POST https://localhost:9443/api/am/publisher/v0.14/client-certificates -H 'authorization: Bearer f2f562bd-f6d9-3fad-b48d-72ab5702c98a' -H 'content-type: multipart/form-data' -F certificate=@test.crt -F alias=alias -F apiId=fea749dd-d548-4a8b-b308-34903b39a34b -F tier=Gold",
                "x-wso2-response": "HTTP/1.1 201 Created Location: https://localhost:9443/api/am/publisher/v0.14/client-certificates?alias=newtest1 Date: Tue, 09 Oct 2018 16:18:10 GMT Content-Type: application/json Transfer-Encoding: chunked Server: WSO2 Carbon Server {\"alias\":\"alias\",\"apiId\":\"fea749dd-d548-4a8b-b308-34903b39a34b\",\"tier\":\"Gold\"}",
                "summary": "Upload a new certificate.",
                "description": "This operation can be used to upload a new certificate for an endpoint.\n",
                "tags": [
                    "ClientCertificates (Individual)"
                ]
            }
        },
        "/client-certificates/{alias}": {
            "put": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:client_certificates_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X PUT https://localhost:9443/api/am/publisher/v0.14/client-certificates/newtest1 -H 'authorization: Bearer f80b8c34-01bc-3ac2-99b6-4873e45c861c' -F tier=Bronze",
                "x-wso2-request": "PUT https://localhost:9443/api/am/publisher/v0.14/client-certificates/newtest1 -H 'authorization: Bearer f80b8c34-01bc-3ac2-99b6-4873e45c861c' -F tier=Bronze",
                "x-wso2-response": "HTTP/1.1 200 OK\r\n {\r\n\"alias\":\"newtest1\",\r\n\"apiId\":\"fea749dd-d548-4a8b-b308-34903b39a34b\",\r\n \"tier\":\"Gold\"\r\n}\r\n",
                "summary": "Update a certificate.",
                "description": "This operation can be used to update an uploaded certificate.\n",
                "tags": [
                    "ClientCertificates (Individual)"
                ]
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:client_certificates_update"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X DELETE https://localhost:9443/api/am/publisher/v0.14/client-certificates/newtest1 -H 'authorization: Bearer f80b8c34-01bc-3ac2-99b6-4873e45c861c' ",
                "x-wso2-request": "DELETE https://localhost:9443/api/am/publisher/v0.14/client-certificates/newtest1 -H 'authorization: Bearer f80b8c34-01bc-3ac2-99b6-4873e45c861c'",
                "x-wso2-response": "HTTP/1.1 200 OK",
                "summary": "Delete a certificate.",
                "description": "This operation can be used to delete an uploaded certificate.\n",
                "tags": [
                    "ClientCertificates (Individual)"
                ]
            },
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:client_certificates_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X GET https://localhost:9443/api/am/publisher/v0.14/client-certificates/newtest1 -H 'authorization: Bearer f80b8c34-01bc-3ac2-99b6-4873e45c861c'",
                "x-wso2-request": "GET https://apis.wso2.com/api/am/publisher/v0.14/client-certificates/newtest1 Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8",
                "x-wso2-response": "HTTP/1.1 200 OK Date: Tue, 09 Oct 2018 16:25:43 GMT Content-Type: application/json Transfer-Encoding: chunked Server: WSO2 Carbon Server {\"status\":\"Active\",\"validity\":{\"from\":\"Fri Sep 14 15:46:22 IST 2018\",\"to\":\"Sat Sep 14 15:46:22 IST 2019\"},\"version\":\"3\",\"subject\":\"EMAILADDRESS=wso2@wso2.com, CN=WSO2, OU=test, O=WSO2, L=colombo, ST=Some-State, C=CA\"}",
                "summary": "Get the certificate information.",
                "description": "This operation can be used to get the information about a certificate.\n",
                "tags": [
                    "ClientCertificates (Individual)"
                ]
            }
        },
        "/client-certificates/{alias}/content": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:client_certificates_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X GET https://localhost:9443/api/am/publisher/v0.14/client-certificates/newtest1/content -H 'authorization: Bearer f80b8c34-01bc-3ac2-99b6-4873e45c861c'",
                "x-wso2-request": "GET https://apis.wso2.com/api/am/publisher/v0.14/certificates/wso2carbon/content Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8",
                "x-wso2-response": "HTTP/1.1 200 OK Content-Disposition: attachment; filename=\"newtest1.crt\" Date: Tue, 09 Oct 2018 16:21:25 GMT Content-Type: application/octet-stream Content-Length: 997 Server: WSO2 Carbon Server",
                "summary": "Download a certificate.",
                "description": "This operation can be used to download a certificate which matches the given alias.\n",
                "tags": [
                    "ClientCertificates (Individual)"
                ]
            }
        },
        "/endpoints": {
            "get": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" \"https://127.0.0.1:9443/api/am/publisher/v1.0/endpoints\"",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/endpoints\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n  \"list\": [\n    {\n      \"id\": \"01234567-0123-0123-0123-012345678901\",\n      \"name\": \"Endpoint 1\",\n      \"endpointConfig\": {\n        \"serviceUrl\": \"http://192.168.56.1:8281\",\n        \"timeout\": 1000\n      },\n      \"endpointSecurity\": {\n        \"enabled\": false\n      },\n      \"maxTps\": 1000,\n      \"type\": \"http\"\n    }\n  ],\n  \"count\": 1\n}",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "summary": "Get all endpoints",
                "description": "This operation can be used to retrieve the list of endpoints available.\n",
                "tags": [
                    "Endpoint (Collection)"
                ]
            },
            "post": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -H \"Content-Type: application/json\" -X POST -d @data.json \"https://127.0.0.1:9443/api/am/publisher/v1.0/endpoints\"",
                "x-wso2-request": "",
                "x-wso2-response": "",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "summary": "Add a new endpoint",
                "description": "This operation can be used to add a new endpoint.\n",
                "tags": [
                    "Endpoint (Collection)"
                ]
            },
            "head": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "summary": "Check given Endpoint is already exist\n",
                "description": "Using this operation, you can check a given Endpoint name is already used. You need to provide the name you want to check.\n",
                "tags": [
                    "Endpoint (Collection)"
                ]
            }
        },
        "/endpoints/{endpointId}": {
            "get": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" \"https://127.0.0.1:9443/api/am/publisher/v1.0/endpoints/1234-123-2111-345\"",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/endpoints/1234-123-2111-345\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"list\": [   {\n      \"showInApiConsole\": true,\n      \"serverUrl\": \"https://192.168.56.1:9444//services/\",\n      \"endpoints\":       {\n         \"http\": \"http://192.168.56.1:8281\",\n         \"https\": \"https://192.168.56.1:8244\"\n      },\n      \"name\": \"Production and Sandbox\",\n      \"type\": \"hybrid\"\n   }],\n   \"count\": 1\n}",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "summary": "Get specific endpoints",
                "description": "This operation can be used to retrieve endpoint specific details.\n",
                "tags": [
                    "Endpoint (individual)"
                ]
            },
            "put": {
                "x-wso2-curl": "",
                "x-wso2-request": "",
                "x-wso2-response": "",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "summary": "Update a Tier",
                "description": "This operation can be used to update an existing endpoint.\n`PUT https://127.0.0.1:9443/api/am/publisher/v1.0/endpoints/api/Low`\n",
                "tags": [
                    "Endpoint (individual)"
                ]
            },
            "delete": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X DELETE https://127.0.0.1:9443/api/am/publisher/v1.0/endpoints/6fb74674-4ab8-4b52-9886-f9a376985060",
                "x-wso2-request": "DELETE https://127.0.0.1:9443/api/am/publisher/v1.0/endpoints/6fb74674-4ab8-4b52-9886-f9a376985060\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "summary": "Delete an endpoint",
                "description": "This operation can be used to delete an existing Endpoint proving the Id of the Endpoint.\n",
                "tags": [
                    "Endpoint (individual)"
                ]
            }
        },
        "/export/apis": {
            "get": {
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/publisher/v1.0/export/apis?query=xxx > exported-apis.zip",
                "x-wso2-request": "GET https://127.0.0.1:9443/api/am/publisher/v1.0/export/apis?query=xxx\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\n Connection: keep-alive\n  Content-Disposition: attachment; filename=\"exported-apis.zip\"\n  Content-Type: application/zip",
                "summary": "Export information related to an API.",
                "description": "This operation can be used to export information related to a particular API.\n",
                "tags": [
                    "Export Configuration"
                ]
            }
        },
        "/import/apis": {
            "put": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_update"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -F \"file=@exported.zip\" -X PUT -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/publisher/v1.0/import/apis",
                "x-wso2-request": "PUT https://127.0.0.1:9443/api/am/publisher/v1.0/import/apis\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\"count\":2,\"list\":[{\"id\":\"4df90edc-f76b-4b19-bf57-7d161fa04467\",\"name\":\"testApi2\",\"context\":\"/test2\",\"version\":\"2.0.3\",\"provider\":\"admin\",\"lifeCycleStatus\":\"Created\",\"workflowStatus\":\"APPROVED\"},{\"id\":\"4066bc9e-1d87-4296-bcca-f6e38d3da6d0\",\"name\":\"testApi\",\"context\":\"/testApi\",\"version\":\"1.0.0\",\"provider\":\"admin\",\"lifeCycleStatus\":\"Created\",\"workflowStat[...]",
                "summary": "Imports API(s).",
                "description": "This operation can be used to import one or more existing APIs.\n",
                "tags": [
                    "Import Configuration"
                ]
            },
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_create"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -F \"file=@exported.zip\" -X POST -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/publisher/v1.0/import/apis",
                "x-wso2-request": "POST https://127.0.0.1:9443/api/am/publisher/v1.0/import/apis\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\"count\":2,\"list\":[{\"id\":\"4df90edc-f76b-4b19-bf57-7d161fa04467\",\"name\":\"testApi2\",\"context\":\"/test2\",\"version\":\"2.0.3\",\"provider\":\"admin\",\"lifeCycleStatus\":\"Created\",\"workflowStatus\":\"APPROVED\"},{\"id\":\"4066bc9e-1d87-4296-bcca-f6e38d3da6d0\",\"name\":\"testApi\",\"context\":\"/testApi\",\"version\":\"1.0.0\",\"provider\":\"admin\",\"lifeCycleStatus\":\"Created\",\"workflowStat[...]",
                "summary": "Imports API(s).",
                "description": "This operation can be used to import one or more existing APIs.\n",
                "tags": [
                    "Import Configuration"
                ]
            }
        },
        "/threat-protection-policies": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "summary": "Get All Threat Protection Policies",
                "description": "This can be used to get all defined threat protection policies",
                "tags": [
                    "Threat Protection Policies"
                ]
            }
        },
        "/threat-protection-policies/{policyId}": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "summary": "Get a threat protection policy",
                "tags": [
                    "Threat Protection Policy"
                ]
            }
        },
        "/endpoint-certificates": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:ep_certificates_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X GET -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -H \"Content-Type: application/json\" \"https://localhost:9443/api/am/publisher/v0.14/certificates\"",
                "x-wso2-request": "GET https://localhost:9443/api/am/publisher/v0.14/certificates?alias=wso2carbon&endpoint=https://www.abc.com",
                "x-wso2-response": "HTTP/1.1 200 OK \n\n{\n  \"count\":1,\n  \"next\":\"\",\n  \"previous\":\"\",\n\"certificates\":[\n   {\n    \"alias\":\"wso2carbon\",\n    \"endpoint\":\"https://www.abc.com\"\n   }\n],\n  \"pagination\":{\n    \"total\":1,\n          \"offset\":0,\n          \"limit\":25\n   } \n}",
                "summary": "Retrieve/Search uploaded certificates.",
                "description": "This operation can be used to retrieve and search the uploaded certificates.\n",
                "tags": [
                    "Certificates (Collection)"
                ]
            },
            "post": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:ep_certificates_add"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X POST -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -H \"Content-Type: multipart/form-data\"  -F \"certificate=@/home/user/wso2carbon.cert\" -F \"alias=wso2carbon\" -F \"endpoint=https://www.abc.com\" \"https://localhost:9443/api/am/publisher/v0.14/certificates/certificate\"",
                "x-wso2-request": "POST https://localhost:9443/api/am/publisher/v0.14/certificates/certificate \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -F \"certificate=/home/user/wso2carbon.cert\" -F \"alias=wso2carbon\" -F \"endpoint=https://www.abc.com\"",
                "x-wso2-response": "HTTP/1.1 201 Created Location: https://localhost:9443/api/am/publisher/v0.14/client-certificates?alias=newtest1 Date: Fri, 05 Oct 2018 09:50:48 GMT Content-Type: application/json Transfer-Encoding: chunked Server: WSO2 Carbon Server {\"alias\": \"newtest1\",\"apiId\": \"4624bdfb-6acd-465a-8454-bac9c4c94d88\",\"tier\": \"Gold\"}",
                "summary": "Upload a new Certificate.",
                "description": "This operation can be used to upload a new certificate for an endpoint.\n",
                "tags": [
                    "Certificates (Individual)"
                ]
            }
        },
        "/endpoint-certificates/{alias}": {
            "put": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:ep_certificates_update"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X PUT -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -H \"Content-Type:multipart/form-data\" -F \"certificate=@/home/user/wso2carbon.cert\" \"https://localhost:9443/api/am/publisher/v0.14/certificates/wso2carbon\"",
                "x-wso2-request": "PUT https://localhost:9443/api/am/publisher/v0.14/certificates/wso2carbon Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8 -F  \"certificate=@/home/user/wso2carbon.cert\"",
                "x-wso2-response": "HTTP/1.1 200 OK\r\n {\"alias\":wso2carbon,\"endpoint\":\"https://www.abc.com\"}",
                "summary": "Update a certificate.",
                "description": "This operation can be used to update an uploaded certificate.\n",
                "tags": [
                    "Certificates (Individual)"
                ]
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:ep_certificates_update"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X DELETE -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" \"https://localhost:9443/api/am/publisher/v0.14/certificates/wso2carbon\"",
                "x-wso2-request": "DELETE https://localhost:9443/api/am/publisher/v0.14/certificates/wso2carbon Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8",
                "x-wso2-response": "HTTP/1.1 200 OK",
                "summary": "Delete a certificate.",
                "description": "This operation can be used to delete an uploaded certificate.\n",
                "tags": [
                    "Certificates (Individual)"
                ]
            },
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:ep_certificates_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X GET \"https://apis.wso2.com/api/am/publisher/v0.14/certificates/wso2carbon\" -H  \"accept: application/json\"",
                "x-wso2-request": "GET https://apis.wso2.com/api/am/publisher/v0.14/certificates/wso2carbon Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8",
                "x-wso2-response": "HTTP/1.1 200 OK \nContent-Type: application/json\r\n {\n  \"status\":\"Active\",\n  \"validity\":{\n    \"from\":\"Fri May 04 19:01:01 IST 2018\",\n    \"to\":\"Thu Aug 02 19:01:01 IST 2018\"\n  }\n,  \"version\":\"3\",\n  \"subject\":\"CN=wso2.com, OU=wso2, O=wso2, L=Colombo, ST=Western, C=LK\"\n}",
                "summary": "Get the certificate information.",
                "description": "This operation can be used to get the information about a certificate.\n",
                "tags": [
                    "Certificates (Individual)"
                ]
            }
        },
        "/endpoint-certificates/{alias}/content": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:ep_certificates_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -X GET \"https://apis.wso2.com/api/am/publisher/v0.14/certificates/wso2carbon/content\" -H \"accept: application/json\"",
                "x-wso2-request": "GET https://apis.wso2.com/api/am/publisher/v0.14/certificates/wso2carbon/content Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8",
                "x-wso2-response": "HTTP/1.1 200 OK\r\n [content of the certificate]",
                "summary": "Download a certificate.",
                "description": "This operation can be used to download a certificate which matches the given alias.\n",
                "tags": [
                    "Certificates (Individual)"
                ]
            }
        },
        "/search": {
            "get": {
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:api_view"
                        ]
                    }
                ],
                "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/publisher/v0.13/search=query?sample",
                "x-wso2-request": "GET https://localhost:9443/api/am/publisher/v0.13/search\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
                "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"previous\": \"\",\n   \"list\":    [\n            {\n         \"provider\": \"admin\",\n         \"version\": \"1.0.0\",\n         \"description\": \"This sample API provides Account Status Validation\",\n         \"name\": \"AccountVal\",\n         \"context\": \"/account\",\n         \"id\": \"2e81f147-c8a8-4f68-b4f0-69e0e7510b01\",\n         \"status\": \"PUBLISHED\"\n      },\n            {\n      [...]",
                "summary": "Retrieve/Search APIs and API Documents by content\n",
                "description": "This operation provides you a list of available APIs and API Documents qualifying the given keyword match.\n",
                "tags": [
                    "API (Collection)"
                ]
            }
        },
        "/settings": {
            "get": {
                "summary": "Retreive publisher settings",
                "security": [
                    {
                        "OAuth2Security": [
                            "apim:publisher_setting"
                        ]
                    }
                ],
                "description": "Retreive publisher settings\n"
            }
        }
    }
}
