#   Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#---------------------------------------------------------------------------

openapi: "3.0.0"
info:
  title: Service Catalog APIs
  description: |
    This specifies a **RESTful API** for Service Catalog.
  version: "1.0"
servers:
  - url: 'https://apis.wso2.com/api/service-catalog/v1'
  - url: 'http://apis.wso2.com/api/service-catalog/v1'

paths:
  /service-catalogs:
    #-----------------------------------------------------
    # Retrieve the array of all Service Catalogs
    #-----------------------------------------------------
    get:
      summary: |
        Retrieve all Service Catalogs
      description: |
        This operation provides you an array of available Service Catalogs.
      tags:
        - Service Catalog
      security:
        - default:
          - service_catalog:view
      operationId: getServiceCatalogs
    #-----------------------------------------------------
    # Create a new Service Catalog
    #-----------------------------------------------------
    post:
      summary: Create a new Service Catalog
      description: |
        This operation can be used to create a new Service Catalog specifying the details of the Service Catalog
        in the payload.
      security:
        - default:
          - service_catalog:create
      tags:
        - Service Catalog
      operationId: addServiceCatalog
  /service-catalogs/{catalogId}:
    #-----------------------------------------------------
    # Retrieve the details of a Service Catalog
    #-----------------------------------------------------
    get:
      summary: Get details of a Service Catalog
      description: |
        Using this operation, you can retrieve complete details of a single Service Catalog using the CatalogId.
      security:
        - default:
          - service_catalog:view
      tags:
        - Service Catalog
      operationId: getServiceCatalogByUUID
    #-----------------------------------------------------
    # Update an existing Service Catalog
    #-----------------------------------------------------
    put:
      summary: Update an existing Service Catalog
      description: |
        This operation can be used to update an existing Service Catalog
      security:
        - default:
          - service_catalog:manage
      tags:
        - Service Catalog
      operationId: updateServiceCatalog
    #-----------------------------------------------------
    # Delete an Service Catalog
    #-----------------------------------------------------
    delete:
      summary: Delete an Service Catalog
      description: |
        This operation can be used to delete an existing Service Catalog proving the Id of the Service Catalog.
      security:
        - default:
          - service_catalog:delete
      tags:
       - Service Catalog
      operationId: deleteServiceCatalog
  #-----------------------------------------------------
  # Retrieve all entries in a Service Catalog
  #-----------------------------------------------------
  /service-catalogs/{catalogId}/entries:
    get:
      summary: Get All entries in the registry
      operationId: getAllEntriesInCatalog
      security:
        - default:
          - service_catalog:entry_view
      tags:
        - Service Catalog Entries
  #-----------------------------------------------------
  # Create new entry in entry in Service Catalog
  #-----------------------------------------------------
    post:
      summary: Create a new Service Catalog Entry
      description: |
        This operation can be used to create a new Service Catalog Entry specifying the details of the Entry in the
        payload.
      security:
        - default:
          - service_catalog:entry_write
      tags:
        - Service Catalog Entries
      operationId: createCatalogEntry
  /service-catalogs/{catalogId}/entries/{entryId}:
    #-----------------------------------------------------
    # Retrieve an entry in a Service Catalog
    #-----------------------------------------------------
    get:
      summary: Retrieve a specific Entry in a Catalog
      description: |
        Using this operation, you can retrieve a specific entry in a single Catalog using the EntryId and CatalogId.
      security:
        - default:
          - service_catalog:entry_view
      operationId: getCatalogEntryByUuid
      tags:
        - Service Catalog Entries
    #-----------------------------------------------------
    # Update an entry in a Service Catalog
    #-----------------------------------------------------
    put:
      summary: Update an existing Entry in a Service Catalog
      description: |
        This operation can be used to update an existing Entry in Service Catalog with the details of the Entry in the
         payload.
      security:
        - default:
          - service_catalog:entry_write
      operationId: updateCatalogEntry
      tags:
        - Service Catalog Entries
    #-----------------------------------------------------
    # Delete an entry in a Service Catalog
    #-----------------------------------------------------
    delete:
      summary: Delete an Entry in a Service Catalog
      description: |
        This operation can be used to delete an existing Entry in Catalog by specifying the catalogId and entryId.
      security:
        - default:
          - service_catalog:entry_write
      operationId: deleteCatalogEntry
      tags:
        - Service Catalog Entries
  #-----------------------------------------------------
  # Retrieve definition file of an entry in Service Catalog
  #-----------------------------------------------------
  /service-catalogs/{catalogId}/entries/{entryId}/definition:
    get:
      summary: Retrieve the definition file of a specific Entry in a Catalog
      description: |
        Using this operation, you can retrieve the definition file of a specific entry in a Catalog using the EntryId
        and CatalogId.
      security:
        - default:
          - service_catalog:entry_view
      operationId: getCatalogEntryDefinition
      tags:
        - Service Catalog Entries
  ######################################################
  # The Service Catalog settings List
  ######################################################
  /settings:
    #-----------------------------------------------------
    # Retrieve Service Catalog settings
    #-----------------------------------------------------
    get:
      summary: Retrieve Service Catalog settings
      description: |
        Retrieve Service Catalog settings
      operationId: getSettings
      tags:
        - Settings
components:
  #-------------------------------------------------------
  # The security schemes of resources used by some of the APIs
  #-------------------------------------------------------
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://example.com/oauth/authorize
          scopes:
            service_catalog:view: view service catalog
            service_catalog:create: create service catalog
            service_catalog:manage: update service catalog
            service_catalog:delete: delete service catalog
            service_catalog:entry_view: view service catalog entry
            service_catalog:entry_write: write service catalog entry

  #-------------------------------------------------------
  # The definitions of resources used by some of the APIs
  #-------------------------------------------------------
######################################################
# Parameters - required by some of the APIs above
######################################################