{
  "swagger": "2.0",
  "info": {
    "version": "v1.0",
    "title": "WSO2 API Manager - Store",
    "description": "This document specifies a **RESTful API** for WSO2 **API Manager** - Store.\n\nIt is written with [swagger 2](http://swagger.io/).\n",
    "contact": {
      "name": "WSO2",
      "url": "http://wso2.com/products/api-manager/",
      "email": "architecture@wso2.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "schemes": [
    "https",
    "http"
  ],
  "host": "apis.wso2.com",
  "basePath": "/api/am/store/v1.0",
  "x-wso2-security": {
    "apim": {
      "x-wso2-scopes": [
        {
          "description": "",
          "roles": "Internal/username",
          "name": "apim:subscribe",
          "key": "apim:subscribe"
        }
      ]
    }
  },
  "securityDefinitions": {
    "OAuth2Security": {
      "type": "oauth2",
      "flow": "password",
      "tokenUrl": "https://localhost:9443/token",
      "scopes": {
        "apim:subscribe": "Subscribe API",
        "apim:self-signup": "Self Sign-up",
        "apim:dedicated_gateway": "Updating dedicated Gateway"
      }
    }
  },
  "paths": {
    "/apis": {
      "get": {
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "summary": "Retrieve/Search APIs\n",
        "description": "Get a list of available APIs qualifying under a given search condition.\n",
        "tags": [
          "API (Collection)",
          "Retrieve"
        ]
      }
    },
    "/apis/{apiId}": {
      "get": {
        "summary": "Get details of an API",
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "description": "Get details of an API\n",
        "tags": [
          "API (Individual)",
          "Retrieve"
        ]
      }
    },
    "/apis/{apiId}/swagger": {
      "get": {
        "summary": "Get API swagger definition",
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "description": "Get the swagger of an API\n",
        "tags": [
          "API (Individual)",
          "Retrieve"
        ]
      }
    },
    "/apis/{apiId}/sdks/{language}": {
      "get": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -X GET -k -H \"Authorization:Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9292/api/am/store/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/sdks/java > Swagger Petstore_java_1.0.0.zip",
        "x-wso2-request": "GET https://localhost:9292/api/am/store/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/sdks/java\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-disposition : attachment; filename=\"Swagger Petstore_java_1.0.0.zip\"\nContent-type : application/zip",
        "summary": "Generate a SDK for an API\n",
        "description": "This operation can be used to generate SDKs (System Development Kits), for the APIs available in the API Store, for a requested development language.\n",
        "tags": [
          "API (Individual)"
        ]
      }
    },
    "/apis/{apiId}/wsdl": {
      "get": {
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9292/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/wsdl",
        "x-wso2-request": "GET https://127.0.0.1:9292/api/am/publisher/v1.0/apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/wsdl\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\nContent-Length: 329\n\n{\n   \"paths\": {\"/*\": {\"get\":    {\n      \"x-auth-type\": \"Application\",\n      \"x-throttling-policy\": \"Unlimited\",\n      \"responses\": {\"200\": {\"description\": \"OK\"}}\n   }}},\n   \"x-wso2-security\": {\"apim\": {\"x-wso2-scopes\": []}},\n   \"swagger\": \"2.0\",\n   \"info\":    {\n      \"title\": \"PhoneVerification\",\n      \"description\": \"Verify a phone number\",\n   [...]",
        "summary": "Get API WSDL definition",
        "description": "This operation can be used to retrieve the swagger definition of an API.\n",
        "tags": [
          "API (Individual)"
        ]
      }
    },
    "/apis/{apiId}/documents": {
      "get": {
        "summary": "Get a list of API documents",
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "description": "Get a list of documents belonging to an API.\n",
        "tags": [
          "Document (Collection)",
          "API (Individual)",
          "Retrieve"
        ]
      }
    },
    "/apis/{apiId}/documents/{documentId}": {
      "get": {
        "summary": "Get a document of an API",
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "description": "Get a particular document associated with an API.\n",
        "tags": [
          "Document (Individual)",
          "API (Individual)",
          "Retrieve"
        ]
      }
    },
    "/apis/{apiId}/documents/{documentId}/content": {
      "get": {
        "summary": "Get the content of an API document",
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "description": "Downloads a FILE type document/get the inline content or source url of a certain document.\n",
        "tags": [
          "Document (Individual)",
          "API (Individual)",
          "Retrieve"
        ]
      }
    },
    "/apis/{apiId}/ratings": {
      "get": {
        "summary": "Get API ratings",
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "description": "Get the rating of an API.\n",
        "tags": [
          "Rating (Collection)",
          "API (Individual)",
          "Retrieve"
        ]
      }
    },
    "/apis/{apiId}/ratings/{ratingId}": {
      "get": {
        "summary": "Get a single API rating",
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "description": "Get a specific rating of an API.\n",
        "tags": [
          "Rating (Individual)",
          "API (Individual)"
        ]
      }
    },
    "/apis/{apiId}/user-rating": {
      "put": {
        "summary": "Add or update logged in user's rating for an API",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Adds or updates a rating\n",
        "tags": [
          "Rating (Individual)",
          "API (Individual)",
          "Create"
        ]
      }
    },
    "/apis/{apiId}/comments": {
      "get": {
        "summary": "Retrieve API comments",
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "description": "Get a list of Comments that are already added to APIs\n",
        "tags": [
          "Comment (Collection)",
          "Retrieve"
        ]
      },
      "post": {
        "summary": "Add an API comment",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "tags": [
          "Comment (Individual)",
          "API (Individual)",
          "Create"
        ]
      }
    },
    "/apis/{apiId}/comments/{commentId}": {
      "get": {
        "summary": "Get details of an API comment",
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "description": "Get the individual comment given by a username for a certain API.\n",
        "tags": [
          "Comment (Individual)",
          "API (Individual)",
          "Retrieve"
        ]
      },
      "delete": {
        "summary": "Delete an API comment",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Remove a Comment\n",
        "tags": [
          "Comment (Individual)",
          "API (Individual)",
          "Delete"
        ]
      },
      "put": {
        "summary": "Update an API comment",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Update a certain Comment\n",
        "tags": [
          "Comment (Individual)",
          "API (Individual)",
          "Update"
        ]
      }
    },
    "/composite-apis": {
      "get": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9090/api/am/store/v1/composite-apis",
        "x-wso2-request": "GET https://127.0.0.1:9090/api/am/store/v1/composite-apis\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"previous\": \"\",\n   \"list\":    [\n            {\n         \"provider\": \"admin\",\n         \"version\": \"1.0.0\",\n         \"description\": \"This sample API provides Account Status Validation\",\n         \"name\": \"AccountVal\",\n         \"context\": \"/account\",\n         \"id\": \"2e81f147-c8a8-4f68-b4f0-69e0e7510b01\",\n         \"lifeCycleStatus\": \"PUBLISHED\"\n      },\n            {\n     [...]",
        "summary": "Retrieve/Search Composite APIs\n",
        "description": "This operation provides you a list of available Composite APIs qualifying under a given search condition.\n\nEach retrieved Composite API is represented with a minimal amount of attributes. If you want to get complete details of a Composite API, you need to use **Get details of a Composite API** operation.\n",
        "tags": [
          "Composite API (Collection)"
        ]
      },
      "post": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -H \"Content-Type: application/json\" -X POST -d @data.json https://127.0.0.1:9090/api/am/store/v1/composite-apis",
        "x-wso2-request": "POST https://127.0.0.1:9090/api/am/store/v1/composite-apis\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n\n{\r\n   \"name\": \"PizzaShackAPI\",\r\n   \"description\": \"This document describe a RESTFul API for Pizza Shack online pizza delivery store.\\r\\n\",\r\n   \"context\": \"/pizzashack\",\r\n   \"version\": \"1.0.0\",\r\n   \"provider\": \"admin\",\r\n   \"wsdlUri\": null,\r\n   \"lifeCycleStatus\": \"PUBLISHED\",\r\n   \"responseCaching\": \"Disab[...]",
        "x-wso2-response": "HTTP/1.1 201 Created\nLocation: https://127.0.0.1:9090/api/am/publisher/v1/apis/7a2298c4-c905-403f-8fac-38c73301631f\nContent-Type: application/json\n\n{\r\n   \"id\": \"7a2298c4-c905-403f-8fac-38c73301631f\",\r\n   \"name\": \"PizzaShackAPI\",\r\n   \"description\": \"This document describe a RESTFul API for Pizza Shack online pizza delivery store.\\r\\n\",\r\n   \"context\": \"/pizzashack\",\r\n   \"version\": \"1.0.0\",\r\n   \"provider\": \"admin\",\r\n   \"wsdlUr[...]",
        "summary": "Create a new API",
        "description": "This operation can be used to create a new API specifying the details of the API in the payload. The new API will be in `CREATED` state.\n\nThere is a special capability for a user who has `APIM Admin` permission such that he can create APIs on behalf of other users. For that he can to specify `\"provider\" : \"some_other_user\"` in the payload so that the API's creator will be shown as `some_other_user` in the UI.\n",
        "tags": [
          "Composite API (Collection)"
        ]
      }
    },
    "/composite-apis/{apiId}": {
      "get": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9090/api/am/store/v1/composite-apis/7a2298c4-c905-403f-8fac-38c73301631f",
        "x-wso2-request": "GET https://127.0.0.1:9090/api/am/store/v1/composite-apis/7a2298c4-c905-403f-8fac-38c73301631f\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\r\n   \"id\": \"7a2298c4-c905-403f-8fac-38c73301631f\",\r\n   \"name\": \"PizzaShackAPI\",\r\n   \"description\": \"This document describe a RESTFul API for Pizza Shack online pizza delivery store.\\r\\n\",\r\n   \"context\": \"/pizzashack\",\r\n   \"version\": \"1.0.0\",\r\n   \"provider\": \"admin\",\r\n   \"endpointId\": \"{\\\"paths\\\":{\\\"/order\\\":{\\\"post\\\":{\\\"x-auth-type\\\":\\\"Application & Applica[...]",
        "summary": "Get details of a Composite API",
        "description": "Using this operation, you can retrieve complete details of a single Composite API. You need to provide the Id of the Composite API to retrive it.\n",
        "tags": [
          "Composite API (Individual)"
        ]
      },
      "put": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -H \"Content-Type: application/json\" -X PUT -d @data.json https://127.0.0.1:9090/api/am/store/v1/composite-apis/7a2298c4-c905-403f-8fac-38c73301631f",
        "x-wso2-request": "PUT https://127.0.0.1:9090/api/am/store/v1/composite-apis/7a2298c4-c905-403f-8fac-38c73301631f\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\nContent-Type: application/json\n\n{\r\n   \"id\": \"7a2298c4-c905-403f-8fac-38c73301631f\",\r\n   \"name\": \"PizzaShackAPI\",\r\n   \"description\": \"This document describe a RESTFul API for Pizza Shack online pizza delivery store.\\r\\n\",\r\n   \"context\": \"/pizzashack\",\r\n   \"version\": \"1.0.0\",\r\n   \"[...]",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\r\n   \"id\": \"7a2298c4-c905-403f-8fac-38c73301631f\",\r\n   \"name\": \"PizzaShackAPI\",\r\n   \"description\": \"This document describe a RESTFul API for Pizza Shack online pizza delivery store.\\r\\n\",\r\n   \"context\": \"/pizzashack\",\r\n   \"version\": \"1.0.0\",\r\n   \"provider\": \"admin\",\r\n   \"endpointId\": \"{\\\"paths\\\":{\\\"/order\\\":{\\\"post\\\":{\\\"x-auth-type\\\":\\\"Application & Applica[...]",
        "summary": "Update a Composite API",
        "description": "This operation can be used to update an existing Composite API.\nBut the properties `name`, `version`, `context`, `provider`, `state` will not be changed by this operation.\n",
        "tags": [
          "Composite API (Individual)"
        ]
      },
      "delete": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X DELETE https://127.0.0.1:9090/api/am/store/v1/composite-apis/6fb74674-4ab8-4b52-9886-f9a376985060",
        "x-wso2-request": "DELETE https://127.0.0.1:9090/api/am/store/v1/composite-apis/6fb74674-4ab8-4b52-9886-f9a376985060\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK",
        "summary": "Delete a Composite API",
        "description": "This operation can be used to delete an existing Composite API proving the Id of the Composite API.\n",
        "tags": [
          "Composite API (Individual)"
        ]
      }
    },
    "/composite-apis/{apiId}/dedicated-gateway": {
      "get": {
        "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9090/api/am/store/v1/composite-apis/am/publisher/v1.0/apis/96077508-fd01-4fae-bc64-5de0e2baf43c/dedicated-gateway",
        "x-wso2-request": "GET https://127.0.0.1:9292/api/am/store/v1/composite-apis/96077508-fd01-4fae-bc64-5de0e2baf43c/dedicated-gateway\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n\"isEnabled\":true\n}",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "summary": "Get details of dedicated-gateway",
        "description": "This operation can be used to retrieve whether the dedicated gateway is enabled in a certain Composite API.\n",
        "tags": [
          "DedicatedGateway (Individual)"
        ]
      },
      "put": {
        "x-wso2-curl": "curl -k -H \"Authorization:Bearer b0982cd2aacd463ff5f63cd5ebe58f4a\" -H \"Content-Type: application/json\" -X PUT -d data.json \"https://127.0.0.1:9443/api/am/publisher/v1.0/apis/96077508-fd01-4fae-bc64-5de0e2baf43c/dedicated-gateway",
        "x-wso2-request": "PUT https://127.0.0.1:9292/api/am/store/v1/composite-apis/96077508-fd01-4fae-bc64-5de0e2baf43c/dedicated-gateway\nAuthorization:Bearer b0982cd2aacd463ff5f63cd5ebe58f4a\nContent-Type: application/json\n\n{\n   \"isEnabled\": \"true\"\n}",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"enabled\": \"true\"\n}",
        "security": [
          {
            "OAuth2Security": [
              "apim:dedicated_gateway"
            ]
          }
        ],
        "x-scope": "apim:dedicated_gateway",
        "summary": "Update enabling of dedicated Gateway of Composite API",
        "description": "This operation can be used to update metadata of an API's dedicated-gateway.\n",
        "tags": [
          "dedicated-gateway (Individual)"
        ]
      }
    },
    "/composite-apis/{apiId}/swagger": {
      "get": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9090/api/am/store/v1/composite-apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/swagger",
        "x-wso2-request": "GET https://127.0.0.1:9090/api/am/store/v1/composite-apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/swagger\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\nContent-Length: 329\n\n{\n   \"paths\": {\"/*\": {\"get\":    {\n      \"x-auth-type\": \"Application\",\n      \"x-throttling-policy\": \"Unlimited\",\n      \"responses\": {\"200\": {\"description\": \"OK\"}}\n   }}},\n   \"x-wso2-security\": {\"apim\": {\"x-wso2-scopes\": []}},\n   \"swagger\": \"2.0\",\n   \"info\":    {\n      \"title\": \"PhoneVerification\",\n      \"description\": \"Verify a phone number\",\n   [...]",
        "summary": "Get swagger definition",
        "description": "This operation can be used to retrieve the swagger definition of a Composite API.\n",
        "tags": [
          "Composite API (Individual)"
        ]
      },
      "put": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -k -H \"Authorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\" -F endpointId=\"{\\\"paths\\\":{\\\"\\/*\\\":{\\\"get\\\":{\\\"x-auth-type\\\":\\\"Application\\\",\\\"x-throttling-policy\\\":\\\"Unlimited\\\",\\\"responses\\\":{\\\"200\\\":{\\\"description\\\":\\\"OK\\\"}}}}},\\\"x-wso2-security\\\":{\\\"apim\\\":{\\\"x-wso2-scopes\\\":[]}},\\\"swagger\\\":\\\"2.0\\\",\\\"info\\\":{\\\"title\\\":\\\"PhoneVerification\\\",\\\"description\\\":\\\"Verify a phone num[...]",
        "x-wso2-request": "PUT https://127.0.0.1:9090/api/am/store/v1/composite-apis/8848faaa-7fd1-478a-baa2-48a4ebb92c98/swagger\nAuthorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\nContent-Length: 477\nContent-Type: multipart/form-data; boundary=------------------------4f51e636c0003d99\n\n--------------------------4f51e636c0003d99\nContent-Disposition: form-data; name=\"apiDefinition\"\n\n{\"paths\":{\"\\/*\":{\"get\":{\"x-auth-type\":\"Application\",\"x-throttling-policy\":\"Unlimited\[...]",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"paths\": {\"/*\": {\"get\":    {\n      \"x-auth-type\": \"Application\",\n      \"x-throttling-policy\": \"Unlimited\",\n      \"responses\": {\"200\": {\"description\": \"OK\"}}\n   }}},\n   \"x-wso2-security\": {\"apim\": {\"x-wso2-scopes\": []}},\n   \"swagger\": \"2.0\",\n   \"info\":    {\n      \"title\": \"PhoneVerification\",\n      \"description\": \"Verify a phone number\",\n      \"contact\":      [...]",
        "summary": "Update swagger definition",
        "description": "This operation can be used to update the swagger definition of an existing Composite API. Swagger definition to be updated is passed as a form data parameter `apiDefinition`.\n",
        "tags": [
          "Composite API (Individual)"
        ]
      }
    },
    "/composite-apis/{apiId}/implementation": {
      "get": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://127.0.0.1:9090/api/am/store/v1/composite-apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/implementation",
        "x-wso2-request": "GET https://127.0.0.1:9090/api/am/store/v1/composite-apis/890a4f4d-09eb-4877-a323-57f6ce2ed79b/implementation\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\nContent-Length: 329\n\n{\n   \"paths\": {\"/*\": {\"get\":    {\n      \"x-auth-type\": \"Application\",\n      \"x-throttling-policy\": \"Unlimited\",\n      \"responses\": {\"200\": {\"description\": \"OK\"}}\n   }}},\n   \"x-wso2-security\": {\"apim\": {\"x-wso2-scopes\": []}},\n   \"swagger\": \"2.0\",\n   \"info\":    {\n      \"title\": \"PhoneVerification\",\n      \"description\": \"Verify a phone number\",\n   [...]",
        "summary": "Get Composite API implementation",
        "description": "This operation can be used to retrieve the Ballerina implementation of a Composite API.\n",
        "tags": [
          "Composite API (Individual)"
        ]
      },
      "put": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -k -H \"Authorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\" -F endpointId=\"{\\\"paths\\\":{\\\"\\/*\\\":{\\\"get\\\":{\\\"x-auth-type\\\":\\\"Application\\\",\\\"x-throttling-policy\\\":\\\"Unlimited\\\",\\\"responses\\\":{\\\"200\\\":{\\\"description\\\":\\\"OK\\\"}}}}},\\\"x-wso2-security\\\":{\\\"apim\\\":{\\\"x-wso2-scopes\\\":[]}},\\\"swagger\\\":\\\"2.0\\\",\\\"info\\\":{\\\"title\\\":\\\"PhoneVerification\\\",\\\"description\\\":\\\"Verify a phone num[...]",
        "x-wso2-request": "PUT https://127.0.0.1:9090/api/am/store/v1/composite-apis/8848faaa-7fd1-478a-baa2-48a4ebb92c98/implementation\nAuthorization:Bearer 5311eca3-8ac8-354e-ab36-7e2fdd6a4013\nContent-Length: 477\nContent-Type: multipart/form-data; boundary=------------------------4f51e636c0003d99\n\n--------------------------4f51e636c0003d99\nContent-Disposition: form-data; name=\"apiImplementation\"\n\n{\"paths\":{\"\\/*\":{\"get\":{\"x-auth-type\":\"Application\",\"x-throttling-policy\":\[...]",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"paths\": {\"/*\": {\"get\":    {\n      \"x-auth-type\": \"Application\",\n      \"x-throttling-policy\": \"Unlimited\",\n      \"responses\": {\"200\": {\"description\": \"OK\"}}\n   }}},\n   \"x-wso2-security\": {\"apim\": {\"x-wso2-scopes\": []}},\n   \"swagger\": \"2.0\",\n   \"info\":    {\n      \"title\": \"PhoneVerification\",\n      \"description\": \"Verify a phone number\",\n      \"contact\":      [...]",
        "summary": "Update Composite API implementation",
        "description": "This operation can be used to update the Ballerina implementation of a Composite API. Ballerina implementation to be updated is passed as a form data parameter `apiImplementation`.\n",
        "tags": [
          "Composite API (Individual)"
        ]
      }
    },
    "/applications": {
      "get": {
        "summary": "Get all applications",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Get a list of applications\n",
        "tags": [
          "Application (Collection)"
        ]
      },
      "post": {
        "summary": "Create a new application",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Create a new application.\n",
        "tags": [
          "Application (Individual)",
          "Create"
        ]
      }
    },
    "/applications/{applicationId}": {
      "get": {
        "summary": "Get details of an application",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Get application details\n",
        "tags": [
          "Application (Individual)",
          "Retrieve"
        ]
      },
      "put": {
        "summary": "Update an application",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Update application details\n",
        "tags": [
          "Application (Individual)",
          "Update"
        ]
      },
      "delete": {
        "summary": "Delete an application",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Delete an application\n",
        "tags": [
          "Application (Individual)",
          "Delete"
        ]
      }
    },
    "/applications/{applicationId}/generate-keys": {
      "post": {
        "summary": "Generate application keys",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Generate keys (Consumer key/secret) for application\n",
        "tags": [
          "Application Key (Individual)",
          "Application (Individual)"
        ]
      }
    },
    "/applications/{applicationId}/map-keys": {
      "post": {
        "summary": "Map application keys",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Map keys (Consumer key/secret) to an application\n",
        "tags": [
          "Application Key (Individual)",
          "Application (Individual)"
        ]
      }
    },
    "/applications/{applicationId}/keys": {
      "get": {
        "summary": "Retrieve all application keys",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Retrieve keys (Consumer key/secret) of application\n",
        "tags": [
          "Application Key (Collection)",
          "Application (Individual)"
        ]
      }
    },
    "/applications/{applicationId}/keys/{keyType}": {
      "get": {
        "summary": "Retrieve application keys for a provided type",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Retrieve keys (Consumer key/secret) of application by a given type\n",
        "tags": [
          "Application Key (Collection)",
          "Application (Individual)"
        ]
      },
      "put": {
        "summary": "Update an application key",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Update grant types and callback url (Consumer Key and Consumer Secret are ignored)\n",
        "tags": [
          "Application Key (Individual)",
          "Application (Individual)"
        ]
      }
    },
    "/applications/{applicationId}/generate-token": {
      "post": {
        "summary": "Generate application token",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Generate an access token for application by client_credentials grant type\n",
        "tags": [
          "Application Token (Individual)",
          "Application (Individual)"
        ]
      }
    },
    "/export/applications": {
      "get": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9292/api/am/store/v1.0/export/applications?appId=xxx > exported-application.zip",
        "x-wso2-request": "GET https://127.0.0.1:9292/api/am/store/v1.0/export/applications?appId=xxx\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK\n Connection: keep-alive\n  Content-Disposition: attachment; filename=\"exported-applications.zip\"\n  Content-Type: application/zip",
        "summary": "Export details related to an Application.",
        "description": "This operation can be used to export details related to a perticular application.\n",
        "tags": [
          "Application (Individual)"
        ]
      }
    },
    "/import/applications": {
      "put": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-wso2-curl": "curl -k -F \"file=@exported.zip\" -X PUT -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9292/api/am/store/v1.0/import/applications",
        "x-wso2-request": "PUT https://127.0.0.1:9292/api/am/store/v1.0/import/applications\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type:application/json\n\n{\"applicationUUID\":\"645b8e32-3643-48e5-ab42-aed853a8cd77\",\"workflowResponse\":{\"workflowStatus\":\"APPROVED\"}}",
        "summary": "Imports an Updates an Application.",
        "description": "This operation can be used to import an existing Application.\n",
        "tags": [
          "Application (Individual)"
        ]
      },
      "post": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-wso2-curl": "curl -k -F \"file=@exported.zip\" -X POST -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9292/api/am/store/v1.0/import/applications",
        "x-wso2-request": "POST https://127.0.0.1:9292/api/am/store/v1.0/import/applications\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\"name\":\"sampleApp2\",\"uuid\":\"5e3ac21a-cc14-4404-95f1-659900c165c4\",\"description\":\"sample app 2\",\"policy\":{\"uuid\":\"5b74ec82-264e-4104-91ef-fdd41b981798\",\"policyName\":\"50PerMin\",\"isDeployed\":false},\"status\":\"APPROVED\",\"createdUser\":\"admin\",\"createdTime\":{\"date\":{\"year\":2017,\"month\":11,\"day\":8},\"time\":{\"hour\":4,\"minute\":10,\"second\":4,\"nano\":434000000}}}",
        "summary": "Imports an Application.",
        "description": "This operation can be used to import an existing Application.\n",
        "tags": [
          "Application (Individual)"
        ]
      }
    },
    "/subscriptions": {
      "get": {
        "summary": "Get all subscriptions",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Get subscription list.\nThe API Identifier or Application Identifier\nthe subscriptions of which are to be returned are passed as parameters.\n",
        "tags": [
          "Subscription (Collection)",
          "Retrieve"
        ]
      },
      "post": {
        "summary": "Add a new subscription",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Add a new subscription\n",
        "tags": [
          "Subscription (Individual)",
          "Create"
        ]
      }
    },
    "/subscriptions/{subscriptionId}": {
      "get": {
        "summary": "Get details of a subscription",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Get subscription details\n",
        "tags": [
          "Subscription (Individual)",
          "Retrieve"
        ]
      },
      "delete": {
        "summary": "Remove a subscription",
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "description": "Remove subscription\n",
        "tags": [
          "Subscription (Individual)",
          "Delete"
        ]
      }
    },
    "/policies/{tierLevel}": {
      "get": {
        "summary": "Get all available policies",
        "security": [
          {
            "OAuth2Security": null
          }
        ],
        "description": "Get available policies\n",
        "tags": [
          "Tier (Collection)",
          "Retrieve"
        ]
      }
    },
    "/policies/{tierLevel}/{tierName}": {
      "get": {
        "summary": "Get a single policy details",
        "description": "Get policy details\n",
        "tags": [
          "Tier (Individual)",
          "Retrieve"
        ]
      }
    },
    "/tags": {
      "get": {
        "summary": "Get all tags",
        "description": "Get a list of tags that are already added to APIs\n",
        "tags": [
          "Tag (Collection)",
          "Retrieve"
        ]
      }
    },
    "/labels": {
      "get": {
        "summary": "Get label information based on the label name",
        "description": "This operation can be used to retrieve the information of the labels\n",
        "tags": [
          "Label (Collection)"
        ]
      }
    },
    "/self-signup": {
      "post": {
        "summary": "Register a new user",
        "security": [
          {
            "OAuth2Security": [
              "apim:self-signup"
            ]
          }
        ],
        "x-scope": "apim:self-signup",
        "description": "User self signup API\n",
        "tags": [
          "Sign Up"
        ]
      }
    },
    "/sdk-gen/languages": {
      "get": {
        "security": [
          {
            "OAuth2Security": [
              "apim:subscribe"
            ]
          }
        ],
        "x-scope": "apim:subscribe",
        "x-wso2-curl": "curl -X GET -k -H \"Authorization:Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9292/api/am/store/v1.0/sdk-gen/languages",
        "x-wso2-request": "GET https://localhost:9292/api/am/store/v1.0/sdk-gen/languages\nAuthorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\n",
        "x-wso2-response": "HTTP/1.1 200 OK\nContent-Type : application/json",
        "summary": "Get a list of supported SDK languages\n",
        "description": "This operation will provide a list of programming languages that are supported by the swagger codegen library for generating System Development Kits (SDKs) for APIs available in the API Manager Store\n",
        "tags": [
          "SDK Languages"
        ]
      }
    },
    "/settings": {
      "get": {
        "summary": "Retreive store settings",
        "security": [
          {
            "OAuth2Security": [
              "apim:store_setting"
            ]
          }
        ],
        "x-scope": "apim:store_setting",
        "description": "Retreive store settings\n"
      }
    }
  }
}