#   Copyright (c) 2022, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
################################################################################
openapi: 3.0.1
info:
  title: WSO2 API Manager - BackOffice REST API
  description: This document specifies a **RESTful API** for WSO2 **APK** - **BackOffice**.
  contact:
    name: WSO2
    url: https://wso2.com/api-manager/
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
servers:
  - url: https://apis.wso2.com/api/am/backoffice/v1

paths:
  ######################################################
  # The "API Collection" resource APIs
  ######################################################
  /apis:
    get:
      tags:
        - APIs
      summary: |
        Retrieve/Search APIs
      description: |
        This operation provides you a list of available APIs qualifying under a given search condition.

        Each retrieved API is represented with a minimal amount of attributes. If you want to get complete details of an API, you need to use **Get details of an API** operation.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:api_list_view
      operationId: getAllAPIs

  ######################################################
  # The "Individual API" resource APIs
  ######################################################
  /apis/{apiId}:
    get:
      tags:
        - APIs
      summary: Get Details of an API
      description: |
        Using this operation, you can retrieve complete details of a single API. You need to provide the Id of the API to retrive it.
      security:
        - OAuth2Security:
            - apim:api_view
      operationId: getAPI
    put:
      tags:
        - APIs
      summary: Update an API
      description: |
        This operation can be used to update an existing API.
        But the properties `name`, `provider` and `version` cannot be changed.
      security:
        - OAuth2Security:
            - apim:api_publish
            - apim:api_manage
      operationId: updateAPI

  /apis/{apiId}/definition:
    get:
      tags:
        - APIs
      summary: Get the API Definition
      description: |
        This operation can be used to retrieve the definition of an API.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:api_definition_view
      operationId: getAPIDefinition

  /apis/{apiId}/resource-paths:
    get:
      tags:
        - APIs
      summary: Get Resource Paths of an API
      description: |
        This operation can be used to retrieve resource paths defined for a specific API.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:api_manage
      operationId: getAPIResourcePaths

  /apis/{apiId}/thumbnail:
    get:
      tags:
        - APIs
      summary: Get Thumbnail Image
      description: |
        This operation can be used to download a thumbnail image of an API.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:api_publish
            - apim:api_manage
      operationId: getAPIThumbnail

    put:
      tags:
        - APIs
      summary: Upload a Thumbnail Image
      description: |
        This operation can be used to upload a thumbnail image of an API. The thumbnail to be uploaded should be given as a form data parameter `file`.
      security:
        - OAuth2Security:
            - apim:api_publish
            - apim:api_manage
      operationId: updateAPIThumbnail

  /apis/{apiId}/documents:
    get:
      tags:
        - API Documents
      summary: Get a List of Documents of an API
      description: |
        This operation can be used to retrive a list of documents belonging to an API by providing the ID of the API.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:document_manage
      operationId: getAPIDocuments

    post:
      tags:
        - API Documents
      summary: Add a New Document to an API
      description: |
        This operation can be used to add a new documentation to an API. This operation only adds the metadata of a document. To add the actual content we need to use **Upload the content of an API document ** API once we obtain a document Id by this operation.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:document_manage
      operationId: addAPIDocument

  /apis/{apiId}/documents/{documentId}:
    get:
      tags:
        - API Documents
      summary: Get a Document of an API
      description: |
        This operation can be used to retrieve a particular document's metadata associated with an API.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:document_manage
      operationId: getAPIDocument

    put:
      tags:
        - API Documents
      summary: Update a Document of an API
      description: |
        This operation can be used to update metadata of an API's document.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:document_manage
      operationId: updateAPIDocument

    delete:
      tags:
        - API Documents
      summary: Delete a Document of an API
      description: |
        This operation can be used to delete a document associated with an API.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:document_manage
      operationId: deleteAPIDocument

  /apis/{apiId}/documents/{documentId}/content:
    get:
      tags:
        - API Documents
      summary: Get the Content of an API Document
      description: |
        This operation can be used to retrive the content of an API's document.

        The document can be of 3 types. In each cases responses are different.

        1. **Inline type**:
           The content of the document will be retrieved in `text/plain` content type

           _Sample cURL_ : `curl -k -H "Authorization:Bearer 579f0af4-37be-35c7-81a4-f1f1e9ee7c51" -F inlineContent=@"docs.txt" -X POST "https://localhost:9443/api/apk/backoffice/v1/apis/995a4972-3178-4b17-a374-756e0e19127c/documents/43c2bcce-60e7-405f-bc36-e39c0c5e189e/content`
        2. **FILE type**:
           The file will be downloaded with the related content type (eg. `application/pdf`)
        3. **URL type**:
            The client will recieve the URL of the document as the Location header with the response with - `303 See Other`
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:document_manage
      operationId: getAPIDocumentContent

    post:
      tags:
        - API Documents
      summary: Upload the Content of an API Document
      description: |
        Thid operation can be used to upload a file or add inline content to an API document.

        **IMPORTANT:**
        * Either **file** or **inlineContent** form data parameters should be specified at one time.
        * Document's source type should be **FILE** in order to upload a file to the document using **file** parameter.
        * Document's source type should be **INLINE** in order to add inline content to the document using **inlineContent** parameter.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:document_manage
      operationId: addAPIDocumentContent

  /apis/{apiId}/comments:
    get:
      tags:
        - Comments
      summary: Retrieve API Comments
      description: |
        Get a list of Comments that are already added to APIs
      operationId: getAllCommentsOfAPI
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:comment_view
            - apim:comment_manage
    post:
      tags:
        - Comments
      summary: Add an API Comment
      operationId: addCommentToAPI
      security:
        - OAuth2Security:
            - apim:comment_write
            - apim:comment_manage
  /apis/{apiId}/comments/{commentId}:
    get:
      tags:
        - Comments
      summary: Get Details of an API Comment
      description: |
        Get the individual comment given by a username for a certain API.
      operationId: getCommentOfAPI
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:comment_view
            - apim:comment_manage
    patch:
      tags:
        - Comments
      summary: Edit a comment
      description: |
        Edit the individual comment
      operationId: editCommentOfAPI
      security:
        - OAuth2Security:
            - apim:comment_write
            - apim:comment_manage
    delete:
      tags:
        - Comments
      summary: Delete an API Comment
      description: |
        Remove a Comment
      operationId: deleteComment
      security:
        - OAuth2Security:
            - apim:comment_write
            - apim:comment_manage
            - apim:admin # special scope added to moderate other comments as well
  /apis/{apiId}/comments/{commentId}/replies:
    get:
      tags:
        - Comments
      summary: Get replies of a comment
      description: |
        Get replies of a comment
      operationId: getRepliesOfComment
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:comment_view
            - apim:comment_manage
  /apis/{apiId}/monetize:
    post:
      tags:
        - API Monetization
      summary: Configure Monetization for a Given API
      description: |
        This operation can be used to configure monetization for a given API.
      security:
        - OAuth2Security:
            - apim:api_publish
            - apim:api_manage
      operationId: addAPIMonetization

  /apis/{apiId}/monetization:
    get:
      tags:
        - API Monetization
      summary: Get Monetization Status for each Tier in a Given API
      description: |
        This operation can be used to get monetization status for each tier in a given API
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:api_publish
            - apim:api_manage
      operationId: getAPIMonetization

  /apis/{apiId}/revenue:
    get:
      tags:
        - API Monetization
      summary: Get Total Revenue Details of a Given Monetized API with Meterd Billing
      description: |
        This operation can be used to get details of total revenue details of a given monetized API with meterd billing.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:api_publish
            - apim:api_manage
      operationId: getAPIRevenue

  /apis/{apiId}/external-stores:
    get:
      tags:
        - External Stores
      summary: Get the List of External Stores to which an API is Published
      description: |
        This operation can be used to retrieve a list of external stores which an API is published to by providing the ID of the API.
      operationId: getAllPublishedExternalStoresByAPI
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:api_manage
  /apis/{apiId}/publish-to-external-stores:
    post:
      tags:
        - External Stores
      summary: Publish an API to External Stores
      description: |
        This operation can be used to publish an API to a list of external stores.
      operationId: publishAPIToExternalStores
      security:
        - OAuth2Security:
            - apim:api_publish
            - apim:api_manage
  ######################################################
  # The "Subscription Collection" resource APIs
  ######################################################
  /subscriptions:
    get:
      tags:
        - Subscriptions
      summary: Get all Subscriptions
      description: |
        This operation can be used to retrieve a list of subscriptions of the user associated with the provided access token. This operation is capable of

        1. Retrieving all subscriptions for the user's APIs.
        `GET https://127.0.0.1:9443/api/apk/backoffice/v1/subscriptions`

        2. Retrieving subscriptions for a specific API.
        `GET https://127.0.0.1:9443/api/apk/backoffice/v1/subscriptions?apiId=c43a325c-260b-4302-81cb-768eafaa3aed`
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:subscription_view
            - apim:subscription_manage
      operationId: getSubscriptions

  ######################################################
  # The Individual Subscription resource APIs
  ######################################################
  /subscriptions/{subscriptionId}/usage:
    get:
      tags:
        - API Monetization
      summary: Get Details of a Pending Invoice for a Monetized Subscription with Metered Billing.
      description: |
        This operation can be used to get details of a pending invoice for a monetized subscription with meterd billing.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:subscription_view
            - apim:subscription_manage
      operationId: getSubscriptionUsage

  /subscriptions/{subscriptionId}/subscriber-info:
    get:
      tags:
        - Subscriber
      summary: Get Details of a Subscriber
      description: |
        This operation can be used to get details of a user who subscribed to the API.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:subscription_view
            - apim:subscription_manage
      operationId: getSubscriberInfoBySubscriptionId

  /subscriptions/block-subscription:
    post:
      tags:
        - Subscriptions
      summary: Block a Subscription
      description: |
        This operation can be used to block a subscription. Along with the request, `blockState` must be specified as a query parameter.

        1. `BLOCKED` : Subscription is completely blocked for both Production and Sandbox environments.
        2. `PROD_ONLY_BLOCKED` : Subscription is blocked for Production environment only.
      security:
        - OAuth2Security:
            - apim:subscription_block
            - apim:subscription_manage
      operationId: blockSubscription

  /subscriptions/unblock-subscription:
    post:
      tags:
        - Subscriptions
      summary: Unblock a Subscription
      description: |
        This operation can be used to unblock a subscription specifying the subscription Id. The subscription will be fully unblocked after performing this operation.
      security:
        - OAuth2Security:
            - apim:subscription_block
            - apim:subscription_manage
      operationId: unBlockSubscription


  ######################################################
  # The "Thorttling Tier Collection" resource APIs
  ######################################################
  /usage-plans:
    get:
      tags:
        - Usage Plan
      summary: Get All Useage Plans
      description: |
        This operation can be used to list the available usage plans.
      operationId: getAllUsagePlans
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:tier_view
  ######################################################
  # The "Content Search Results" resource APIs
  ######################################################
  /search:
    get:
      tags:
        - Unified Search
      summary: |
        Retrieve/Search APIs and API Documents by Content
      description: |
        This operation provides you a list of available APIs and API Documents qualifying the given keyword match.
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:api_manage
      operationId: search

  ######################################################
  # The "ExternalStore Collection" resource APIs
  ######################################################
  /external-stores:
    get:
      tags:
        - External Stores
      summary: Retrieve External Stores List to Publish an API
      description: |
        Retrieve external stores list configured to publish an API
      operationId: getAllExternalStores
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:api_manage
  ######################################################
  # The BackOffice settings resource APIs
  ######################################################
  /settings:
    get:
      tags:
        - Settings
      summary: Retreive BackOffice Settings
      description: |
        Retreive BackOffice settings
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:backoffice_settings
      operationId: getSettings

  ######################################################
  # The "API Category Collection" resource API
  ######################################################
  /api-categories:
    get:
      tags:
        - API Category (Collection)
      summary: Get all API categories
      description: |
        Get all API categories
      security:
        - OAuth2Security:
            - apim:api_view
            - apim:api_manage
      operationId: getAllAPICategories

  /apis/change-lifecycle:
    post:
      tags:
        - API Lifecycle
      summary: Change API LC Status
      description: |
        This operation is used to change the lifecycle of an API.
        Eg: Publish an API which is in `CREATED` state. In order to change the lifecycle, we need to provide the
        lifecycle `action` as a query parameter.

        For example, to Publish an API, `action` should be `Publish`.

      security:
        - OAuth2Security:
            - apim:api_publish
            - apim:api_manage
      operationId: changeAPILifecycle

  /apis/{apiId}/lifecycle-history:
    get:
      tags:
        - API Lifecycle
      summary: Get Lifecycle State Change History of the APIs.
      description: |
        This operation can be used to retrieve Lifecycle state change history of the APIs.
      security:
        - OAuth2Security:
            - apim:api_publish
            - apim:api_manage
      operationId: getAPILifecycleHistory

  /apis/{apiId}/lifecycle-state:
    get:
      tags:
        - API Lifecycle
      summary: Get Lifecycle State Data of the API.
      description: |
        This operation can be used to retrieve Lifecycle state data of the API.
      security:
        - OAuth2Security:
            - apim:api_publish
            - apim:api_create
            - apim:api_manage
      operationId: getAPILifecycleState

  /apis/{apiId}/lifecycle-state/pending-tasks:
    delete:
      tags:
        - API Lifecycle
      summary: Delete Pending Lifecycle State Change Tasks
      description: |
        This operation can be used to remove pending lifecycle state change requests that are in pending state
      security:
        - OAuth2Security:
            - apim:api_publish
            - apim:api_manage
      operationId: deleteAPILifecycleStatePendingTasks

components:
  securitySchemes:
    OAuth2Security:
      type: oauth2
      flows:
        password:
          tokenUrl: https://localhost:9443/oauth2/token
          scopes:
            openid: Authorize access to user details
            apim:api_view: View API
            apim:api_create: Create API
            apim:api_delete: Delete API
            apim:api_publish: Publish API
            apim:api_manage: Manage all API related operations
            apim:subscription_view: View Subscription
            apim:subscription_block: Block Subscription
            apim:subscription_manage: Manage all Subscription related operations
            apim:document_manage: Create, update and delete API documents
            apim:backoffice_settings: Retrieve BackOffice settings
            apim:app_import_export: Import and export applications related operations
            apim:admin: Manage all admin operations
            apim:comment_view: Read permission to comments
            apim:comment_write: Write permission to comments
            apim:comment_manage: Read and Write comments
            apim:tier_view: View Usage plans
            apim:api_list_view: View, Retrieve API list
            apim:api_definition_view: View, Retrieve API definition
