/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.apimgt.gateway.utils;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.junit.Assert;
import org.junit.Test;
import org.wso2.carbon.apimgt.api.model.subscription.URLMapping;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Unit tests for {@link MCPPayloadGenerator#generateToolListPayload(Object, List, boolean)} — the gateway
 * builder for the {@code tools/list} response. Pins the metadata-preservation fix: a stored tool definition
 * may be a bare input schema OR a wrapper additionally carrying {@code title}, {@code annotations},
 * {@code _meta}, {@code outputSchema} and {@code execution}; the builder must emit ALL of those fields, while
 * still sanitizing the input schema for non third-party (OpenAPI/API-generated) servers.
 */
public class MCPPayloadGeneratorTest {

    private static final Gson GSON = new Gson();

    private JsonArray toolsOf(String payload) {
        JsonObject root = GSON.fromJson(payload, JsonObject.class);
        Assert.assertTrue("payload must carry a result object", root.has("result"));
        JsonObject result = root.getAsJsonObject("result");
        Assert.assertTrue("result must carry a tools array", result.has("tools"));
        return result.getAsJsonArray("tools");
    }

    private URLMapping tool(String name, String description, String schemaDefinition) {
        URLMapping mapping = new URLMapping();
        mapping.setUrlPattern(name);
        mapping.setDescription(description);
        mapping.setSchemaDefinition(schemaDefinition);
        return mapping;
    }

     private static final String TOOL_NAME = "get_surrender_value";

     /**
     * Schema as published by a third-party MCP server proxied through the gateway — arbitrary
     * snake_case names, no WSO2 location prefixes. Taken from issue #19337.
     */
    private static final String PROXY_SCHEMA =
            "{\"inputSchema\":{\"type\":\"object\","
                    + "\"required\":[\"agreement_number\",\"source_id\",\"opendate\"],"
                    + "\"properties\":{"
                    + "\"agreement_number\":{\"description\":\"Original description\",\"type\":\"string\"},"
                    + "\"source_id\":{\"description\":\"source description\",\"type\":\"string\"},"
                    + "\"opendate\":{\"format\":\"date\",\"description\":\"Date of the open\","
                    + "\"type\":\"string\"}}}}";

    /**
     * Schema as generated by WSO2 from an OpenAPI definition. Keys are composed as
     * {@code <parameter location>_<parameter name>}, covering every location the OAS2 and OAS3
     * parsers can emit.
     */
    private static final String API_DERIVED_SCHEMA =
            "{\"inputSchema\":{\"type\":\"object\","
                    + "\"required\":[\"path_itemId\",\"query_city\"],"
                    + "\"properties\":{"
                    + "\"query_city\":{\"type\":\"string\"},"
                    + "\"header_X-Trace\":{\"type\":\"string\"},"
                    + "\"path_itemId\":{\"type\":\"string\"},"
                    + "\"cookie_sessionId\":{\"type\":\"string\"},"
                    + "\"formData_file\":{\"type\":\"string\"}}}}";

    // ------------------------------------------------------------------ helpers

    private static URLMapping toolMapping(String schemaDefinition) {
        URLMapping mapping = new URLMapping();
        mapping.setUrlPattern(TOOL_NAME);
        mapping.setDescription("Determine the surrender value of an agreement");
        mapping.setSchemaDefinition(schemaDefinition);
        return mapping;
    }

    private static JsonObject firstTool(String payload) {
        JsonObject root = JsonParser.parseString(payload).getAsJsonObject();
        JsonArray tools = root.getAsJsonObject("result").getAsJsonArray("tools");
        Assert.assertEquals("Expected exactly one tool in the response", 1, tools.size());
        return tools.get(0).getAsJsonObject();
    }

    private static JsonObject inputSchemaOf(String payload) {
        return firstTool(payload).getAsJsonObject("inputSchema");
    }

    private static Set<String> propertyKeys(JsonObject inputSchema) {
        return new HashSet<>(inputSchema.getAsJsonObject("properties").keySet());
    }

    private static List<String> requiredOf(JsonObject inputSchema) {
        JsonArray required = inputSchema.getAsJsonArray("required");
        return required == null ? Collections.emptyList()
                : required.asList().stream().map(e -> e.getAsString()).collect(Collectors.toList());
    }

    private static String generate(String schemaDefinition, boolean isThirdParty) {
        return MCPPayloadGenerator.generateToolListPayload(
                1, Collections.singletonList(toolMapping(schemaDefinition)), isThirdParty);
    }

    /**
     * Regression core — a proxied (third-party) tool whose stored definition wraps the input schema together
     * with annotations, _meta and outputSchema must have EVERY one of those fields emitted in tools/list, and
     * the input schema passed through UNCHANGED (proxy schemas are not sanitized). Before the fix only
     * name/description/inputSchema were emitted.
     */
    @Test
    public void testProxyToolPreservesMetadataInToolsList() {

        String schema = "{"
                + "\"inputSchema\":{\"type\":\"object\",\"properties\":{\"query_city\":{\"type\":\"string\"}},"
                + "  \"required\":[\"query_city\"]},"
                + "\"title\":\"Weather Lookup\","
                + "\"annotations\":{\"readOnlyHint\":true,\"title\":\"Weather\"},"
                + "\"_meta\":{\"vendor\":\"wso2\"},"
                + "\"outputSchema\":{\"type\":\"object\",\"properties\":{\"temp\":{\"type\":\"number\"}},"
                + "  \"required\":[\"temp\"]},"
                + "\"execution\":{\"mode\":\"async\",\"timeout\":30}"
                + "}";
        List<URLMapping> ops = Collections.singletonList(tool("get_weather", "Returns the weather", schema));

        JsonArray tools = toolsOf(MCPPayloadGenerator.generateToolListPayload(1, ops, true));
        Assert.assertEquals(1, tools.size());
        JsonObject t = tools.get(0).getAsJsonObject();

        Assert.assertEquals("get_weather", t.get("name").getAsString());
        Assert.assertEquals("Returns the weather", t.get("description").getAsString());

        Assert.assertEquals("top-level title must be preserved", "Weather Lookup", t.get("title").getAsString());
        Assert.assertTrue("execution must be preserved", t.has("execution"));
        Assert.assertEquals("execution.mode value must be preserved", "async",
                t.getAsJsonObject("execution").get("mode").getAsString());
        Assert.assertEquals("execution.timeout value must be preserved", 30,
                t.getAsJsonObject("execution").get("timeout").getAsInt());

        Assert.assertTrue("annotations must be preserved", t.has("annotations"));
        Assert.assertTrue("annotations.readOnlyHint value must be preserved",
                t.getAsJsonObject("annotations").get("readOnlyHint").getAsBoolean());
        Assert.assertEquals("annotations.title value must be preserved", "Weather",
                t.getAsJsonObject("annotations").get("title").getAsString());

        Assert.assertTrue("_meta must be preserved", t.has("_meta"));
        Assert.assertEquals("wso2", t.getAsJsonObject("_meta").get("vendor").getAsString());

        Assert.assertTrue("outputSchema must be preserved", t.has("outputSchema"));
        Assert.assertEquals("outputSchema contents must be preserved verbatim", "number",
                t.getAsJsonObject("outputSchema").getAsJsonObject("properties")
                        .getAsJsonObject("temp").get("type").getAsString());
        Assert.assertEquals("outputSchema.required must be preserved verbatim", "temp",
                t.getAsJsonObject("outputSchema").getAsJsonArray("required").get(0).getAsString());

        // Proxy input schema is passed through verbatim (not sanitized).
        JsonObject inputSchema = t.getAsJsonObject("inputSchema");
        Assert.assertTrue("proxy inputSchema must be passed through unchanged",
                inputSchema.getAsJsonObject("properties").has("query_city"));
    }

    /**
     * Backward compatibility — a proxied tool stored in the LEGACY shape (the definition is the bare input
     * schema, with no {@code inputSchema} wrapper key) is still emitted with its input schema, unchanged.
     */
    @Test
    public void testProxyToolWithLegacyBareSchemaIsPassedThrough() {

        // Prefixed key: the third-party path must pass it through unchanged.
        String bareSchema = "{\"type\":\"object\",\"properties\":{\"query_message\":{\"type\":\"string\"}},"
                + "\"required\":[\"query_message\"]}";
        List<URLMapping> ops = Collections.singletonList(tool("echo", "Echoes the message", bareSchema));

        JsonArray tools = toolsOf(MCPPayloadGenerator.generateToolListPayload(1, ops, true));
        JsonObject t = tools.get(0).getAsJsonObject();

        Assert.assertEquals("echo", t.get("name").getAsString());
        Assert.assertTrue("inputSchema must be emitted", t.has("inputSchema"));
        JsonObject properties = t.getAsJsonObject("inputSchema").getAsJsonObject("properties");
        Assert.assertTrue("bare proxy schema must be passed through unchanged (prefix retained)",
                properties.has("query_message"));
        Assert.assertFalse("prefix must NOT be stripped on the third-party path", properties.has("message"));
        Assert.assertEquals("required must retain the prefixed key", "query_message",
                t.getAsJsonObject("inputSchema").getAsJsonArray("required").get(0).getAsString());
        Assert.assertFalse("no metadata should be invented for a bare schema", t.has("annotations"));
    }

    /**
     * For a NON third-party (OpenAPI/API-generated) server the input schema is SANITIZED (header/query/path
     * prefixes stripped, {@code contentType} removed) — while any sibling metadata is still emitted.
     */
    @Test
    public void testNonProxyToolSanitizesInputSchemaButKeepsMetadata() {

        String schema = "{"
                + "\"inputSchema\":{\"type\":\"object\","
                + "  \"properties\":{\"query_city\":{\"type\":\"string\"},\"contentType\":{\"type\":\"string\"}},"
                + "  \"required\":[\"query_city\"]},"
                + "\"annotations\":{\"readOnlyHint\":true}"
                + "}";
        List<URLMapping> ops = Collections.singletonList(tool("get_weather", "Returns the weather", schema));

        JsonArray tools = toolsOf(MCPPayloadGenerator.generateToolListPayload(1, ops, false));
        JsonObject t = tools.get(0).getAsJsonObject();

        JsonObject properties = t.getAsJsonObject("inputSchema").getAsJsonObject("properties");
        Assert.assertTrue("query_ prefix must be stripped for non-proxy", properties.has("city"));
        Assert.assertFalse("prefixed key must not remain", properties.has("query_city"));
        Assert.assertFalse("contentType must be removed", properties.has("contentType"));
        Assert.assertTrue("required prefix must be stripped",
                t.getAsJsonObject("inputSchema").getAsJsonArray("required").get(0).getAsString().equals("city"));
        Assert.assertTrue("sibling metadata must still be emitted", t.has("annotations"));
        Assert.assertTrue("annotations.readOnlyHint value must be preserved on the non-proxy path",
                t.getAsJsonObject("annotations").get("readOnlyHint").getAsBoolean());
    }

    /**
     * A null description is omitted from the emitted tool object (never serialized as a null/empty field).
     */
    @Test
    public void testNullDescriptionIsOmitted() {

        List<URLMapping> ops = Collections.singletonList(tool("echo", null, null));

        JsonArray tools = toolsOf(MCPPayloadGenerator.generateToolListPayload(1, ops, true));
        JsonObject t = tools.get(0).getAsJsonObject();

        Assert.assertEquals("echo", t.get("name").getAsString());
        Assert.assertFalse("null description must be omitted", t.has("description"));
    }

    // ------------------------------------------------------- the reported bug (#19337)

    /**
     * The bug scenario. A proxied backend schema uses snake_case names that are not location
     * prefixes; they must survive untouched. Before the fix this produced
     * {@code number} / {@code id} / {@code opendate}.
     */
    @Test
    public void testProxySnakeCasePropertyNamesArePreserved() {
        JsonObject schema = inputSchemaOf(generate(PROXY_SCHEMA, false));

        Assert.assertEquals("snake_case property names must not be truncated",
                new HashSet<>(Arrays.asList("agreement_number", "source_id", "opendate")),
                propertyKeys(schema));
        Assert.assertEquals("the required list must be sanitized the same way as the properties map",
                new HashSet<>(Arrays.asList("agreement_number", "source_id", "opendate")),
                new HashSet<>(requiredOf(schema)));
    }

    /** The tool name and description are metadata, never subject to prefix stripping. */
    @Test
    public void testToolNameAndDescriptionAreNotSanitized() {
        JsonObject tool = firstTool(generate(PROXY_SCHEMA, false));

        Assert.assertEquals(TOOL_NAME, tool.get("name").getAsString());
        Assert.assertEquals("Determine the surrender value of an agreement",
                tool.get("description").getAsString());
    }

    // --------------------------------------------- existing behaviour that must not regress

    /**
     * Every location prefix the OAS2 and OAS3 parsers can generate must still be stripped.
     * {@code cookie_} (OpenAPI 3) and {@code formData_} (Swagger 2) are included deliberately —
     * omitting them from the allow-list would silently regress API-derived MCP servers.
     */
    @Test
    public void testKnownLocationPrefixesAreStripped() {
        JsonObject schema = inputSchemaOf(generate(API_DERIVED_SCHEMA, false));

        Assert.assertEquals(
                new HashSet<>(Arrays.asList("city", "X-Trace", "itemId", "sessionId", "file")),
                propertyKeys(schema));
        Assert.assertEquals(new HashSet<>(Arrays.asList("itemId", "city")),
                new HashSet<>(requiredOf(schema)));
    }

    /** Only the leading prefix is removed; a second prefix-like segment is part of the name. */
    @Test
    public void testOnlyTheLeadingPrefixIsStripped() {
        String definition = "{\"inputSchema\":{\"type\":\"object\",\"properties\":{"
                + "\"query_header_x\":{\"type\":\"string\"}}}}";

        Assert.assertEquals(Collections.singleton("header_x"),
                propertyKeys(inputSchemaOf(generate(definition, false))));
    }

    /** {@code requestBody} is a reserved key and is never renamed, in properties or required. */
    @Test
    public void testRequestBodyKeyIsPreserved() {
        String definition = "{\"inputSchema\":{\"type\":\"object\","
                + "\"required\":[\"requestBody\",\"query_city\"],"
                + "\"properties\":{\"requestBody\":{\"type\":\"object\"},"
                + "\"query_city\":{\"type\":\"string\"}}}}";

        JsonObject schema = inputSchemaOf(generate(definition, false));

        Assert.assertEquals(new HashSet<>(Arrays.asList("requestBody", "city")), propertyKeys(schema));
        Assert.assertEquals(new HashSet<>(Arrays.asList("requestBody", "city")),
                new HashSet<>(requiredOf(schema)));
    }

    /** The {@code contentType} helper property is still dropped from the advertised schema. */
    @Test
    public void testContentTypePropertyIsRemoved() {
        String definition = "{\"inputSchema\":{\"type\":\"object\",\"properties\":{"
                + "\"contentType\":{\"type\":\"string\"},\"query_city\":{\"type\":\"string\"}}}}";

        Assert.assertEquals(Collections.singleton("city"),
                propertyKeys(inputSchemaOf(generate(definition, false))));
    }

    /** A schema stored without the {@code inputSchema} wrapper is sanitized just the same. */
    @Test
    public void testBareSchemaWithoutInputSchemaWrapperIsSanitized() {
        String definition = "{\"type\":\"object\",\"required\":[\"agreement_number\"],"
                + "\"properties\":{\"agreement_number\":{\"type\":\"string\"},"
                + "\"query_city\":{\"type\":\"string\"}}}";

        JsonObject schema = inputSchemaOf(generate(definition, false));

        Assert.assertEquals(new HashSet<>(Arrays.asList("agreement_number", "city")),
                propertyKeys(schema));
        Assert.assertEquals(Collections.singletonList("agreement_number"), requiredOf(schema));
    }

    /** When the caller marks the server as third party the schema is emitted verbatim. */
    @Test
    public void testThirdPartySchemaIsPassedThroughUnchanged() {
        JsonObject schema = inputSchemaOf(generate(API_DERIVED_SCHEMA, true));

        Assert.assertEquals("third-party schemas must not be rewritten at all",
                new HashSet<>(Arrays.asList("query_city", "header_X-Trace", "path_itemId",
                        "cookie_sessionId", "formData_file")),
                propertyKeys(schema));
    }

    // ------------------------------------------------------------------ edge cases

    /** A leading underscore has no location prefix in front of it and must be kept. */
    @Test
    public void testLeadingUnderscoreIsPreserved() {
        String definition = "{\"inputSchema\":{\"type\":\"object\",\"required\":[\"_id\"],"
                + "\"properties\":{\"_id\":{\"type\":\"string\"}}}}";

        JsonObject schema = inputSchemaOf(generate(definition, false));

        Assert.assertEquals(Collections.singleton("_id"), propertyKeys(schema));
        Assert.assertEquals(Collections.singletonList("_id"), requiredOf(schema));
    }

    /** Names with several underscores are not split at all. */
    @Test
    public void testMultipleUnderscoresArePreserved() {
        String definition = "{\"inputSchema\":{\"type\":\"object\",\"properties\":{"
                + "\"a_b_c\":{\"type\":\"string\"}}}}";

        Assert.assertEquals(Collections.singleton("a_b_c"),
                propertyKeys(inputSchemaOf(generate(definition, false))));
    }

    /**
     * A prefix word only counts when followed by an underscore — {@code query} and
     * {@code querystring} are ordinary names.
     */
    @Test
    public void testPrefixWordWithoutTrailingUnderscoreIsPreserved() {
        String definition = "{\"inputSchema\":{\"type\":\"object\",\"properties\":{"
                + "\"query\":{\"type\":\"string\"},\"querystring\":{\"type\":\"string\"},"
                + "\"path\":{\"type\":\"string\"}}}}";

        Assert.assertEquals(new HashSet<>(Arrays.asList("query", "querystring", "path")),
                propertyKeys(inputSchemaOf(generate(definition, false))));
    }

    /** A bare prefix key collapses to the empty string, matching the previous behaviour. */
    @Test
    public void testBarePrefixCollapsesToEmptyName() {
        String definition = "{\"inputSchema\":{\"type\":\"object\",\"properties\":{"
                + "\"query_\":{\"type\":\"string\"}}}}";

        Assert.assertEquals(Collections.singleton(""),
                propertyKeys(inputSchemaOf(generate(definition, false))));
    }

    /** Prefix matching is case sensitive; {@code Query_} is not a generated prefix. */
    @Test
    public void testPrefixMatchingIsCaseSensitive() {
        String definition = "{\"inputSchema\":{\"type\":\"object\",\"properties\":{"
                + "\"Query_city\":{\"type\":\"string\"}}}}";

        Assert.assertEquals(Collections.singleton("Query_city"),
                propertyKeys(inputSchemaOf(generate(definition, false))));
    }

    // ------------------------------------------------------------- negative / empty input

    /** A tool with no stored schema yields a tool entry carrying no input schema. */
    @Test
    public void testNullSchemaDefinitionProducesToolWithoutInputSchema() {
        JsonObject tool = firstTool(generate(null, false));

        Assert.assertEquals(TOOL_NAME, tool.get("name").getAsString());
        Assert.assertFalse("no inputSchema should be emitted when none is stored",
                tool.has("inputSchema"));
    }

    /** An empty properties map and an absent required list must not blow up. */
    @Test
    public void testEmptyPropertiesAndAbsentRequiredAreHandled() {
        String definition = "{\"inputSchema\":{\"type\":\"object\",\"properties\":{}}}";

        JsonObject schema = inputSchemaOf(generate(definition, false));

        Assert.assertTrue(propertyKeys(schema).isEmpty());
        Assert.assertTrue(requiredOf(schema).isEmpty());
        Assert.assertEquals("object", schema.get("type").getAsString());
    }

    /** An empty operation list still produces a well-formed, empty tools array. */
    @Test
    public void testEmptyOperationListProducesEmptyToolsArray() {
        String payload = MCPPayloadGenerator.generateToolListPayload(1, Collections.emptyList(), false);
        JsonObject root = JsonParser.parseString(payload).getAsJsonObject();

        Assert.assertEquals(0, root.getAsJsonObject("result").getAsJsonArray("tools").size());
    }

}
