<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://org.apache.axis2/xsd" xmlns:ns="http://service.impl.apimgt.carbon.wso2.org" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" targetNamespace="http://service.impl.apimgt.carbon.wso2.org">
   <wsdl:documentation>TierCacheService</wsdl:documentation>
   <wsdl:types>
      <xs:schema attributeFormDefault="qualified"
                 elementFormDefault="qualified"
                 targetNamespace="http://service.impl.apimgt.carbon.wso2.org">
         <xs:element name="invalidateCache">
            <xs:complexType>
               <xs:sequence>
                  <xs:element minOccurs="0"
                              name="tenantDomain"
                              nillable="true"
                              type="xs:string"/>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
      </xs:schema>
   </wsdl:types>
   <wsdl:message name="invalidateCacheRequest">
      <wsdl:part name="parameters" element="ns:invalidateCache"/>
   </wsdl:message>
   <wsdl:portType name="TierCacheServicePortType">
      <wsdl:operation name="invalidateCache">
         <wsdl:input message="ns:invalidateCacheRequest" wsaw:Action="urn:invalidateCache"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="TierCacheServiceSoap11Binding" type="ns:TierCacheServicePortType">
      <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
      <wsdl:operation name="invalidateCache">
         <soap:operation soapAction="urn:invalidateCache" style="document"/>
         <wsdl:input>
            <soap:body use="literal"/>
         </wsdl:input>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:binding name="TierCacheServiceSoap12Binding" type="ns:TierCacheServicePortType">
      <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
      <wsdl:operation name="invalidateCache">
         <soap12:operation soapAction="urn:invalidateCache" style="document"/>
         <wsdl:input>
            <soap12:body use="literal"/>
         </wsdl:input>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:binding name="TierCacheServiceHttpBinding" type="ns:TierCacheServicePortType">
      <http:binding verb="POST"/>
      <wsdl:operation name="invalidateCache">
         <http:operation location="invalidateCache"/>
         <wsdl:input>
            <mime:content type="text/xml" part="parameters"/>
         </wsdl:input>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="TierCacheService">
      <wsdl:port name="TierCacheServiceHttpSoap11Endpoint"
                 binding="ns:TierCacheServiceSoap11Binding">
         <soap:address location="http://localhost:8080/axis2/services/TierCacheService"/>
      </wsdl:port>
      <wsdl:port name="TierCacheServiceHttpSoap12Endpoint"
                 binding="ns:TierCacheServiceSoap12Binding">
         <soap12:address location="http://localhost:8080/axis2/services/TierCacheService"/>
      </wsdl:port>
      <wsdl:port name="TierCacheServiceHttpEndpoint"
                 binding="ns:TierCacheServiceHttpBinding">
         <http:address location="http://localhost:8080/axis2/services/TierCacheService"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
