- title: Using a Valid OpenAPI Definition
  rawRequest: |
    POST https://localhost:9443/api/am/publisher/v1.0/apis/validate-openapi?returnContent=true HTTP/1.1
    Content-Type: multipart/form-data; boundary="----=_Part_0_771605626.1563876237955"
    Authorization: Bearer 031cf7d6-4f49-3089-a164-5289b171203a
    Content-Length: 1504

    ------=_Part_0_771605626.1563876237955
    Content-Type: application/octet-stream; name=swagger2-sample.1.0.0.yaml
    Content-Transfer-Encoding: binary
    Content-Disposition: form-data; name="file"; filename="swagger2-sample.1.0.0.yaml"

    paths:
      /menu:
        patch:
          x-auth-type: "Application & Application User"
          responses:
            200:
              description: "OK"
          x-throttling-tier: "Unlimited"
        post:
          x-auth-type: "Application & Application User"
          responses:
            200:
              description: "OK"
          x-throttling-tier: "Unlimited"
        get:
          x-auth-type: "Application & Application User"
          responses:
            200:
              description: "OK"
          x-throttling-tier: "Unlimited"
        delete:
          x-auth-type: "Application & Application User"
          responses:
            200:
              description: "OK"
          x-throttling-tier: "Unlimited"
        put:
          x-auth-type: "Application & Application User"
          responses:
            200:
              description: "OK"
          x-throttling-tier: "Unlimited"
    securityDefinitions:
      default:
        tokenUrl: "https://test.com"
        type: "oauth2"
        flow: "password"
    swagger: "2.0"
    x-wso2-security:
      apim:
        x-wso2-scopes: []
    info:
      title: "sample"
      version: "1.0.0"

    ------=_Part_0_771605626.1563876237955--

  curl: |
    curl -k -H "Authorization: Bearer 031cf7d6-4f49-3089-a164-5289b171203a" -F file=@petstore.v3.yaml  -X POST https://localhost:9443/api/am/publisher/v1.0/apis/validate-openapi?returnContent=true
  rawResponse: |
    HTTP/1.1 200 OK
    Date: Tue, 23 Jul 2019 10:04:01 GMT
    Content-Type: application/json
    Transfer-Encoding: chunked

    {
      "isValid" : true,
      "content" : "  paths: \n    /menu: \n      patch: \n        x-auth-type: \"Application & Application User\"\n        responses: \n          200: \n            description: \"OK\"\n        x-throttling-tier: \"Unlimited\"\n      post: \n        x-auth-type: \"Application & Application User\"\n        responses: \n          200: \n            description: \"OK\"\n        x-throttling-tier: \"Unlimited\"\n      get: \n        x-auth-type: \"Application & Application User\"\n        responses: \n          200: \n            description: \"OK\"\n        x-throttling-tier: \"Unlimited\"\n      delete: \n        x-auth-type: \"Application & Application User\"\n        responses: \n          200: \n            description: \"OK\"\n        x-throttling-tier: \"Unlimited\"\n      put: \n        x-auth-type: \"Application & Application User\"\n        responses: \n          200: \n            description: \"OK\"\n        x-throttling-tier: \"Unlimited\"\n  securityDefinitions: \n    default: \n      tokenUrl: \"https://test.com\"\n      type: \"oauth2\"\n      flow: \"password\"\n  swagger: \"2.0\"\n  x-wso2-security: \n    apim: \n      x-wso2-scopes: []\n  info: \n    title: \"sample\"\n    version: \"1.0.0\"\n",
      "errors" : [ ]
    }

- title: Using an Invalid OpenAPI Definition
  rawRequest: |
    POST https://localhost:9443/api/am/publisher/v1.0/apis/validate-openapi HTTP/1.1
    Accept-Encoding: gzip,deflate
    Content-Type: multipart/form-data; boundary="----=_Part_7_1998017516.1563885449948"
    Authorization: Bearer 031cf7d6-4f49-3089-a164-5289b171203a
    Content-Length: 2841

      ------=_Part_7_1998017516.1563885449948
    Content-Type: application/octet-stream; name=petstore.v3-invalid.yaml
    Content-Transfer-Encoding: binary
    Content-Disposition: form-data; name="file"; filename="petstore.v3-invalid.yaml"

    openapi: "3.0.0"
    servers:
      - url: http://petstore.swagger.io/v1
    paths:
      /pets:
        get:
          summary: List all pets
          operationId: listPets
          tags:
            - pets
          parameters:
            - name: limit
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer
                format: int32
          responses:
            '200':
              description: A paged array of pets
              headers:
                x-next:
                  description: A link to the next page of responses
                  schema:
                    type: string
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Pets"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        post:
          summary: Create a pet
          operationId: createPets
          tags:
            - pets
          responses:
            '201':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
      /pets/{petId}:
        get:
          summary: Info for a specific pet
          operationId: showPetById
          tags:
            - pets
          parameters:
            - name: petId
              in: path
              required: true
              description: The id of the pet to retrieve
              schema:
                type: string
          responses:
            '200':
              description: Expected response to a valid request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Pet"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        Pet:
          required:
            - id
            - name
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            tag:
              type: string
        Pets:
          type: array
          items:
            $ref: "#/components/schemas/Pet"
        Error:
          required:
            - code
            - message
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
      ------=_Part_7_1998017516.1563885449948--


  curl: |
      curl -k -H "Authorization: Bearer 031cf7d6-4f49-3089-a164-5289b171203a" -F file=@petstore.v3-invalid.yaml  -X POST https://localhost:9443/api/am/publisher/v1.0/apis/validate-openapi?returnContent=true
  rawResponse: |
      HTTP/1.1 200 OK
      Date: Tue, 23 Jul 2019 10:04:01 GMT
      Content-Type: application/json
      Transfer-Encoding: chunked

      {
        "isValid" : false,
        "content" : null,
        "errors" : [
        {
          "code" : "900754",
          "message" : "Error while parsing OpenAPI definition",
          "description" : "attribute info is missing"
        }
        ]
      }