{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "WSO2 API Manager - Endpoint Registry",
    "description" : "This specifies a **RESTful API** for Enpoint Registry.\n",
    "version" : "1.0"
  },
  "servers" : [ {
    "url" : "https://apis.wso2.com/api/am/endpoint-registry/v1"
  }, {
    "url" : "http://apis.wso2.com/api/am/endpoint-registry/v1"
  } ],
  "paths" : {
    "/registries" : {
      "get" : {
        "tags" : [ "Registries" ],
        "summary" : "Retrieve all Registries\n",
        "description" : "This operation provides you an array of available Registries.\n",
        "operationId" : "getRegistries",
        "security" : [ {
          "default" : [ "registry:view" ]
        } ]
      },
      "post" : {
        "tags" : [ "Registries" ],
        "summary" : "Create a new Registry",
        "description" : "This operation can be used to create a new Registry specifying the details of the Registry in the payload.\n",
        "operationId" : "addRegistry",
        "security" : [ {
          "default" : [ "registry:write" ]
        } ]
      }
    },
    "/registries/{registryId}" : {
      "get" : {
        "tags" : [ "Registries" ],
        "summary" : "Get details of a Registry",
        "description" : "Using this operation, you can retrieve complete details of a single Registry using the RegistryId.\n",
        "operationId" : "getRegistryByUUID",
        "security" : [ {
          "default" : [ "registry:view" ]
        } ]
      },
      "put" : {
        "tags" : [ "Registries" ],
        "summary" : "Update an existing Registry",
        "description" : "This operation can be used to update an existing Endpoint Registry\n",
        "operationId" : "updateRegistry",
        "security" : [ {
          "default" : [ "registry:write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Registries" ],
        "summary" : "Delete an Endpoint Registry",
        "description" : "This operation can be used to delete an existing Registry proving the Id of the Registry.\n",
        "operationId" : "deleteRegistry",
        "security" : [ {
          "default" : [ "registry:write" ]
        } ]
      }
    },
    "/registries/{registryId}/entries" : {
      "get" : {
        "tags" : [ "Registry Entries" ],
        "summary" : "Get All entries in the registry",
        "operationId" : "getAllEntriesInRegistry",
        "security" : [ {
          "default" : [ "registry:entry_view" ]
        } ]
      }
    },
    "/registries/{registryId}/entry" : {
      "post" : {
        "tags" : [ "Registry Entries" ],
        "summary" : "Create a new Registry Entry",
        "description" : "This operation can be used to create a new Registry Entry specifying the details of the Entry in the payload.\n",
        "operationId" : "createRegistryEntry",
        "security" : [ {
          "default" : [ "registry:entry_write" ]
        } ]
      }
    },
    "/registries/{registryId}/entries/{entryId}" : {
      "get" : {
        "tags" : [ "Registry Entries" ],
        "summary" : "Retrieve a specific Entry in a Registry",
        "description" : "Using this operation, you can retrieve a specific entry in a single Registry using the EntryId and RegistryId.\n",
        "operationId" : "getRegistryEntryByUuid",
        "security" : [ {
          "default" : [ "registry:entry_view" ]
        } ]
      },
      "put" : {
        "tags" : [ "Registry Entries" ],
        "summary" : "Update an existing Entry in a Registry",
        "description" : "This operation can be used to update an existing Entry in Registry with the details of the Entry in the payload.\n",
        "operationId" : "updateRegistryEntry",
        "security" : [ {
          "default" : [ "registry:entry_write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Registry Entries" ],
        "summary" : "Delete an Entry in a Registry",
        "description" : "This operation can be used to delete an existing Entry in Registry by specifying the registryId and entryId.\n",
        "operationId" : "deleteRegistryEntry",
        "security" : [ {
          "default" : [ "registry:entry_write" ]
        } ]
      }
    },
    "/registries/{registryId}/entries/{entryId}/definition-file" : {
      "get" : {
        "tags" : [ "Registry Entries" ],
        "summary" : "Retrieve the definition file of a specific Entry in a Registry",
        "description" : "Using this operation, you can retrieve the definition file of a specific entry in a Registry using the EntryId and RegistryId.\n",
        "operationId" : "getEndpointDefinition",
        "security" : [ {
          "default" : [ "registry:entry_view" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "default" : {
        "type" : "oauth2",
        "flows" : {
          "implicit" : {
            "authorizationUrl" : "https://example.com/oauth/authorize",
            "scopes" : {
              "registry:view" : "view registry",
              "registry:write" : "write registry",
              "registry:entry_view" : "view reg entry",
              "registry:entry_write" : "write reg entry"
            }
          }
        }
      }
    }
  }
}