theme : "org.wso2.carbon.uuf.common.default.theme"

menus:
  - name: "main"
    items:
      - text: "Home"
        link: ""
        icon: "fw-home"
  - name: "left"
    items:
      - text: "APIs"
        link: ""
        icon: "fw-home"
      - text: "Applications"
        link: "/applications"
      - text: "Forum"
        link: "/forum"
      - text: "Statistics"
        link: "/statistics"

errorPages:
  404: /commons/error/404
  default: /commons/error/default