get:
  - id: GetAlertConfigurations
    request:
      method: GET
      url: https://localhost:9443/api/am/store/v1.0/alerts/AbnormalRequestCount/configurations
      headers: |
        Authorization: Bearer eff01a97-4dc0-3542-a184-75aecf355ec2
    response:
      status:
        code: 200
        msg: OK
      body:
        {
          "count": 1,
          "list": [
          {
            "configurationId": "UGl6emFTaGFja0FQSSsxLjAuMCtEZWZhdWx0QXBwbGljYXRpb24K",
            "configuration": {
              "apiName": "PizzaShackAPI",
              "apiVersion": "1.0.0",
              "applicationName": "DefaultApplication",
              "requestConunt": "12"
            }
          }
          ]
        }
      headers: |
        Content-Type: application/json

put:
  - id: AddAlertConfiguration
    request:
      method: PUT
      url: https://localhost:9443/api/am/store/v1.0/alerts/AbnormalRequestCount/configurations/UGl6emFTaGFja0FQSSMxLjAuMCNEZWZhdWx0QXBwbGljYXRpb24
      headers: |
        Authorization: Bearer eff01a97-4dc0-3542-a184-75aecf355ec2
        Content-Type: application/json
      body:
        {
          "requestCount":"12112",
          "apiName":"PizzaShackAPI",
          "apiVersion":" 2.0",
          "applicationName":"DefaultApplication"
        }
    response:
      status:
        code: 200
        msg: OK
      headers: |
          Content-Type: application/json
      body:
        {
          "configurationId":"YWRhZGEjIDIuMCNEZWZhdWx0QXBwbGljYXRpb24",
          "configuration":
            {
              "requestCount":"12112",
              "apiName":"PizzaShackAPI",
              "apiVersion":" 2.0",
              "applicationName":"DefaultApplication"
            }
        }

delete:
  - id: RemoveAlertConfiguration
    request:
      method: DELETE
      url: https://localhost:9443/api/am/store/v1.0/alerts/AbnormalRequestCount/configurations/UGl6emFTaGFja0FQSSMxLjAuMCNEZWZhdWx0QXBwbGljYXRpb24
      headers: |
        Authorization: Bearer eff01a97-4dc0-3542-a184-75aecf355ec2
        Content-Type: application/json
      response:
        status:
          code: 200
          msg: OK
        headers: |
          Content-Type: application/json
