/*
 * Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.apimgt.governance.impl.dao.constants;

/**
 * This class represents the SQL Constants
 */
public class SQLConstants {

    public static final String CREATE_POLICY =
            "INSERT INTO GOV_POLICY (POLICY_ID, NAME, DESCRIPTION, " +
                    "POLICY_CATEGORY, POLICY_TYPE, ARTIFACT_TYPE, " +
                    "DOCUMENTATION_LINK, PROVIDER, ORGANIZATION, CREATED_BY) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    public static final String ADD_POLICY_CONTENT =
            "INSERT INTO GOV_POLICY_CONTENT(POLICY_ID, CONTENT, CONTENT_TYPE, FILE_NAME) " +
                    "VALUES (?, ?, ?, ?)";

    public static final String ADD_RULES =
            "INSERT INTO GOV_POLICY_RULE (POLICY_RULE_ID, POLICY_ID, " +
                    "RULE_NAME, RULE_DESCRIPTION, SEVERITY, RULE_CONTENT) " +
                    "VALUES (?, ?, ?, ?, ?, ?)";

    public static final String GET_POLICIES =
            "SELECT POLICY_ID, NAME, DESCRIPTION, POLICY_CATEGORY, POLICY_TYPE, ARTIFACT_TYPE, " +
                    "DOCUMENTATION_LINK, PROVIDER, ORGANIZATION, CREATED_BY, CREATED_TIME, " +
                    "UPDATED_BY, LAST_UPDATED_TIME " +
                    "FROM GOV_POLICY WHERE ORGANIZATION = ?";

    public static final String GET_POLICY_BY_NAME =
            "SELECT POLICY_ID, NAME, DESCRIPTION, POLICY_CATEGORY, POLICY_TYPE, ARTIFACT_TYPE, " +
                    "DOCUMENTATION_LINK, PROVIDER, ORGANIZATION, CREATED_BY, CREATED_TIME, " +
                    "UPDATED_BY, LAST_UPDATED_TIME " +
                    "FROM GOV_POLICY WHERE NAME = ? AND ORGANIZATION = ?";

    public static final String GET_POLICIES_BY_ID =
            "SELECT POLICY_ID, NAME, DESCRIPTION,  POLICY_CATEGORY, " +
                    "POLICY_TYPE, ARTIFACT_TYPE, DOCUMENTATION_LINK, " +
                    "PROVIDER, ORGANIZATION, CREATED_BY, CREATED_TIME, UPDATED_BY, LAST_UPDATED_TIME " +
                    "FROM GOV_POLICY WHERE POLICY_ID = ? AND ORGANIZATION = ?";

    public static final String GET_POLICY_CONTENT =
            "SELECT CONTENT, CONTENT_TYPE, FILE_NAME FROM GOV_POLICY_CONTENT " +
                    "JOIN GOV_POLICY ON GOV_POLICY_CONTENT.POLICY_ID = GOV_POLICY.POLICY_ID " +
                    "WHERE GOV_POLICY_CONTENT.POLICY_ID = ? AND GOV_POLICY.ORGANIZATION = ?";

    public static final String UPDATE_POLICY =
            "UPDATE GOV_POLICY SET NAME = ?, DESCRIPTION = ?, " +
                    "POLICY_CATEGORY = ?, POLICY_TYPE = ?, ARTIFACT_TYPE = " +
                    "?, DOCUMENTATION_LINK = ?, PROVIDER = ?, UPDATED_BY = ?, " +
                    "LAST_UPDATED_TIME = CURRENT_TIMESTAMP " +
                    "WHERE POLICY_ID = ? AND ORGANIZATION = ?";

    public static final String UPDATE_POLICY_CONTENT =
            "UPDATE GOV_POLICY_CONTENT SET CONTENT = ?, CONTENT_TYPE = ?, FILE_NAME = ? " +
                    "WHERE POLICY_ID = ?";

    public static final String SEARCH_POLICIES = "SELECT POLICY_ID, NAME, " +
            "DESCRIPTION, POLICY_CATEGORY, " +
            "POLICY_TYPE, ARTIFACT_TYPE, DOCUMENTATION_LINK, PROVIDER, ORGANIZATION, " +
            "CREATED_BY, CREATED_TIME, " +
            "UPDATED_BY, LAST_UPDATED_TIME FROM GOV_POLICY WHERE ORGANIZATION = ? " +
            "AND NAME LIKE %?% AND POLICY_TYPE LIKE %?% " +
            "AND ARTIFACT_TYPE LIKE %?%";

    public static final String DELETE_POLICY =
            "DELETE FROM GOV_POLICY WHERE POLICY_ID = ? AND ORGANIZATION = ?";

    public static final String DELETE_RULES =
            "DELETE FROM GOV_POLICY_RULE WHERE POLICY_ID = ?";

    public static final String DELETE_POLICY_CONTENT =
            "DELETE FROM GOV_POLICY_CONTENT WHERE POLICY_ID = ?";

    public static final String GET_RULES_WITHOUT_CONTENT =
            "SELECT PR.POLICY_RULE_ID, PR.POLICY_ID, PR.RULE_NAME, " +
                    "PR.RULE_DESCRIPTION, PR.SEVERITY " +
                    "FROM GOV_POLICY_RULE PR JOIN GOV_POLICY GP ON PR.POLICY_ID = GP.POLICY_ID " +
                    "WHERE PR.POLICY_ID = ? AND GP.ORGANIZATION = ?";

    public static final String CREATE_POLICY_ATTACHMENT =
            "INSERT INTO GOV_POLICY_ATTACHMENT (POLICY_ATTACHMENT_ID, NAME, DESCRIPTION, " +
                    "ORGANIZATION, CREATED_BY, IS_GLOBAL) " +
                    "VALUES (?, ?, ?, ?, ?, ?)";

    public static final String CREATE_POLICY_ATTACHMENT_POLICY_MAPPING =
            "INSERT INTO GOV_POLICY_ATTACHMENT_POLICY (POLICY_ATTACHMENT_ID, POLICY_ID) VALUES (?, ?)";

    public static final String CREATE_GOVERNANCE_POLICY_ATTACHMENT_LABEL_MAPPING =
            "INSERT INTO GOV_POLICY_ATTACHMENT_LABEL (POLICY_ATTACHMENT_ID, LABEL) VALUES (?, ?)";

    public static final String CREATE_GOVERNANCE_POLICY_ATTACHMENT_STATE_MAPPING =
            "INSERT INTO GOV_POLICY_ATTACHMENT_STATE (POLICY_ATTACHMENT_ID, STATE) VALUES (?, ?)";

    public static final String CREATE_GOVERNANCE_POLICY_ATTACHMENT_ACTION_MAPPING =
            "INSERT INTO " +
                    "GOV_POLICY_ATTACHMENT_ACTION (POLICY_ATTACHMENT_ID, STATE, SEVERITY, TYPE) VALUES (?, ?, ?, ?)";

    public static final String DELETE_GOVERNANCE_POLICY_ATTACHMENT =
            "DELETE FROM GOV_POLICY_ATTACHMENT WHERE POLICY_ATTACHMENT_ID = ? AND ORGANIZATION = ?";

    public static final String DELETE_GOVERNANCE_POLICY_ATTACHMENT_LABEL_MAPPING_BY_POLICY_ID =
            "DELETE FROM GOV_POLICY_ATTACHMENT_LABEL WHERE POLICY_ATTACHMENT_ID = ?";

    public static final String DELETE_GOVERNANCE_POLICY_ATTACHMENT_STATE_MAPPING_BY_POLICY_ID =
            "DELETE FROM GOV_POLICY_ATTACHMENT_STATE WHERE POLICY_ATTACHMENT_ID = ?";

    public static final String DELETE_POLICY_ATTACHMENT_POLICY_MAPPING_BY_POLICY_ATTACHMENT_ID =
            "DELETE FROM GOV_POLICY_ATTACHMENT_POLICY WHERE POLICY_ATTACHMENT_ID = ?";

    public static final String DELETE_GOVERNANCE_POLICY_ATTACHMENT_ACTION_MAPPING_BY_POLICY_ATTACHMENT_ID =
            "DELETE FROM GOV_POLICY_ATTACHMENT_ACTION WHERE POLICY_ATTACHMENT_ID = ?";

    public static final String DELETE_GOVERNANCE_POLICY_ATTACHMENT_BY_LABEL =
            "DELETE FROM GOV_POLICY_ATTACHMENT_LABEL WHERE LABEL = ? AND ORGANIZATION = ?";

    public static final String GET_POLICY_ATTACHMENT_BY_NAME =
            "SELECT POLICY_ATTACHMENT_ID, NAME, DESCRIPTION, CREATED_BY, CREATED_TIME, UPDATED_BY, " +
                    "LAST_UPDATED_TIME, IS_GLOBAL FROM GOV_POLICY_ATTACHMENT WHERE ORGANIZATION = ? AND NAME = ?";

    public static final String GET_POLICY_ATTACHMENT_BY_ID =
            "SELECT POLICY_ATTACHMENT_ID, NAME, DESCRIPTION, CREATED_BY, CREATED_TIME, UPDATED_BY, " +
                    "LAST_UPDATED_TIME, IS_GLOBAL FROM GOV_POLICY_ATTACHMENT WHERE POLICY_ATTACHMENT_ID = ? " +
                    "AND ORGANIZATION = ?";

    public static final String GET_POLICY_ATTACHMENT =
            "SELECT POLICY_ATTACHMENT_ID, NAME, DESCRIPTION, CREATED_BY, CREATED_TIME, UPDATED_BY, " +
                    "LAST_UPDATED_TIME, IS_GLOBAL FROM GOV_POLICY_ATTACHMENT WHERE ORGANIZATION = ?";

    public static final String SEARCH_POLICY_ATTACHMENT =
            "SELECT DISTINCT GP.POLICY_ATTACHMENT_ID, GP.NAME, GP.DESCRIPTION, GP.CREATED_BY, GP.CREATED_TIME, " +
                    "GP.UPDATED_BY, GP.LAST_UPDATED_TIME, GP.IS_GLOBAL " +
                    "FROM GOV_POLICY_ATTACHMENT GP " +
                    "JOIN GOV_POLICY_ATTACHMENT_LABEL GPL ON GP.POLICY_ATTACHMENT_ID = GPL.POLICY_ATTACHMENT_ID " +
                    "JOIN GOV_POLICY_ATTACHMENT_STATE GPS ON GP.POLICY_ATTACHMENT_ID = " +
                    "GPS.POLICY_ATTACHMENT_ID WHERE GP.ORGANIZATION = ? AND GP.NAME LIKE %?% " +
                    "AND GPS.STATE LIKE %?%";

    public static final String UPDATE_POLICY_ATTACHMENT =
            "UPDATE GOV_POLICY_ATTACHMENT SET NAME = ?, DESCRIPTION = ?, UPDATED_BY = ?, IS_GLOBAL = ?, " +
                    "LAST_UPDATED_TIME = CURRENT_TIMESTAMP " +
                    "WHERE POLICY_ATTACHMENT_ID = ? AND ORGANIZATION = ?";

    public static final String GET_POLICY_IDS_BY_POLICY_ATTACHMENT_ID =
            "SELECT POLICY_ID FROM GOV_POLICY_ATTACHMENT_POLICY WHERE POLICY_ATTACHMENT_ID = ?";

    public static final String GET_LABELS_BY_POLICY_ATTACHMENT_ID =
            "SELECT LABEL FROM GOV_POLICY_ATTACHMENT_LABEL WHERE POLICY_ATTACHMENT_ID = ?";

    public static final String GET_STATES_BY_POLICY_ATTACHMENT_ID =
            "SELECT STATE FROM GOV_POLICY_ATTACHMENT_STATE WHERE POLICY_ATTACHMENT_ID = ?";

    public static final String GET_ACTIONS_BY_POLICY_ATTACHMENT_ID =
            "SELECT STATE,SEVERITY,TYPE FROM GOV_POLICY_ATTACHMENT_ACTION WHERE POLICY_ATTACHMENT_ID = ?";

    public static final String GET_POLICY_ATTACHMENT_FOR_POLICY =
            "SELECT POLICY_ATTACHMENT_ID FROM GOV_POLICY_ATTACHMENT_POLICY GAP " +
                    "JOIN GOV_POLICY GP ON GAP.POLICY_ID = GP.POLICY_ID " +
                    "WHERE GAP.POLICY_ID = ? AND GP.ORGANIZATION = ?";

    public static final String GET_POLICIES_BY_POLICY_ATTACHMENT_ID =
            "SELECT POLICY.POLICY_ID, POLICY.NAME, " +
                    "POLICY.POLICY_CATEGORY, POLICY.POLICY_TYPE, POLICY.ARTIFACT_TYPE " +
                    "FROM GOV_POLICY POLICY " +
                    "JOIN GOV_POLICY_ATTACHMENT_POLICY GAP ON POLICY.POLICY_ID = " +
                    "GAP.POLICY_ID " +
                    "WHERE GAP.POLICY_ATTACHMENT_ID = ? AND POLICY.ORGANIZATION = ?";
    public static final String GET_POLICIES_WITH_CONTENT_BY_POLICY_ATTACHMENT_ID =
            "SELECT POLICY.POLICY_ID, POLICY.NAME, " +
                    "POLICY.POLICY_CATEGORY, POLICY.POLICY_TYPE, POLICY.ARTIFACT_TYPE, " +
                    "GPC.CONTENT, GPC.CONTENT_TYPE, GPC.FILE_NAME " +
                    "FROM GOV_POLICY POLICY " +
                    "JOIN GOV_POLICY_CONTENT GPC " +
                    "ON POLICY.POLICY_ID = GPC.POLICY_ID " +
                    "JOIN GOV_POLICY_ATTACHMENT_POLICY GAP " +
                    "ON POLICY.POLICY_ID = GAP.POLICY_ID " +
                    "WHERE GAP.POLICY_ATTACHMENT_ID = ? AND POLICY.ORGANIZATION = ?";
    public static final String GET_POLICY_ATTACHMENTS_BY_LABEL =
            "SELECT DISTINCT GPA.POLICY_ID, GPA.NAME " +
                    "FROM GOV_POLICY_ATTACHMENT GPA " +
                    "JOIN GOV_POLICY_ATTACHMENT_LABEL GPAL ON GPA.POLICY_ATTACHMENT_ID = " +
                    "GPAL.POLICY_ATTACHMENT_ID " +
                    "WHERE GPAL.LABEL = ? " +
                    "AND GPA.ORGANIZATION = ?";

    public static final String GET_GLOBAL_POLICY_ATTACHMENTS =
            "SELECT DISTINCT GOV_POLICY_ATTACHMENT.POLICY_ATTACHMENT_ID, GOV_POLICY_ATTACHMENT.NAME " +
                    "FROM GOV_POLICY_ATTACHMENT " +
                    "WHERE GOV_POLICY_ATTACHMENT.ORGANIZATION = ? " +
                    "AND GOV_POLICY_ATTACHMENT.IS_GLOBAL = 1";

    public static final String GET_POLICY_ATTACHMENTS_BY_LABEL_AND_STATE =
            "SELECT DISTINCT GPA.POLICY_ATTACHMENT_ID " +
                    "FROM GOV_POLICY_ATTACHMENT GPA " +
                    "JOIN GOV_POLICY_ATTACHMENT_LABEL GPAL ON GPA.POLICY_ATTACHMENT_ID = GPAL.POLICY_ATTACHMENT_ID " +
                    "JOIN GOV_POLICY_ATTACHMENT_STATE GPAS ON GPA.POLICY_ATTACHMENT_ID = GPAS.POLICY_ATTACHMENT_ID ";


    public static final String GET_GLOBAL_POLICY_ATTACHMENT_BY_STATE =
            "SELECT DISTINCT GPA.POLICY_ATTACHMENT_ID " +
                    "FROM GOV_POLICY_ATTACHMENT GPA " +
                    "JOIN GOV_POLICY_ATTACHMENT_STATE GPAS ON GPA.POLICY_ATTACHMENT_ID = GPAS.POLICY_ATTACHMENT_ID " +
                    "WHERE GPAS.STATE = ? " +
                    "AND GPA.ORGANIZATION = ? " +
                    "AND GPA.IS_GLOBAL = 1";


    public static final String ADD_GOV_ARTIFACT = "INSERT INTO GOV_ARTIFACT " +
            "(ARTIFACT_KEY, ARTIFACT_REF_ID, ARTIFACT_TYPE, ORGANIZATION) VALUES (?, ?, ?, ?)";

    public static final String DELETE_GOV_ARTIFACT = "DELETE FROM GOV_ARTIFACT WHERE " +
            "ARTIFACT_REF_ID = ? AND ARTIFACT_TYPE = ? AND ORGANIZATION = ?";

    public static final String GET_ARTIFACT_KEY = "SELECT ARTIFACT_KEY " +
            "FROM GOV_ARTIFACT WHERE ARTIFACT_REF_ID = ? AND ARTIFACT_TYPE = ? AND ORGANIZATION = ?";

    public static final String GET_PENDING_REQ_FOR_ARTIFACT = "SELECT REQ_ID FROM GOV_REQUEST GR " +
            "JOIN GOV_ARTIFACT GA ON GR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
            "WHERE GA.ARTIFACT_REF_ID = ? AND GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ? AND GR.STATUS = 'PENDING'";

    public static final String GET_COMPLIANCE_PENDING_ARTIFACTS = "SELECT DISTINCT GA.ARTIFACT_REF_ID " +
            "FROM GOV_ARTIFACT GA " +
            "JOIN GOV_REQUEST GR ON GA.ARTIFACT_KEY = GR.ARTIFACT_KEY " +
            "WHERE GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ? AND GR.STATUS = 'PENDING'";
    public static final String ADD_GOV_EVAL_REQ = "INSERT INTO GOV_REQUEST " +
            "(REQ_ID, ARTIFACT_KEY) VALUES (?, ?)";

    public static final String ADD_REQ_POLICY_ATTACHMENT_MAPPING = "INSERT INTO GOV_REQUEST_POLICY_ATTACHMENT " +
            "(REQ_ID, POLICY_ATTACHMENT_ID) VALUES (?, ?)";

    public static final String GET_PENDING_REQ =
            "SELECT REQ_ID, ARTIFACT_REF_ID, ARTIFACT_TYPE, ORGANIZATION FROM GOV_REQUEST GR " +
                    "JOIN GOV_ARTIFACT GA ON GR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
                    "WHERE GR.STATUS = 'PENDING'";

    public static final String GET_REQ_POLICY_ATTACHMENT_MAPPING = "SELECT POLICY_ATTACHMENT_ID " +
            "FROM GOV_REQUEST_POLICY_ATTACHMENT WHERE REQ_ID = ?";

    public static final String UPDATE_GOV_REQ_STATUS_TO_PROCESSING = "UPDATE GOV_REQUEST " +
            "SET STATUS = 'PROCESSING', PROCESSING_TIMESTAMP = CURRENT_TIMESTAMP WHERE REQ_ID = ?" +
            "AND STATUS = 'PENDING'";

    public static final String UPDATE_GOV_REQ_STATUS_FROM_PROCESSING_TO_PENDING = "UPDATE GOV_REQUEST " +
            "SET STATUS = 'PENDING', PROCESSING_TIMESTAMP = NULL WHERE STATUS = 'PROCESSING'";

    public static final String DELETE_GOV_REQ = "DELETE FROM GOV_REQUEST" +
            " WHERE REQ_ID = ?";

    public static final String DELETE_REQ_POLICY_ATTACHMENT_MAPPING = "DELETE FROM GOV_REQUEST_POLICY_ATTACHMENT " +
            "WHERE REQ_ID = ?";

    public static final String DELETE_GOV_REQ_FOR_ARTIFACT = "DELETE FROM GOV_REQUEST " +
            "WHERE ARTIFACT_KEY IN (" +
            "    SELECT GA.ARTIFACT_KEY " +
            "    FROM GOV_ARTIFACT GA " +
            "    WHERE GA.ARTIFACT_REF_ID = ? AND GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ?" +
            ")";


    public static final String DELETE_REQ_POLICY_ATTACHMENT_MAPPING_FOR_ARTIFACT =
            "DELETE FROM GOV_REQUEST_POLICY_ATTACHMENT " +
                    "WHERE REQ_ID = (" +
                    "    SELECT GR.REQ_ID " +
                    "    FROM GOV_REQUEST GR " +
                    "    JOIN GOV_ARTIFACT GA ON GR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
                    "    WHERE GA.ARTIFACT_REF_ID = ? " +
                    "    AND GA.ARTIFACT_TYPE = ? " +
                    "    AND GA.ORGANIZATION = ? " +
                    "    LIMIT 1" +
                    ")";

    public static final String DELETE_REQ_POLICY_ATTACHMENT_MAPPING_FOR_POLICY_ATTACHMENT = "DELETE FROM " +
            "GOV_REQUEST_POLICY_ATTACHMENT WHERE POLICY_ATTACHMENT_ID = ?";

    public static final String ADD_POLICY_ATTACHMENT_RUN = "INSERT INTO GOV_POLICY_ATTACHMENT_RUN " +
            "(ARTIFACT_KEY, POLICY_ATTACHMENT_ID) VALUES (?, ?)";

    public static final String ADD_POLICY_RUN = "INSERT INTO GOV_POLICY_RUN (POLICY_RUN_ID, " +
            "ARTIFACT_KEY, POLICY_ID, RESULT) VALUES (?, ?, ?, ?)";

    public static final String ADD_RULE_VIOLATION = "INSERT INTO GOV_RULE_VIOLATION (ID, POLICY_RUN_ID, " +
            "POLICY_ID, RULE_NAME, VIOLATED_PATH, MESSAGE) VALUES (?, ?, ?, ?, ?, ?)";

    public static final String DELETE_POLICY_ATTACHMENT_RUN_FOR_ARTIFACT_AND_POLICY_ATTACHMENT = "DELETE " +
            "FROM GOV_POLICY_ATTACHMENT_RUN WHERE ARTIFACT_KEY IN ( " +
            "SELECT ARTIFACT_KEY FROM GOV_ARTIFACT WHERE ARTIFACT_REF_ID = ? " +
            "AND ARTIFACT_TYPE = ? AND ORGANIZATION = ? ) AND POLICY_ATTACHMENT_ID = ?";

    public static final String DELETE_POLICY_ATTACHMENT_RUN_FOR_POLICY_ATTACHMENT = "DELETE " +
            "FROM GOV_POLICY_ATTACHMENT_RUN WHERE POLICY_ATTACHMENT_ID = ?";

    public static final String GET_POLICY_ATTACHMENT_RUNS_FOR_ARTIFACT = "SELECT DISTINCT POLICY_ATTACHMENT_ID" +
            " FROM GOV_POLICY_ATTACHMENT_RUN GPR " +
            "JOIN GOV_ARTIFACT GA ON GPR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
            "WHERE GA.ARTIFACT_REF_ID = ? AND GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ?";

    public static final String GET_POLICY_ATTACHMENT_RUNS = "SELECT DISTINCT POLICY_ATTACHMENT_ID " +
            "FROM GOV_POLICY_ATTACHMENT_RUN GPR " +
            "JOIN GOV_ARTIFACT GA ON GPR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
            "WHERE GA.ORGANIZATION = ?";

    public static final String DELETE_POLICY_ATTACHMENT_RUNS_FOR_ARTIFACT = "DELETE FROM " +
            "GOV_POLICY_ATTACHMENT_RUN WHERE ARTIFACT_KEY " +
            "IN ( SELECT ARTIFACT_KEY FROM GOV_ARTIFACT WHERE ARTIFACT_REF_ID = ? " +
            "AND ARTIFACT_TYPE = ? AND ORGANIZATION = ? )";

    public static final String DELETE_POLICY_RUN_FOR_ARTIFACT_AND_POLICY = "DELETE FROM GOV_POLICY_RUN " +
            "WHERE ARTIFACT_KEY IN ( SELECT GA.ARTIFACT_KEY FROM GOV_ARTIFACT GA WHERE GA.ARTIFACT_REF_ID = ? " +
            "AND GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ? ) AND POLICY_ID = ?";

    public static final String DELETE_POLICY_RUN_FOR_POLICY = "DELETE FROM GOV_POLICY_RUN " +
            "WHERE POLICY_ID = ?";
    public static final String GET_POLICY_RUNS_FOR_ARTIFACT = "SELECT DISTINCT POLICY_ID " +
            "FROM GOV_POLICY_RUN GRR " +
            "JOIN GOV_ARTIFACT GA ON GRR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
            "WHERE GA.ARTIFACT_REF_ID = ? AND GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ?";

    public static final String GET_POLICY_RUN_FOR_ARTIFACT_AND_POLICY = "SELECT DISTINCT " +
            "POLICY_ID FROM GOV_POLICY_RUN GRR " +
            "JOIN GOV_ARTIFACT GA ON GRR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
            "WHERE GA.ARTIFACT_REF_ID = ? AND GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ? AND GRR.POLICY_ID = ?";

    public static final String GET_FAILED_POLICY_RUNS = "SELECT DISTINCT POLICY_ID FROM GOV_POLICY_RUN GRR " +
            "JOIN GOV_ARTIFACT GA ON GRR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
            "WHERE GA.ORGANIZATION = ? AND GRR.RESULT = 0";

    public static final String GET_FAILED_POLICY_RUNS_FOR_ARTIFACT = "SELECT DISTINCT POLICY_ID " +
            "FROM GOV_POLICY_RUN GRR " +
            "JOIN GOV_ARTIFACT GA ON GRR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
            "WHERE GA.ARTIFACT_REF_ID = ? AND GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ? AND GRR.RESULT = 0";
    public static final String DELETE_POLICY_RUNS_FOR_ARTIFACT = "DELETE FROM GOV_POLICY_RUN " +
            "WHERE ARTIFACT_KEY IN (SELECT ARTIFACT_KEY FROM GOV_ARTIFACT WHERE ARTIFACT_REF_ID = ? " +
            "AND ARTIFACT_TYPE = ? AND ORGANIZATION = ?);";

    public static final String DELETE_RULE_VIOLATIONS_FOR_ARTIFACT_AND_POLICY = "DELETE FROM GOV_RULE_VIOLATION " +
            "WHERE POLICY_RUN_ID IN ( SELECT GRR.POLICY_RUN_ID FROM GOV_POLICY_RUN GRR JOIN GOV_ARTIFACT GA " +
            "ON GRR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
            "WHERE GA.ARTIFACT_REF_ID = ? AND GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ? AND GRR.POLICY_ID = ? );";

    public static final String DELETE_RULE_VIOLATIONS_FOR_POLICY = "DELETE FROM GOV_RULE_VIOLATION " +
            "WHERE POLICY_ID = ?";

    public static final String DELETE_RULE_VIOLATIONS_FOR_ARTIFACT = "DELETE FROM GOV_RULE_VIOLATION " +
            "WHERE POLICY_RUN_ID IN ( SELECT GRR.POLICY_RUN_ID FROM GOV_POLICY_RUN GRR " +
            "INNER JOIN GOV_ARTIFACT GA ON GRR.ARTIFACT_KEY = GA.ARTIFACT_KEY WHERE GA.ARTIFACT_REF_ID = ? " +
            "AND GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ? );";

    public static final String GET_RULE_VIOLATIONS =
            "SELECT DISTINCT GRV.RULE_NAME, GRV.VIOLATED_PATH, GRV.MESSAGE, GPRL.SEVERITY " +
                    "FROM GOV_RULE_VIOLATION GRV " +
                    "JOIN GOV_POLICY_RUN GPR ON GRV.POLICY_RUN_ID = GPR.POLICY_RUN_ID " +
                    "JOIN GOV_ARTIFACT GA ON GPR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
                    "JOIN GOV_POLICY_RULE GPRL ON GPR.POLICY_ID = GPRL.POLICY_ID " +
                    "AND GRV.RULE_NAME = GPRL.RULE_NAME " +
                    "WHERE GA.ARTIFACT_REF_ID = ? AND GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ? AND " +
                    "GPR.POLICY_ID = ?";


    public static final String GET_RULE_VIOLATIONS_FOR_ARTIFACT =
            "SELECT DISTINCT GRV.POLICY_ID, GRV.RULE_NAME, GRV.VIOLATED_PATH, GRV.MESSAGE, GPRL.SEVERITY " +
                    "FROM GOV_RULE_VIOLATION GRV " +
                    "JOIN GOV_POLICY_RUN GPR ON GRV.POLICY_RUN_ID = GPR.POLICY_RUN_ID " +
                    "JOIN GOV_ARTIFACT GA ON GPR.ARTIFACT_KEY = GA.ARTIFACT_KEY " +
                    "JOIN GOV_POLICY_RULE GPRL ON GPR.POLICY_ID = GPRL.POLICY_ID " +
                    "AND GRV.RULE_NAME = GPRL.RULE_NAME " +
                    "WHERE GA.ARTIFACT_REF_ID = ? AND GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ?";

    public static final String GET_ALL_EVALUATED_ARTIFACTS =
            "SELECT DISTINCT GA.ARTIFACT_REF_ID " +
                    "FROM GOV_ARTIFACT GA " +
                    "JOIN GOV_POLICY_ATTACHMENT_RUN GPAR ON GA.ARTIFACT_KEY = GPAR.ARTIFACT_KEY " +
                    "WHERE GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ?";

    public static final String GET_NON_COMPLIANT_ARTIFACTS =
            "SELECT DISTINCT GA.ARTIFACT_REF_ID " +
                    "FROM GOV_ARTIFACT GA " +
                    "JOIN GOV_POLICY_ATTACHMENT_RUN GPAR ON GA.ARTIFACT_KEY = GPAR.ARTIFACT_KEY " +
                    "JOIN GOV_POLICY_RUN GPR ON GA.ARTIFACT_KEY = GPR.ARTIFACT_KEY " +
                    "WHERE GA.ARTIFACT_TYPE = ? AND GA.ORGANIZATION = ? AND GPR.RESULT = 0";

    public static final String GET_ARTIFACTS_FOR_POLICY_ATTACHMENT_RUN =
            "SELECT DISTINCT GA.ARTIFACT_REF_ID, " +
                    "GA.ARTIFACT_TYPE FROM GOV_ARTIFACT GA " +
                    "JOIN GOV_POLICY_ATTACHMENT_RUN GPAR ON GA.ARTIFACT_KEY = GPAR.ARTIFACT_KEY " +
                    "WHERE GPAR.POLICY_ATTACHMENT_ID = ? AND GA.ORGANIZATION = ?";


}
