export default {
    IPCONDITION: 'IPCONDITION',
    HEADERCONDITION: 'HEADERCONDITION',
    QUERYPARAMETERCONDITION: 'QUERYPARAMETERCONDITION',
    JWTCLAIMSCONDITION: 'JWTCLAIMSCONDITION',
    IPCONDITION_IPRANGE: 'IPRANGE',
    IPCONDITION_IPSPECIFIC: 'IPSPECIFIC',
};
