CREATE TABLE IF NOT EXISTS GOV_RULESET (
    RULESET_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    RULESET_CONTENT LONGBLOB NOT NULL,
    ARTIFACT_TYPE VARCHAR(128) NOT NULL,
    RULE_CATEGORY VARCHAR(128) NOT NULL,
    RULE_TYPE VARCHAR(128) NOT NULL,
    DOCUMENTATION_LINK VARCHAR(1024),
    PROVIDER VARCHAR(256),
    ORGANIZATION VARCHAR(128) NOT NULL,
    CREATED_BY VARCHAR(256),
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(256),
    LAST_UPDATED_TIME DATETIME,
    CONSTRAINT RULESET_CONSTRAINT UNIQUE (NAME, ORGANIZATION),
    PRIMARY KEY (RULESET_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_RULESET_RULE (
    RULESET_RULE_ID VARCHAR(36) NOT NULL,
    RULESET_ID VARCHAR(36) NOT NULL,
    RULE_NAME VARCHAR(256) NOT NULL,
    RULE_MESSAGE VARCHAR(1024),
    RULE_DESCRIPTION VARCHAR(1024),
    SEVERITY VARCHAR(32) NOT NULL,
    RULE_CONTENT BLOB NOT NULL,
    FOREIGN KEY (RULESET_ID) REFERENCES GOV_RULESET(RULESET_ID),
    CONSTRAINT RULESET_RULE_CONSTRAINT UNIQUE (RULESET_ID, RULE_NAME),
    PRIMARY KEY (RULESET_RULE_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_POLICY (
    POLICY_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    ORGANIZATION VARCHAR(128) NOT NULL,
    CREATED_BY VARCHAR(256),
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(256),
    LAST_UPDATED_TIME DATETIME,
    IS_GLOBAL INT DEFAULT 0, -- 1 - Global, 0 - Not Global
    CONSTRAINT POLICY_CONSTRAINT UNIQUE (NAME, ORGANIZATION),
    PRIMARY KEY (POLICY_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_POLICY_LABEL (
    POLICY_ID VARCHAR(36) NOT NULL,
    LABEL VARCHAR(128) NOT NULL,
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID),
    PRIMARY KEY (POLICY_ID, LABEL)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_POLICY_GOVERNABLE_STATE (
    POLICY_ID VARCHAR(36) NOT NULL,
    STATE VARCHAR(128) NOT NULL,
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID),
    PRIMARY KEY (POLICY_ID, STATE)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_POLICY_ACTION (
    POLICY_ID VARCHAR(36) NOT NULL,
    STATE VARCHAR(128) NOT NULL,
    SEVERITY VARCHAR(32) NOT NULL,
    TYPE VARCHAR(32) NOT NULL,
    FOREIGN KEY (POLICY_ID, STATE) REFERENCES GOV_POLICY_GOVERNABLE_STATE(POLICY_ID, STATE),
    PRIMARY KEY (POLICY_ID, STATE, SEVERITY, TYPE)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_POLICY_RULESET (
    POLICY_ID VARCHAR(36) NOT NULL,
    RULESET_ID VARCHAR(36) NOT NULL,
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID),
    FOREIGN KEY (RULESET_ID) REFERENCES GOV_RULESET(RULESET_ID),
    PRIMARY KEY (POLICY_ID, RULESET_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_ARTIFACT (
    ARTIFACT_KEY VARCHAR(36) NOT NULL,
    ARTIFACT_REF_ID VARCHAR(36) NOT NULL,
    ARTIFACT_TYPE VARCHAR(32) NOT NULL,
    ORGANIZATION VARCHAR(128) NOT NULL,
    CONSTRAINT GOV_ARTIFACT_CONSTRAINT UNIQUE (ARTIFACT_REF_ID, ARTIFACT_TYPE, ORGANIZATION),
    PRIMARY KEY (ARTIFACT_KEY)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_REQUEST (
    REQ_ID VARCHAR(36) NOT NULL,
    ARTIFACT_KEY VARCHAR(36) NOT NULL,
    STATUS VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    REQ_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    PROCESSING_TIMESTAMP DATETIME,
    CONSTRAINT EVAL_CONSTRAINT UNIQUE (STATUS, ARTIFACT_KEY),
    PRIMARY KEY (REQ_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_REQUEST_POLICY (
    REQ_ID VARCHAR(36) NOT NULL,
    POLICY_ID VARCHAR(36) NOT NULL,
    FOREIGN KEY (REQ_ID) REFERENCES GOV_REQUEST(REQ_ID),
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID),
    PRIMARY KEY (REQ_ID, POLICY_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_POLICY_RUN (
    ARTIFACT_KEY VARCHAR(36) NOT NULL,
    POLICY_ID VARCHAR(36) NOT NULL,
    RUN_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ARTIFACT_KEY) REFERENCES GOV_ARTIFACT(ARTIFACT_KEY),
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID),
    PRIMARY KEY (ARTIFACT_KEY, POLICY_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_RULESET_RUN (
    RULESET_RUN_ID VARCHAR(36) NOT NULL,
    ARTIFACT_KEY VARCHAR(36) NOT NULL,
    RULESET_ID VARCHAR(36) NOT NULL,
    RESULT INT NOT NULL, -- 1 - Pass, 0 - Fail
    RUN_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT RULESET_RESULT UNIQUE (ARTIFACT_KEY, RULESET_ID),
    FOREIGN KEY (ARTIFACT_KEY) REFERENCES GOV_ARTIFACT(ARTIFACT_KEY),
    FOREIGN KEY (RULESET_ID) REFERENCES GOV_RULESET(RULESET_ID),
    PRIMARY KEY (RULESET_RUN_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_RULE_VIOLATION (
    RULESET_RUN_ID VARCHAR(36) NOT NULL,
    RULESET_ID VARCHAR(36) NOT NULL,
    RULE_NAME VARCHAR(256) NOT NULL,
    VIOLATED_PATH VARCHAR(1024) NOT NULL,
    FOREIGN KEY (RULESET_RUN_ID) REFERENCES GOV_RULESET_RUN(RULESET_RUN_ID),
    FOREIGN KEY (RULESET_ID, RULE_NAME) REFERENCES GOV_RULESET_RULE(RULESET_ID, RULE_NAME),
    PRIMARY KEY (RULESET_RUN_ID, RULE_NAME, VIOLATED_PATH)
) ENGINE=INNODB;


