# Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License
################################################################################
openapi: 3.0.1
info:
  version: v1.1
  title: WSO2 API Manager - Governance
  description: |
    This document specifies a **RESTful API** for WSO2 **API Manager** - Governance.
  contact:
    name: WSO2
    url: http://wso2.com/products/api-manager/
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://apis.wso2.com/api/am/governance/v1
tags:
  - name: Governance Policies
    description: for managing governance policies.
  - name: Governance Policy Attachments
    description: for managing governance policy attachments.
  - name: Artifact Compliance
    description: for accessing artifact compliance.
  - name: Policy Attachment Adherence
    description: for accessing policy attachments adherence.
paths:
  /policies:
    get:
      summary: Retrieves a list of policies.
      description: Returns a list of all policies associated with the requested organization.
      operationId: getPolicies
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_read
    post:
      summary: Create a new policy.
      description: Creates a new policy in the user's organization.
      operationId: createPolicy
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_manage
  /policies/{policyId}:
    get:
      summary: Retrieves details of a specific policy.
      description: Retrieves details of the policy identified by the policyId.
      operationId: getPolicyById
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_read
    put:
      summary: Updates a specific policy.
      description: Updates the details of the policy identified by the `policyId`.
      operationId: updatePolicyById
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_manage
    delete:
      summary: Deletes a specific policy.
      description: Deletes an existing policy identified by the policyId.
      operationId: deletePolicy
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_manage
  /policies/{policyId}/content:
    get:
      summary: Retrieves the content of a specific policy.
      description: Retrieves the content of the policy identified by the policyId.
      operationId: getPolicyContent
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_read
  /policies/{policyId}/usage:
    get:
      summary: Retrieves the policy attachment usage of a specific policy.
      description: Retrieves the list of policy attachments using the policy identified by the policyId.
      operationId: getPolicyUsage
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_read
  /policy-attachments:
    get:
      summary: Retrieves a list of all governance policy-attachments.
      description: Retrieves a list of governance policy-attachments for the user's organization.
      operationId: getGovernancePolicyAttachments
      tags:
        - Governance Policy Attachments
      security:
        - OAuth2Security:
            - apim:gov_policy_attachment_read
    post:
      summary: Creates a new governance policy attachment.
      description: Creates a new governance policy attachment for the user's organization.
      operationId: createGovernancePolicyAttachment
      tags:
        - Governance Policy Attachments
      security:
        - OAuth2Security:
            - apim:gov_policy_attachment_manage
  /policy-attachments/{policyAttachmentId}:
    get:
      summary: Get a specific governance policy attachment
      description: Retrieves details of a specific governance policy attachment identified by the policyAttachmentId.
      operationId: getGovernancePolicyAttachmentById
      tags:
        - Governance Policy Attachments
      security:
        - OAuth2Security:
            - apim:gov_policy_attachment_read
    put:
      summary: Update a specific governance policy attachment
      description: Updates the details of an existing governance policy attachment identified by the policyAttachmentId.
      operationId: updateGovernancePolicyAttachmentById
      tags:
        - Governance Policy Attachments
      security:
        - OAuth2Security:
            - apim:gov_policy_attachment_manage
    delete:
      summary: Delete a specific governance policy attachment
      description: Deletes an existing governance policy attachment identified by the policyAttachmentId.
      operationId: deleteGovernancePolicyAttachment
      tags:
        - Governance Policy Attachments
      security:
        - OAuth2Security:
            - apim:gov_policy_attachment_manage
  /artifact-compliance/api:
    get:
      summary: Retrieves compliance of all API artifacts
      description: Retrieves compliance of all API artifacts within the organization.
      operationId: getComplianceStatusListOfAPIs
      tags:
        - Artifact Compliance
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /artifact-compliance/api/summary:
    get:
      summary: Retrieves the summary of compliance of all API artifacts
      description: Retrieves the summary of compliance of all API artifacts within the organization.
      operationId: getComplianceSummaryForAPIs
      tags:
        - Artifact Compliance
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /artifact-compliance/api/{apiId}:
    get:
      summary: Retrieve compliance details for a specific API
      description: Retrieve compliance details associated with a specific API using its unique UUID.
      operationId: getComplianceByAPIId
      tags:
        - Artifact Compliance
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /artifact-compliance/api/{apiId}/policy-validation-results/{policyId}:
    get:
      summary: Retrieve policy validation results for a specific API
      description: Retrieve policy validation results associated with a specific API using its unique UUID.
      operationId: getPolicyValidationResultsByAPIId
      tags:
        - Artifact Compliance
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /policy-attachment-adherence:
    get:
      summary: Retrieve adherence status for all policy attachments
      description: Retrieve adherence status of all governance policy attachments within the organization.
      operationId: getPolicyAttachmentAdherenceForAllPolicyAttachments
      tags:
        - Policy Attachment Adherence
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /policy-attachment-adherence/summary:
    get:
      summary: Retrieves the summary of adherence for all policy attachments
      description: Retrieves the summary of adherence for all governance policy attachments within the organization.
      operationId: getPolicyAttachmentAdherenceSummary
      tags:
        - Policy Attachment Adherence
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /policy-attachment-adherence/{policyAttachmentId}:
    get:
      summary: Retrieve adherence details for a specific policy attachment
      description: Retrieve adherence details associated with a specific governance policy attachment within the organization using its unique ID.
      operationId: getPolicyAttachmentAdherenceByPolicyAttachmentId
      tags:
        - Policy Attachment Adherence
      security:
        - OAuth2Security:
            - apim:gov_result_read

components:
  securitySchemes:
    OAuth2Security:
      type: oauth2
      flows:
        password:
          tokenUrl: https://localhost:9443/oauth2/token
          scopes:
            openid: Authorize access to user details
            apim:gov_policy_read: Read governance policies
            apim:gov_policy_manage: Manage governance policies
            apim:gov_policy_attachment_read: Read governance policy attachments
            apim:gov_policy_attachment_manage: Manage governance policy attachments
            apim:gov_result_read: Read governance results