# Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License
################################################################################
openapi: 3.0.1
info:
  version: v0.1
  title: WSO2 API Manager - Governance
  description: |
    This document specifies a **RESTful API** for WSO2 **API Manager** - Governance.
  contact:
    name: WSO2
    url: http://wso2.com/products/api-manager/
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://apis.wso2.com/api/am/governance/v0
tags:
  - name: Rulesets
    description: for managing rulesets.
  - name: Governance Policies
    description: for managing governance policies.
  - name: Artifact Compliance
    description: for accessing artifact compliance.
  - name: Policy Adherence
    description: for accessing policy adherence.
  - name: Health Check
    description: for health check.
  - name: Deprecated
    description: resources that are deprecated.
paths:
  /rulesets:
    get:
      summary: Retrieves a list of rulesets.
      description: Returns a list of all rulesets associated with the requested organization.
      operationId: getRulesets
      tags:
        - Rulesets
      security:
        - OAuth2Security:
            - apim:gov_rule_read
    post:
      summary: Create a new ruleset.
      description: Creates a new ruleset in the user's organization.
      operationId: createRuleset
      tags:
        - Rulesets
      security:
        - OAuth2Security:
            - apim:gov_rule_manage
  /rulesets/{rulesetId}:
    get:
      summary: Retrieves details of a specific ruleset.
      description: Retrieves details of the ruleset identified by the rulesetId.
      operationId: getRulesetById
      tags:
        - Rulesets
      security:
        - OAuth2Security:
            - apim:gov_rule_read
    put:
      summary: Updates a specific ruleset.
      description: Updates the details of the ruleset identified by the `rulesetId`.
      operationId: updateRulesetById
      tags:
        - Rulesets
      security:
        - OAuth2Security:
            - apim:gov_rule_manage
    delete:
      summary: Deletes a specific ruleset.
      description: Deletes an existing ruleset identified by the rulesetId.
      operationId: deleteRuleset
      tags:
        - Rulesets
      security:
        - OAuth2Security:
            - apim:gov_rule_manage
  /rulesets/{rulesetId}/content:
    get:
      summary: Retrieves the content of a specific ruleset.
      description: Retrieves the content of the ruleset identified by the rulesetId.
      operationId: getRulesetContent
      tags:
        - Rulesets
      security:
        - OAuth2Security:
            - apim:gov_rule_read
  /rulesets/{rulesetId}/usage:
    get:
      summary: Retrieves the policy usage of a specific ruleset.
      description: Retrieves the list of policies using the ruleset identified by the rulesetId.
      operationId: getRulesetUsage
      tags:
        - Rulesets
      security:
        - OAuth2Security:
            - apim:gov_rule_read
  /healthz/liveness:
    get:
      summary: Liveness Check
      description: Checks if the application is alive and able to respond to requests.
      operationId: getHealthzLiveness
      tags:
        - Health Check
        - Internal
  /healthz/readiness:
    get:
      summary: Readiness Check
      description: Checks if the application is ready to handle requests.
      operationId: getHealthzReadiness
      tags:
        - Health Check
        - Internal
  /governance-policies:
    get:
      summary: Retrieves a list of all governance policies.
      description: Retrieves a list of governance policies for the user's organization.
      operationId: getGovernancePolicies
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_read
    post:
      summary: Creates a new governance policy.
      description: Creates a new governance policy for the user's organization.
      operationId: createGovernancePolicy
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_manage
  /governance-policies/{policyId}:
    get:
      summary: Get a specific governance policy
      description: Retrieves details of a specific governance policy identified by the policyId.
      operationId: getGovernancePolicyById
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_read
    put:
      summary: Update a specific governance policy
      description: Updates the details of an existing governance policy identified by the policyId.
      operationId: updateGovernancePolicyById
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_manage
    delete:
      summary: Delete a specific governance policy
      description: Deletes an existing governance policy identified by the policyId.
      operationId: deleteGovernancePolicy
      tags:
        - Governance Policies
      security:
        - OAuth2Security:
            - apim:gov_policy_manage
  /artifact-compliance:
    get:
      summary: Retrieves compliance of all artifacts of a certain type
      description: Retrieves compliance of all artifacts of a certain type within the organization.
      operationId: getArtifactComplianceForAllArtifacts
      tags:
        - Artifact Compliance
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /artifact-compliance/summary:
    get:
      summary: Retrieves the summary of compliance of all artifacts of a certain type
      description: Retrieves the summary of compliance of all artifacts of a certain type within the organization.
      operationId: getArtifactComplianceSummary
      tags:
        - Artifact Compliance
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /artifact-compliance/{artifactId}:
    get:
      summary: Retrieve compliance details for a specific artifact
      description: Retrieve compliance details associated with a specific artifact including APIs within the organization using its unique UUID.
      operationId: getArtifactComplianceByArtifactId
      tags:
        - Artifact Compliance
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /artifact-compliance/{artifactId}/ruleset-validation-results/{rulesetId}:
    get:
      summary: Retrieve ruleset validation results for a specific artifact
      description: Retrieve ruleset validation results associated with a specific artifact including APIs within the organization using its unique UUID.
      operationId: getRulesetValidationResultsByArtifactId
      tags:
        - Artifact Compliance
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /policy-adherence:
    get:
      summary: Retrieve adherence status for all policies
      description: Retrieve adherence status of all governance policies within the organization.
      operationId: getPolicyAdherenceForAllPolicies
      tags:
        - Policy Adherence
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /policy-adherence/summary:
    get:
      summary: Retrieves the summary of adherence for all policies
      description: Retrieves the summary of adherence for all governance policies within the organization.
      operationId: getPolicyAdherenceSummary
      tags:
        - Policy Adherence
      security:
        - OAuth2Security:
            - apim:gov_result_read
  /policy-adherence/{policyId}:
    get:
      summary: Retrieve adherence details for a specific policy
      description: Retrieve adherence details associated with a specific governance policy within the organization using its unique ID.
      operationId: getPolicyAdherenceByPolicyId
      tags:
        - Policy Adherence
      security:
        - OAuth2Security:
            - apim:gov_result_read

components:
  #####
  # TODO: Fix scope validation logic. Currently scope validation is broken due to logic in apimgt.rest.api.common.RestAPICommonUtil
  #####
  securitySchemes:
    OAuth2Security:
      type: oauth2
      flows:
        password:
          tokenUrl: https://localhost:9443/oauth2/token
          scopes:
            openid: Authorize access to user details
            apim:gov_rule_read: Read governance rulesets
            apim:gov_rule_manage: Manage governance rulesets
            apim:gov_policy_read: Read governance policies
            apim:gov_policy_manage: Manage governance policies
            apim:gov_evaluate_compliance: Evaluate governance compliance
            apim:gov_result_read: Read governance results