/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.wso2.carbon.apimgt.gateway.handlers.security.thrift;
/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

import org.apache.thrift.meta_data.FieldMetaData;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class APIKeyValidationInfoDTO implements org.apache.thrift.TBase<APIKeyValidationInfoDTO, APIKeyValidationInfoDTO._Fields>, java.io.Serializable, Cloneable {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("APIKeyValidationInfoDTO");

    private static final org.apache.thrift.protocol.TField AUTHORIZED_FIELD_DESC = new org.apache.thrift.protocol.TField("authorized", org.apache.thrift.protocol.TType.BOOL, (short)1);
    private static final org.apache.thrift.protocol.TField SUBSCRIBER_FIELD_DESC = new org.apache.thrift.protocol.TField("subscriber", org.apache.thrift.protocol.TType.STRING, (short)2);
    private static final org.apache.thrift.protocol.TField TIER_FIELD_DESC = new org.apache.thrift.protocol.TField("tier", org.apache.thrift.protocol.TType.STRING, (short)3);
    private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.STRING, (short)4);
    private static final org.apache.thrift.protocol.TField END_USER_TOKEN_FIELD_DESC = new org.apache.thrift.protocol.TField("endUserToken", org.apache.thrift.protocol.TType.STRING, (short)5);
    private static final org.apache.thrift.protocol.TField END_USER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("endUserName", org.apache.thrift.protocol.TType.STRING, (short)6);
    private static final org.apache.thrift.protocol.TField APPLICATION_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("applicationName", org.apache.thrift.protocol.TType.STRING, (short)7);
    private static final org.apache.thrift.protocol.TField VALIDATION_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("validationStatus", org.apache.thrift.protocol.TType.I32, (short)8);
    private static final org.apache.thrift.protocol.TField APPLICATION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("applicationId", org.apache.thrift.protocol.TType.STRING, (short)9);
    private static final org.apache.thrift.protocol.TField APPLICATION_TIER_FIELD_DESC = new org.apache.thrift.protocol.TField("applicationTier", org.apache.thrift.protocol.TType.STRING, (short)10);
    private static final org.apache.thrift.protocol.TField API_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("apiName", org.apache.thrift.protocol.TType.STRING, (short)11);
    private static final org.apache.thrift.protocol.TField CONSUMER_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("consumerKey", org.apache.thrift.protocol.TType.STRING, (short)12);
    private static final org.apache.thrift.protocol.TField API_PUBLISHER_FIELD_DESC = new org.apache.thrift.protocol.TField("apiPublisher", org.apache.thrift.protocol.TType.STRING, (short)13);

    public boolean authorized; // required
    public String subscriber; // required
    public String tier; // required
    public String type; // required
    public String endUserToken; // required
    public String endUserName; // required
    public String applicationName; // required
    public int validationStatus; // required
    public String applicationId; // required
    public String applicationTier; // required
    public String apiName; // required
    public String consumerKey; // required
    public String apiPublisher; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        AUTHORIZED((short)1, "authorized"),
        SUBSCRIBER((short)2, "subscriber"),
        TIER((short)3, "tier"),
        TYPE((short)4, "type"),
        END_USER_TOKEN((short)5, "endUserToken"),
        END_USER_NAME((short)6, "endUserName"),
        APPLICATION_NAME((short)7, "applicationName"),
        VALIDATION_STATUS((short)8, "validationStatus"),
        APPLICATION_ID((short)9, "applicationId"),
        APPLICATION_TIER((short)10, "applicationTier"),
        API_NAME((short)11, "apiName"),
        CONSUMER_KEY((short)12, "consumerKey"),
        API_PUBLISHER((short)13, "apiPublisher");

        private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

        static {
            for (_Fields field : EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        public static _Fields findByThriftId(int fieldId) {
            switch(fieldId) {
                case 1: // AUTHORIZED
                    return AUTHORIZED;
                case 2: // SUBSCRIBER
                    return SUBSCRIBER;
                case 3: // TIER
                    return TIER;
                case 4: // TYPE
                    return TYPE;
                case 5: // END_USER_TOKEN
                    return END_USER_TOKEN;
                case 6: // END_USER_NAME
                    return END_USER_NAME;
                case 7: // APPLICATION_NAME
                    return APPLICATION_NAME;
                case 8: // VALIDATION_STATUS
                    return VALIDATION_STATUS;
                case 9: // APPLICATION_ID
                    return APPLICATION_ID;
                case 10: // APPLICATION_TIER
                    return APPLICATION_TIER;
                case 11: // API_NAME
                    return API_NAME;
                case 12: // CONSUMER_KEY
                    return CONSUMER_KEY;
                case 13: // API_PUBLISHER
                    return API_PUBLISHER;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        public static _Fields findByName(String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        public short getThriftFieldId() {
            return _thriftId;
        }

        public String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __AUTHORIZED_ISSET_ID = 0;
    private static final int __VALIDATIONSTATUS_ISSET_ID = 1;
    private BitSet __isset_bit_vector = new BitSet(2);

    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
        Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.AUTHORIZED, new org.apache.thrift.meta_data.FieldMetaData("authorized", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                                     new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
        tmpMap.put(_Fields.SUBSCRIBER, new org.apache.thrift.meta_data.FieldMetaData("subscriber", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                                     new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.TIER, new org.apache.thrift.meta_data.FieldMetaData("tier", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                               new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                               new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.END_USER_TOKEN, new org.apache.thrift.meta_data.FieldMetaData("endUserToken", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                                         new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.END_USER_NAME, new org.apache.thrift.meta_data.FieldMetaData("endUserName", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.APPLICATION_NAME, new org.apache.thrift.meta_data.FieldMetaData("applicationName", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                                           new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.VALIDATION_STATUS, new org.apache.thrift.meta_data.FieldMetaData("validationStatus", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                                            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
        tmpMap.put(_Fields.APPLICATION_ID, new org.apache.thrift.meta_data.FieldMetaData("applicationId", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                                         new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.APPLICATION_TIER, new org.apache.thrift.meta_data.FieldMetaData("applicationTier", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                                           new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.API_NAME, new org.apache.thrift.meta_data.FieldMetaData("apiName", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                                   new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.CONSUMER_KEY, new org.apache.thrift.meta_data.FieldMetaData("consumerKey", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                                       new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.API_PUBLISHER, new org.apache.thrift.meta_data.FieldMetaData("apiPublisher", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                                                                                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        metaDataMap = Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(APIKeyValidationInfoDTO.class, metaDataMap);
    }

    public APIKeyValidationInfoDTO() {
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public APIKeyValidationInfoDTO(APIKeyValidationInfoDTO other) {
        __isset_bit_vector.clear();
        __isset_bit_vector.or(other.__isset_bit_vector);
        this.authorized = other.authorized;
        if (other.isSetSubscriber()) {
            this.subscriber = other.subscriber;
        }
        if (other.isSetTier()) {
            this.tier = other.tier;
        }
        if (other.isSetType()) {
            this.type = other.type;
        }
        if (other.isSetEndUserToken()) {
            this.endUserToken = other.endUserToken;
        }
        if (other.isSetEndUserName()) {
            this.endUserName = other.endUserName;
        }
        if (other.isSetApplicationName()) {
            this.applicationName = other.applicationName;
        }
        this.validationStatus = other.validationStatus;
        if (other.isSetApplicationId()) {
            this.applicationId = other.applicationId;
        }
        if (other.isSetApplicationTier()) {
            this.applicationTier = other.applicationTier;
        }
        if (other.isSetApiName()) {
            this.apiName = other.apiName;
        }
        if (other.isSetConsumerKey()) {
            this.consumerKey = other.consumerKey;
        }
        if (other.isSetApiPublisher()) {
            this.apiPublisher = other.apiPublisher;
        }
    }

    public APIKeyValidationInfoDTO deepCopy() {
        return new APIKeyValidationInfoDTO(this);
    }

    @Override
    public void clear() {
        setAuthorizedIsSet(false);
        this.authorized = false;
        this.subscriber = null;
        this.tier = null;
        this.type = null;
        this.endUserToken = null;
        this.endUserName = null;
        this.applicationName = null;
        setValidationStatusIsSet(false);
        this.validationStatus = 0;
        this.applicationId = null;
        this.applicationTier = null;
        this.apiName = null;
        this.consumerKey = null;
        this.apiPublisher = null;
    }

    public boolean isAuthorized() {
        return this.authorized;
    }

    public APIKeyValidationInfoDTO setAuthorized(boolean authorized) {
        this.authorized = authorized;
        setAuthorizedIsSet(true);
        return this;
    }

    public void unsetAuthorized() {
        __isset_bit_vector.clear(__AUTHORIZED_ISSET_ID);
    }

    /** Returns true if field authorized is set (has been assigned a value) and false otherwise */
    public boolean isSetAuthorized() {
        return __isset_bit_vector.get(__AUTHORIZED_ISSET_ID);
    }

    public void setAuthorizedIsSet(boolean value) {
        __isset_bit_vector.set(__AUTHORIZED_ISSET_ID, value);
    }

    public String getSubscriber() {
        return this.subscriber;
    }

    public APIKeyValidationInfoDTO setSubscriber(String subscriber) {
        this.subscriber = subscriber;
        return this;
    }

    public void unsetSubscriber() {
        this.subscriber = null;
    }

    /** Returns true if field subscriber is set (has been assigned a value) and false otherwise */
    public boolean isSetSubscriber() {
        return this.subscriber != null;
    }

    public void setSubscriberIsSet(boolean value) {
        if (!value) {
            this.subscriber = null;
        }
    }

    public String getTier() {
        return this.tier;
    }

    public APIKeyValidationInfoDTO setTier(String tier) {
        this.tier = tier;
        return this;
    }

    public void unsetTier() {
        this.tier = null;
    }

    /** Returns true if field tier is set (has been assigned a value) and false otherwise */
    public boolean isSetTier() {
        return this.tier != null;
    }

    public void setTierIsSet(boolean value) {
        if (!value) {
            this.tier = null;
        }
    }

    public String getType() {
        return this.type;
    }

    public APIKeyValidationInfoDTO setType(String type) {
        this.type = type;
        return this;
    }

    public void unsetType() {
        this.type = null;
    }

    /** Returns true if field type is set (has been assigned a value) and false otherwise */
    public boolean isSetType() {
        return this.type != null;
    }

    public void setTypeIsSet(boolean value) {
        if (!value) {
            this.type = null;
        }
    }

    public String getEndUserToken() {
        return this.endUserToken;
    }

    public APIKeyValidationInfoDTO setEndUserToken(String endUserToken) {
        this.endUserToken = endUserToken;
        return this;
    }

    public void unsetEndUserToken() {
        this.endUserToken = null;
    }

    /** Returns true if field endUserToken is set (has been assigned a value) and false otherwise */
    public boolean isSetEndUserToken() {
        return this.endUserToken != null;
    }

    public void setEndUserTokenIsSet(boolean value) {
        if (!value) {
            this.endUserToken = null;
        }
    }

    public String getEndUserName() {
        return this.endUserName;
    }

    public APIKeyValidationInfoDTO setEndUserName(String endUserName) {
        this.endUserName = endUserName;
        return this;
    }

    public void unsetEndUserName() {
        this.endUserName = null;
    }

    /** Returns true if field endUserName is set (has been assigned a value) and false otherwise */
    public boolean isSetEndUserName() {
        return this.endUserName != null;
    }

    public void setEndUserNameIsSet(boolean value) {
        if (!value) {
            this.endUserName = null;
        }
    }

    public String getApplicationName() {
        return this.applicationName;
    }

    public APIKeyValidationInfoDTO setApplicationName(String applicationName) {
        this.applicationName = applicationName;
        return this;
    }

    public void unsetApplicationName() {
        this.applicationName = null;
    }

    /** Returns true if field applicationName is set (has been assigned a value) and false otherwise */
    public boolean isSetApplicationName() {
        return this.applicationName != null;
    }

    public void setApplicationNameIsSet(boolean value) {
        if (!value) {
            this.applicationName = null;
        }
    }

    public int getValidationStatus() {
        return this.validationStatus;
    }

    public APIKeyValidationInfoDTO setValidationStatus(int validationStatus) {
        this.validationStatus = validationStatus;
        setValidationStatusIsSet(true);
        return this;
    }

    public void unsetValidationStatus() {
        __isset_bit_vector.clear(__VALIDATIONSTATUS_ISSET_ID);
    }

    /** Returns true if field validationStatus is set (has been assigned a value) and false otherwise */
    public boolean isSetValidationStatus() {
        return __isset_bit_vector.get(__VALIDATIONSTATUS_ISSET_ID);
    }

    public void setValidationStatusIsSet(boolean value) {
        __isset_bit_vector.set(__VALIDATIONSTATUS_ISSET_ID, value);
    }

    public String getApplicationId() {
        return this.applicationId;
    }

    public APIKeyValidationInfoDTO setApplicationId(String applicationId) {
        this.applicationId = applicationId;
        return this;
    }

    public void unsetApplicationId() {
        this.applicationId = null;
    }

    /** Returns true if field applicationId is set (has been assigned a value) and false otherwise */
    public boolean isSetApplicationId() {
        return this.applicationId != null;
    }

    public void setApplicationIdIsSet(boolean value) {
        if (!value) {
            this.applicationId = null;
        }
    }

    public String getApplicationTier() {
        return this.applicationTier;
    }

    public APIKeyValidationInfoDTO setApplicationTier(String applicationTier) {
        this.applicationTier = applicationTier;
        return this;
    }

    public void unsetApplicationTier() {
        this.applicationTier = null;
    }

    /** Returns true if field applicationTier is set (has been assigned a value) and false otherwise */
    public boolean isSetApplicationTier() {
        return this.applicationTier != null;
    }

    public void setApplicationTierIsSet(boolean value) {
        if (!value) {
            this.applicationTier = null;
        }
    }

    public String getApiName() {
        return this.apiName;
    }

    public APIKeyValidationInfoDTO setApiName(String apiName) {
        this.apiName = apiName;
        return this;
    }

    public void unsetApiName() {
        this.apiName = null;
    }

    /** Returns true if field apiName is set (has been assigned a value) and false otherwise */
    public boolean isSetApiName() {
        return this.apiName != null;
    }

    public void setApiNameIsSet(boolean value) {
        if (!value) {
            this.apiName = null;
        }
    }

    public String getConsumerKey() {
        return this.consumerKey;
    }

    public APIKeyValidationInfoDTO setConsumerKey(String consumerKey) {
        this.consumerKey = consumerKey;
        return this;
    }

    public void unsetConsumerKey() {
        this.consumerKey = null;
    }

    /** Returns true if field consumerKey is set (has been assigned a value) and false otherwise */
    public boolean isSetConsumerKey() {
        return this.consumerKey != null;
    }

    public void setConsumerKeyIsSet(boolean value) {
        if (!value) {
            this.consumerKey = null;
        }
    }

    public String getApiPublisher() {
        return this.apiPublisher;
    }

    public APIKeyValidationInfoDTO setApiPublisher(String apiPublisher) {
        this.apiPublisher = apiPublisher;
        return this;
    }

    public void unsetApiPublisher() {
        this.apiPublisher = null;
    }

    /** Returns true if field apiPublisher is set (has been assigned a value) and false otherwise */
    public boolean isSetApiPublisher() {
        return this.apiPublisher != null;
    }

    public void setApiPublisherIsSet(boolean value) {
        if (!value) {
            this.apiPublisher = null;
        }
    }

    public void setFieldValue(_Fields field, Object value) {
        switch (field) {
            case AUTHORIZED:
                if (value == null) {
                    unsetAuthorized();
                } else {
                    setAuthorized((Boolean)value);
                }
                break;

            case SUBSCRIBER:
                if (value == null) {
                    unsetSubscriber();
                } else {
                    setSubscriber((String)value);
                }
                break;

            case TIER:
                if (value == null) {
                    unsetTier();
                } else {
                    setTier((String)value);
                }
                break;

            case TYPE:
                if (value == null) {
                    unsetType();
                } else {
                    setType((String)value);
                }
                break;

            case END_USER_TOKEN:
                if (value == null) {
                    unsetEndUserToken();
                } else {
                    setEndUserToken((String)value);
                }
                break;

            case END_USER_NAME:
                if (value == null) {
                    unsetEndUserName();
                } else {
                    setEndUserName((String)value);
                }
                break;

            case APPLICATION_NAME:
                if (value == null) {
                    unsetApplicationName();
                } else {
                    setApplicationName((String)value);
                }
                break;

            case VALIDATION_STATUS:
                if (value == null) {
                    unsetValidationStatus();
                } else {
                    setValidationStatus((Integer)value);
                }
                break;

            case APPLICATION_ID:
                if (value == null) {
                    unsetApplicationId();
                } else {
                    setApplicationId((String)value);
                }
                break;

            case APPLICATION_TIER:
                if (value == null) {
                    unsetApplicationTier();
                } else {
                    setApplicationTier((String)value);
                }
                break;

            case API_NAME:
                if (value == null) {
                    unsetApiName();
                } else {
                    setApiName((String)value);
                }
                break;

            case CONSUMER_KEY:
                if (value == null) {
                    unsetConsumerKey();
                } else {
                    setConsumerKey((String)value);
                }
                break;

            case API_PUBLISHER:
                if (value == null) {
                    unsetApiPublisher();
                } else {
                    setApiPublisher((String)value);
                }
                break;

        }
    }

    public Object getFieldValue(_Fields field) {
        switch (field) {
            case AUTHORIZED:
                return Boolean.valueOf(isAuthorized());

            case SUBSCRIBER:
                return getSubscriber();

            case TIER:
                return getTier();

            case TYPE:
                return getType();

            case END_USER_TOKEN:
                return getEndUserToken();

            case END_USER_NAME:
                return getEndUserName();

            case APPLICATION_NAME:
                return getApplicationName();

            case VALIDATION_STATUS:
                return Integer.valueOf(getValidationStatus());

            case APPLICATION_ID:
                return getApplicationId();

            case APPLICATION_TIER:
                return getApplicationTier();

            case API_NAME:
                return getApiName();

            case CONSUMER_KEY:
                return getConsumerKey();

            case API_PUBLISHER:
                return getApiPublisher();

        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case AUTHORIZED:
                return isSetAuthorized();
            case SUBSCRIBER:
                return isSetSubscriber();
            case TIER:
                return isSetTier();
            case TYPE:
                return isSetType();
            case END_USER_TOKEN:
                return isSetEndUserToken();
            case END_USER_NAME:
                return isSetEndUserName();
            case APPLICATION_NAME:
                return isSetApplicationName();
            case VALIDATION_STATUS:
                return isSetValidationStatus();
            case APPLICATION_ID:
                return isSetApplicationId();
            case APPLICATION_TIER:
                return isSetApplicationTier();
            case API_NAME:
                return isSetApiName();
            case CONSUMER_KEY:
                return isSetConsumerKey();
            case API_PUBLISHER:
                return isSetApiPublisher();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
        if (that == null)
            return false;
        if (that instanceof APIKeyValidationInfoDTO)
            return this.equals((APIKeyValidationInfoDTO)that);
        return false;
    }

    public boolean equals(APIKeyValidationInfoDTO that) {
        if (that == null)
            return false;

        boolean this_present_authorized = true && this.isSetAuthorized();
        boolean that_present_authorized = true && that.isSetAuthorized();
        if (this_present_authorized || that_present_authorized) {
            if (!(this_present_authorized && that_present_authorized))
                return false;
            if (this.authorized != that.authorized)
                return false;
        }

        boolean this_present_subscriber = true && this.isSetSubscriber();
        boolean that_present_subscriber = true && that.isSetSubscriber();
        if (this_present_subscriber || that_present_subscriber) {
            if (!(this_present_subscriber && that_present_subscriber))
                return false;
            if (!this.subscriber.equals(that.subscriber))
                return false;
        }

        boolean this_present_tier = true && this.isSetTier();
        boolean that_present_tier = true && that.isSetTier();
        if (this_present_tier || that_present_tier) {
            if (!(this_present_tier && that_present_tier))
                return false;
            if (!this.tier.equals(that.tier))
                return false;
        }

        boolean this_present_type = true && this.isSetType();
        boolean that_present_type = true && that.isSetType();
        if (this_present_type || that_present_type) {
            if (!(this_present_type && that_present_type))
                return false;
            if (!this.type.equals(that.type))
                return false;
        }

        boolean this_present_endUserToken = true && this.isSetEndUserToken();
        boolean that_present_endUserToken = true && that.isSetEndUserToken();
        if (this_present_endUserToken || that_present_endUserToken) {
            if (!(this_present_endUserToken && that_present_endUserToken))
                return false;
            if (!this.endUserToken.equals(that.endUserToken))
                return false;
        }

        boolean this_present_endUserName = true && this.isSetEndUserName();
        boolean that_present_endUserName = true && that.isSetEndUserName();
        if (this_present_endUserName || that_present_endUserName) {
            if (!(this_present_endUserName && that_present_endUserName))
                return false;
            if (!this.endUserName.equals(that.endUserName))
                return false;
        }

        boolean this_present_applicationName = true && this.isSetApplicationName();
        boolean that_present_applicationName = true && that.isSetApplicationName();
        if (this_present_applicationName || that_present_applicationName) {
            if (!(this_present_applicationName && that_present_applicationName))
                return false;
            if (!this.applicationName.equals(that.applicationName))
                return false;
        }

        boolean this_present_validationStatus = true && this.isSetValidationStatus();
        boolean that_present_validationStatus = true && that.isSetValidationStatus();
        if (this_present_validationStatus || that_present_validationStatus) {
            if (!(this_present_validationStatus && that_present_validationStatus))
                return false;
            if (this.validationStatus != that.validationStatus)
                return false;
        }

        boolean this_present_applicationId = true && this.isSetApplicationId();
        boolean that_present_applicationId = true && that.isSetApplicationId();
        if (this_present_applicationId || that_present_applicationId) {
            if (!(this_present_applicationId && that_present_applicationId))
                return false;
            if (!this.applicationId.equals(that.applicationId))
                return false;
        }

        boolean this_present_applicationTier = true && this.isSetApplicationTier();
        boolean that_present_applicationTier = true && that.isSetApplicationTier();
        if (this_present_applicationTier || that_present_applicationTier) {
            if (!(this_present_applicationTier && that_present_applicationTier))
                return false;
            if (!this.applicationTier.equals(that.applicationTier))
                return false;
        }

        boolean this_present_apiName = true && this.isSetApiName();
        boolean that_present_apiName = true && that.isSetApiName();
        if (this_present_apiName || that_present_apiName) {
            if (!(this_present_apiName && that_present_apiName))
                return false;
            if (!this.apiName.equals(that.apiName))
                return false;
        }

        boolean this_present_consumerKey = true && this.isSetConsumerKey();
        boolean that_present_consumerKey = true && that.isSetConsumerKey();
        if (this_present_consumerKey || that_present_consumerKey) {
            if (!(this_present_consumerKey && that_present_consumerKey))
                return false;
            if (!this.consumerKey.equals(that.consumerKey))
                return false;
        }

        boolean this_present_apiPublisher = true && this.isSetApiPublisher();
        boolean that_present_apiPublisher = true && that.isSetApiPublisher();
        if (this_present_apiPublisher || that_present_apiPublisher) {
            if (!(this_present_apiPublisher && that_present_apiPublisher))
                return false;
            if (!this.apiPublisher.equals(that.apiPublisher))
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        return 0;
    }

    public int compareTo(APIKeyValidationInfoDTO other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;
        APIKeyValidationInfoDTO typedOther = (APIKeyValidationInfoDTO)other;

        lastComparison = Boolean.valueOf(isSetAuthorized()).compareTo(typedOther.isSetAuthorized());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetAuthorized()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.authorized, typedOther.authorized);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetSubscriber()).compareTo(typedOther.isSetSubscriber());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetSubscriber()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.subscriber, typedOther.subscriber);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetTier()).compareTo(typedOther.isSetTier());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTier()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tier, typedOther.tier);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetType()).compareTo(typedOther.isSetType());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetType()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, typedOther.type);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetEndUserToken()).compareTo(typedOther.isSetEndUserToken());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetEndUserToken()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endUserToken, typedOther.endUserToken);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetEndUserName()).compareTo(typedOther.isSetEndUserName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetEndUserName()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endUserName, typedOther.endUserName);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetApplicationName()).compareTo(typedOther.isSetApplicationName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetApplicationName()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.applicationName, typedOther.applicationName);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetValidationStatus()).compareTo(typedOther.isSetValidationStatus());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetValidationStatus()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.validationStatus, typedOther.validationStatus);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetApplicationId()).compareTo(typedOther.isSetApplicationId());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetApplicationId()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.applicationId, typedOther.applicationId);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetApplicationTier()).compareTo(typedOther.isSetApplicationTier());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetApplicationTier()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.applicationTier, typedOther.applicationTier);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetApiName()).compareTo(typedOther.isSetApiName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetApiName()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.apiName, typedOther.apiName);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetConsumerKey()).compareTo(typedOther.isSetConsumerKey());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetConsumerKey()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.consumerKey, typedOther.consumerKey);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.valueOf(isSetApiPublisher()).compareTo(typedOther.isSetApiPublisher());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetApiPublisher()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.apiPublisher, typedOther.apiPublisher);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField field;
        iprot.readStructBegin();
        while (true)
        {
            field = iprot.readFieldBegin();
            if (field.type == org.apache.thrift.protocol.TType.STOP) {
                break;
            }
            switch (field.id) {
                case 1: // AUTHORIZED
                    if (field.type == org.apache.thrift.protocol.TType.BOOL) {
                        this.authorized = iprot.readBool();
                        setAuthorizedIsSet(true);
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 2: // SUBSCRIBER
                    if (field.type == org.apache.thrift.protocol.TType.STRING) {
                        this.subscriber = iprot.readString();
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 3: // TIER
                    if (field.type == org.apache.thrift.protocol.TType.STRING) {
                        this.tier = iprot.readString();
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 4: // TYPE
                    if (field.type == org.apache.thrift.protocol.TType.STRING) {
                        this.type = iprot.readString();
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 5: // END_USER_TOKEN
                    if (field.type == org.apache.thrift.protocol.TType.STRING) {
                        this.endUserToken = iprot.readString();
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 6: // END_USER_NAME
                    if (field.type == org.apache.thrift.protocol.TType.STRING) {
                        this.endUserName = iprot.readString();
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 7: // APPLICATION_NAME
                    if (field.type == org.apache.thrift.protocol.TType.STRING) {
                        this.applicationName = iprot.readString();
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 8: // VALIDATION_STATUS
                    if (field.type == org.apache.thrift.protocol.TType.I32) {
                        this.validationStatus = iprot.readI32();
                        setValidationStatusIsSet(true);
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 9: // APPLICATION_ID
                    if (field.type == org.apache.thrift.protocol.TType.STRING) {
                        this.applicationId = iprot.readString();
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 10: // APPLICATION_TIER
                    if (field.type == org.apache.thrift.protocol.TType.STRING) {
                        this.applicationTier = iprot.readString();
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 11: // API_NAME
                    if (field.type == org.apache.thrift.protocol.TType.STRING) {
                        this.apiName = iprot.readString();
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 12: // CONSUMER_KEY
                    if (field.type == org.apache.thrift.protocol.TType.STRING) {
                        this.consumerKey = iprot.readString();
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                case 13: // API_PUBLISHER
                    if (field.type == org.apache.thrift.protocol.TType.STRING) {
                        this.apiPublisher = iprot.readString();
                    } else {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                default:
                    org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            }
            iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (isSetAuthorized()) {
            oprot.writeFieldBegin(AUTHORIZED_FIELD_DESC);
            oprot.writeBool(this.authorized);
            oprot.writeFieldEnd();
        }
        if (this.subscriber != null) {
            if (isSetSubscriber()) {
                oprot.writeFieldBegin(SUBSCRIBER_FIELD_DESC);
                oprot.writeString(this.subscriber);
                oprot.writeFieldEnd();
            }
        }
        if (this.tier != null) {
            if (isSetTier()) {
                oprot.writeFieldBegin(TIER_FIELD_DESC);
                oprot.writeString(this.tier);
                oprot.writeFieldEnd();
            }
        }
        if (this.type != null) {
            if (isSetType()) {
                oprot.writeFieldBegin(TYPE_FIELD_DESC);
                oprot.writeString(this.type);
                oprot.writeFieldEnd();
            }
        }
        if (this.endUserToken != null) {
            if (isSetEndUserToken()) {
                oprot.writeFieldBegin(END_USER_TOKEN_FIELD_DESC);
                oprot.writeString(this.endUserToken);
                oprot.writeFieldEnd();
            }
        }
        if (this.endUserName != null) {
            if (isSetEndUserName()) {
                oprot.writeFieldBegin(END_USER_NAME_FIELD_DESC);
                oprot.writeString(this.endUserName);
                oprot.writeFieldEnd();
            }
        }
        if (this.applicationName != null) {
            if (isSetApplicationName()) {
                oprot.writeFieldBegin(APPLICATION_NAME_FIELD_DESC);
                oprot.writeString(this.applicationName);
                oprot.writeFieldEnd();
            }
        }
        if (isSetValidationStatus()) {
            oprot.writeFieldBegin(VALIDATION_STATUS_FIELD_DESC);
            oprot.writeI32(this.validationStatus);
            oprot.writeFieldEnd();
        }
        if (this.applicationId != null) {
            if (isSetApplicationId()) {
                oprot.writeFieldBegin(APPLICATION_ID_FIELD_DESC);
                oprot.writeString(this.applicationId);
                oprot.writeFieldEnd();
            }
        }
        if (this.applicationTier != null) {
            if (isSetApplicationTier()) {
                oprot.writeFieldBegin(APPLICATION_TIER_FIELD_DESC);
                oprot.writeString(this.applicationTier);
                oprot.writeFieldEnd();
            }
        }
        if (this.apiName != null) {
            if (isSetApiName()) {
                oprot.writeFieldBegin(API_NAME_FIELD_DESC);
                oprot.writeString(this.apiName);
                oprot.writeFieldEnd();
            }
        }
        if (this.consumerKey != null) {
            if (isSetConsumerKey()) {
                oprot.writeFieldBegin(CONSUMER_KEY_FIELD_DESC);
                oprot.writeString(this.consumerKey);
                oprot.writeFieldEnd();
            }
        }
        if (this.apiPublisher != null) {
            if (isSetApiPublisher()) {
                oprot.writeFieldBegin(API_PUBLISHER_FIELD_DESC);
                oprot.writeString(this.apiPublisher);
                oprot.writeFieldEnd();
            }
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("APIKeyValidationInfoDTO(");
        boolean first = true;

        if (isSetAuthorized()) {
            sb.append("authorized:");
            sb.append(this.authorized);
            first = false;
        }
        if (isSetSubscriber()) {
            if (!first) sb.append(", ");
            sb.append("subscriber:");
            if (this.subscriber == null) {
                sb.append("null");
            } else {
                sb.append(this.subscriber);
            }
            first = false;
        }
        if (isSetTier()) {
            if (!first) sb.append(", ");
            sb.append("tier:");
            if (this.tier == null) {
                sb.append("null");
            } else {
                sb.append(this.tier);
            }
            first = false;
        }
        if (isSetType()) {
            if (!first) sb.append(", ");
            sb.append("type:");
            if (this.type == null) {
                sb.append("null");
            } else {
                sb.append(this.type);
            }
            first = false;
        }
        if (isSetEndUserToken()) {
            if (!first) sb.append(", ");
            sb.append("endUserToken:");
            if (this.endUserToken == null) {
                sb.append("null");
            } else {
                sb.append(this.endUserToken);
            }
            first = false;
        }
        if (isSetEndUserName()) {
            if (!first) sb.append(", ");
            sb.append("endUserName:");
            if (this.endUserName == null) {
                sb.append("null");
            } else {
                sb.append(this.endUserName);
            }
            first = false;
        }
        if (isSetApplicationName()) {
            if (!first) sb.append(", ");
            sb.append("applicationName:");
            if (this.applicationName == null) {
                sb.append("null");
            } else {
                sb.append(this.applicationName);
            }
            first = false;
        }
        if (isSetValidationStatus()) {
            if (!first) sb.append(", ");
            sb.append("validationStatus:");
            sb.append(this.validationStatus);
            first = false;
        }
        if (isSetApplicationId()) {
            if (!first) sb.append(", ");
            sb.append("applicationId:");
            if (this.applicationId == null) {
                sb.append("null");
            } else {
                sb.append(this.applicationId);
            }
            first = false;
        }
        if (isSetApplicationTier()) {
            if (!first) sb.append(", ");
            sb.append("applicationTier:");
            if (this.applicationTier == null) {
                sb.append("null");
            } else {
                sb.append(this.applicationTier);
            }
            first = false;
        }
        if (isSetApiName()) {
            if (!first) sb.append(", ");
            sb.append("apiName:");
            if (this.apiName == null) {
                sb.append("null");
            } else {
                sb.append(this.apiName);
            }
            first = false;
        }
        if (isSetConsumerKey()) {
            if (!first) sb.append(", ");
            sb.append("consumerKey:");
            if (this.consumerKey == null) {
                sb.append("null");
            } else {
                sb.append(this.consumerKey);
            }
            first = false;
        }
        if (isSetApiPublisher()) {
            if (!first) sb.append(", ");
            sb.append("apiPublisher:");
            if (this.apiPublisher == null) {
                sb.append("null");
            } else {
                sb.append(this.apiPublisher);
            }
            first = false;
        }
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bit_vector = new BitSet(1);
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

}
