
CREATE TABLE LC_DEFINITIONS(
            LC_ID INTEGER NOT NULL,
            LC_NAME VARCHAR(255),
            LC_CONTENT BLOB,
            UNIQUE (LC_ID),
            PRIMARY KEY (LC_NAME)
)
/
CREATE SEQUENCE LC_DEFINITIONS_SEQUENCE START WITH 1 INCREMENT BY 1 CACHE 20 ORDER
/
CREATE OR REPLACE TRIGGER LC_DEFINITIONS_TRIGGER
                    BEFORE INSERT
                    ON LC_DEFINITIONS
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                     BEGIN
                       SELECT LC_DEFINITIONS_SEQUENCE.nextval INTO :NEW.LC_ID FROM dual;
 			   END;
/

CREATE TABLE LC_DATA(
            LC_STATE_ID VARCHAR(36) NOT NULL,
            LC_DEFINITION_ID INTEGER ,
            LC_STATUS VARCHAR(255),
            PRIMARY KEY (LC_STATE_ID),
            FOREIGN KEY (LC_DEFINITION_ID) REFERENCES LC_DEFINITIONS(LC_ID) ON DELETE CASCADE
)
/

CREATE TABLE LC_HISTORY(
            LC_ID INTEGER ,
            LC_STATE_ID VARCHAR(36),
            PREVIOUS_STATE VARCHAR(255),
            POST_STATE VARCHAR(255),
            USERNAME VARCHAR(255),
            UPDATED_TIME TIMESTAMP,
            UNIQUE (LC_ID)
)

/
CREATE SEQUENCE LC_HISTORY_SEQUENCE START WITH 1 INCREMENT BY CACHE 20 ORDER
/
CREATE OR REPLACE TRIGGER LC_HISTORY_TRIGGER
                    BEFORE INSERT
                    ON LC_HISTORY
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                     BEGIN
                       SELECT LC_HISTORY_SEQUENCE.nextval INTO :NEW.LC_ID FROM dual;
 			   END;
/
