--- Start of lifecycle tables ---

CREATE TABLE IF NOT EXISTS LC_DEFINITIONS(
            ID INTEGER NOT NULL AUTO_INCREMENT,
            LC_NAME VARCHAR(255),
            LC_CONTENT LONGBLOB,
            LC_TENANT_ID INTEGER DEFAULT 0,
            UNIQUE (ID),
            PRIMARY KEY (LC_NAME, LC_TENANT_ID)
);

CREATE TABLE IF NOT EXISTS LC_DATA(
            LC_STATE_ID VARCHAR(36),
            LC_DEFINITION_ID INTEGER ,
            LC_STATUS VARCHAR(255),
            LC_TENANT_ID INTEGER DEFAULT 0,
            UNIQUE (LC_STATE_ID),
            PRIMARY KEY (LC_STATE_ID, LC_TENANT_ID),
            FOREIGN KEY (LC_DEFINITION_ID) REFERENCES LC_DEFINITIONS(ID)ON DELETE CASCADE
);