
CREATE SEQUENCE LC_DEFINITIONS_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS LC_DEFINITIONS(
            LC_ID INTEGER DEFAULT nextval('lc_definitions_sequence'),
            LC_NAME VARCHAR(255),
            LC_CONTENT BYTEA,
            UNIQUE (LC_ID),
            PRIMARY KEY (LC_NAME)
);

CREATE TABLE IF NOT EXISTS LC_DATA(
            LC_STATE_ID VARCHAR(36) NOT NULL ,
            LC_DEFINITION_ID INTEGER ,
            LC_STATUS VARCHAR(255),
            UNIQUE (LC_STATE_ID),
            PRIMARY KEY (LC_STATE_ID),
            FOREIGN KEY (LC_DEFINITION_ID) REFERENCES LC_DEFINITIONS(LC_ID) ON DELETE CASCADE
);

CREATE SEQUENCE LC_HISTORY_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS LC_HISTORY(
            LC_ID INTEGER DEFAULT nextval('lc_history_sequence'),
            LC_STATE_ID VARCHAR(36),
            PREVIOUS_STATE VARCHAR(255),
            POST_STATE VARCHAR(255),
            USERNAME VARCHAR(255),
            UPDATED_TIME TIMESTAMP,
            UNIQUE (LC_ID)
);
