theme : "org.wso2.carbon.uuf.common.default.theme"

menus:
  - name: "main"
    items:
      - text: "APIs"
        link: "/apis"
        icon: "fw-home"
      - text: "Applications"
        link: ""
        icon: "fw-home"
  - name: "left"
    items:
      - text: "APIs"
        link: ""
        icon: "fw-home"
errorPages:
  "404": /foundation/error/404
  default: /foundation/error/default