CREATE TABLE `AM_API` (
  `API_ID` INTEGER AUTO_INCREMENT,
  `PROVIDER` VARCHAR(255),
  `NAME` VARCHAR(255),
  `CONTEXT` VARCHAR(255),
  `VERSION` VARCHAR(30),
  `IS_DEFAULT_VERSION` BOOLEAN,
  `DESCRIPTION` VARCHAR(1024),
  `VISIBILITY` VARCHAR(30),
  `IS_RESPONSE_CACHED` BOOLEAN,
  `CACHE_TIMEOUT` INTEGER,
  `UUID` VARCHAR(255),
  `TECHNICAL_OWNER` VARCHAR(255),
  `TECHNICAL_EMAIL` VARCHAR(255),
  `BUSINESS_OWNER` VARCHAR(255),
  `BUSINESS_EMAIL` VARCHAR(255),
  `LIFECYCLE_INSTANCE_ID` VARCHAR(255),
  `CURRENT_LC_STATUS` VARCHAR(255),
  `API_POLICY_ID` INTEGER,
  `CORS_ENABLED` BOOLEAN,
  `CORS_ALLOW_ORIGINS` VARCHAR(512),
  `CORS_ALLOW_CREDENTIALS` BOOLEAN,
  `CORS_ALLOW_HEADERS` VARCHAR(512),
  `CORS_ALLOW_METHODS` VARCHAR(255),
  `CREATED_BY` VARCHAR(100),
  `CREATED_TIME` TIMESTAMP,
  `LAST_UPDATED_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`API_ID`),
  UNIQUE (`PROVIDER`,`NAME`,`VERSION`)
);

CREATE TABLE `AM_HISTORY_AUDIT` (
  `ENTRY_ID` INTEGER AUTO_INCREMENT,
  `TABLE_NAME` VARCHAR(255),
  `ENTITY_ID` INTEGER,
  `ACTION` VARCHAR(30),
  `ACTION_BY` VARCHAR(255),
  `ACTION_TIME` TIMESTAMP,
  PRIMARY KEY (`ENTRY_ID`)
);

CREATE TABLE `AM_API_VISIBLE_ROLES` (
  `API_ID` INTEGER,
  `ROLE` VARCHAR(255),
  PRIMARY KEY (`API_ID`, `ROLE`),
  FOREIGN KEY (`API_ID`) REFERENCES `AM_API`(`API_ID`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `AM_API_TAG_MAPPING` (
  `API_ID` INTEGER,
  `TAG_ID` INTEGER,
  PRIMARY KEY (`API_ID`, `TAG_ID`),
  FOREIGN KEY (`API_ID`) REFERENCES `AM_API`(`API_ID`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `AM_TAGS` (
  `TAG_ID` INTEGER AUTO_INCREMENT,
  `TAG_NAME` VARCHAR(255),
  PRIMARY KEY (`TAG_ID`)
);

CREATE TABLE `AM_API_SUBSCRIPTION_POLICY_MAPPING` (
  `API_ID` INTEGER,
  `POLICY_ID` INTEGER,
  PRIMARY KEY (`API_ID`, `POLICY_ID`),
  FOREIGN KEY (`API_ID`) REFERENCES `AM_API`(`API_ID`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `AM_API_ENDPOINTS` (
  `API_ID` INTEGER,
  `ENVIRONMENT_CATEGORY` VARCHAR(30),
  `ENDPOINT_TYPE` VARCHAR(30),
  `IS_ENDPOINT_SECURED` BOOLEAN,
  `TPS` INTEGER,
  `AUTH_DIGEST` VARCHAR(30),
  `USERNAME` VARCHAR(255),
  `PASSWORD` VARCHAR(255),
  PRIMARY KEY (`API_ID`),
  FOREIGN KEY (`API_ID`) REFERENCES `AM_API`(`API_ID`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `AM_API_SCOPES` (
  `API_ID` INTEGER,
  `SCOPE_ID` INTEGER,
  PRIMARY KEY (`API_ID`, `SCOPE_ID`),
  FOREIGN KEY (`API_ID`) REFERENCES `AM_API`(`API_ID`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `AM_API_URL_MAPPING` (
  `API_ID` INTEGER,
  `HTTP_METHOD` VARCHAR(30),
  `URL_PATTERN` VARCHAR(255),
  `AUTH_SCHEME` VARCHAR(30),
  `API_POLICY_ID` INTEGER,
  PRIMARY KEY (`API_ID`, `HTTP_METHOD`, `URL_PATTERN`),
  FOREIGN KEY (`API_ID`) REFERENCES `AM_API`(`API_ID`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `AM_APPLICATION` (
  `APPLICATION_ID` INTEGER,
  `NAME` VARCHAR(255),
  `SUBSCRIBER_ID` INTEGER,
  `APPLICATION_POLICY_ID` INTEGER,
  `CALLBACK_URL` VARCHAR(512),
  `DESCRIPTION` VARCHAR(1024),
  `APPLICATION_STATUS` VARCHAR(255),
  `GROUP_ID` VARCHAR(255),
  `CREATED_BY` VARCHAR(100),
  `CREATED_TIME` TIMESTAMP,
  `LAST_UPDATED_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `UUID` VARCHAR(255),
  PRIMARY KEY (`APPLICATION_ID`)
);

CREATE TABLE `AM_POLICY_SUBSCRIPTION` (
  `POLICY_ID` INTEGER,
  `NAME` VARCHAR(255),
  `DISPLAY_NAME` VARCHAR(512),
  `DESCRIPTION` VARCHAR(1024),
  `QUOTA_TYPE` VARCHAR(30),
  `QUOTA` INTEGER,
  `QUOTA_UNIT` VARCHAR(30),
  `UNIT_TIME` INTEGER,
  `TIME_UNIT` VARCHAR(30),
  `RATE_LIMIT_COUNT` INTEGER,
  `RATE_LIMIT_TIME_UNIT` VARCHAR(30),
  `IS_DEPLOYED` BOOL,
  `CUSTOM_ATTRIBUTES` BLOB,
  `STOP_ON_QUOTA_REACH` BOOL,
  `BILLING_PLAN` VARCHAR(30),
  `UUID` VARCHAR(255),
  PRIMARY KEY (`POLICY_ID`)
);

CREATE TABLE `AM_APP_KEY_MAPPING` (
  `APPLICATION_ID` INTEGER,
  `CONSUMER_KEY` VARCHAR(255),
  `KEY_TYPE` VARCHAR(255),
  `STATE` VARCHAR(30),
  `CREATE_MODE` VARCHAR(30),
  PRIMARY KEY (`APPLICATION_ID`, `KEY_TYPE`)
);

CREATE TABLE `AM_API_TRANSPORTS` (
  `API_ID` INTEGER,
  `TRANSPORT` VARCHAR(30),
  PRIMARY KEY (`API_ID`)
);

CREATE TABLE `AM_API_ENVIRONMENTS` (
  `API_ID` INTEGER,
  `ENV_NAME` VARCHAR(255),
  `HTTP_URL` VARCHAR(255),
  `HTTPS_URL` VARCHAR(255),
  `APPEND_CONTEXT` BOOLEAN,
  PRIMARY KEY (`API_ID`, `ENV_NAME`),
  FOREIGN KEY (`API_ID`) REFERENCES `AM_API`(`API_ID`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `AM_RESOURCE_TYPES` (
  `RESOURCE_TYPE_ID` INTEGER,
  `RESOURCE_TYPE_NAME` VARCHAR(255),
  PRIMARY KEY (`RESOURCE_TYPE_ID`)
);

CREATE TABLE `AM_API_RESOURCES` (
  `RESOURCE_ID` INTEGER,
  `API_ID` INTEGER,
  `RESOURCE_TYPE_ID` INTEGER,
  `DATA_TYPE` VARCHAR(255),
  `RESOURCE_TEXT_VALUE` VARCHAR(1024),
  `RESOURCE_BINARY_VALUE` BLOB,
  PRIMARY KEY (`RESOURCE_ID`),
  FOREIGN KEY (`API_ID`) REFERENCES `AM_API`(`API_ID`) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (`RESOURCE_TYPE_ID`) REFERENCES `AM_RESOURCE_TYPES`(`RESOURCE_TYPE_ID`) ON UPDATE CASCADE ON DELETE CASCADE
);

