CREATE TABLE IF NOT EXISTS GOV_RULESET (
    RULESET_ID VARCHAR(45) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    RULESET_CONTENT LONGBLOB NOT NULL,
    APPLIES_TO VARCHAR(100) NOT NULL,
    DOCUMENTATION_LINK VARCHAR(1024),
    PROVIDER VARCHAR(200),
    ORGANIZATION VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(255),
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    LAST_UPDATED_TIME DATETIME,
    IS_DEFAULT INT DEFAULT 0,
    CONSTRAINT RULESET_UNIQUE_CONSTRAINT UNIQUE (NAME, ORGANIZATION),
    PRIMARY KEY (RULESET_ID)
) ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS GOV_RULESET_RULE (
    RULESET_RULE_ID VARCHAR(45) NOT NULL,
    RULESET_ID VARCHAR(45) NOT NULL,
    RULE_CODE VARCHAR(200) NOT NULL,
    RULE_MESSAGE VARCHAR(1024),
    RULE_DESCRIPTION VARCHAR(2048),
    SEVERITY INT,
    FOREIGN KEY (RULESET_ID) REFERENCES GOV_RULESET(RULESET_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT RULESET_RULE_UNIQUE_CONSTRAINT UNIQUE (RULESET_ID, RULE_CODE),
    PRIMARY KEY (RULESET_RULE_ID)
) ENGINE=INNODB;
