CREATE TABLE IF NOT EXISTS GOV_RULESET (
    RULESET_ID VARCHAR(45) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    RULESET_CONTENT LONGBLOB NOT NULL,
    ARTIFACT_TYPE VARCHAR(100) NOT NULL,
    RULE_TYPE VARCHAR(100) NOT NULL,
    DOCUMENTATION_LINK VARCHAR(1024),
    PROVIDER VARCHAR(200),
    ORGANIZATION VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(255),
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    LAST_UPDATED_TIME DATETIME,
    CONSTRAINT RULESET_UNIQUE_CONSTRAINT UNIQUE (NAME, ORGANIZATION),
    PRIMARY KEY (RULESET_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_RULESET_RULE (
    RULESET_RULE_ID VARCHAR(45) NOT NULL,
    RULESET_ID VARCHAR(45) NOT NULL,
    RULE_CODE VARCHAR(200) NOT NULL,
    RULE_MESSAGE VARCHAR(1024),
    RULE_DESCRIPTION VARCHAR(2048),
    SEVERITY VARCHAR(45) NOT NULL,
    RULE_CONTENT BLOB NOT NULL,
    FOREIGN KEY (RULESET_ID) REFERENCES GOV_RULESET(RULESET_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT RULESET_RULE_UNIQUE_CONSTRAINT UNIQUE (RULESET_ID, RULE_CODE),
    PRIMARY KEY (RULESET_RULE_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_POLICY (
    POLICY_ID VARCHAR(45) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    ORGANIZATION VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(255),
    CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    LAST_UPDATED_TIME DATETIME,
    CONSTRAINT POLICY_UNIQUE_CONSTRAINT UNIQUE (NAME, ORGANIZATION),
    PRIMARY KEY (POLICY_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_POLICY_LABEL (
    POLICY_LABEL_ID VARCHAR(45) NOT NULL,
    POLICY_ID VARCHAR(45) NOT NULL,
    LABEL VARCHAR(100) NOT NULL,
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT POLICY_LABEL_UNIQUE_CONSTRAINT UNIQUE (POLICY_ID, LABEL),
    PRIMARY KEY (POLICY_LABEL_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_POLICY_GOVERNABLE_STATE (
    POLICY_STATE_ID VARCHAR(45) NOT NULL,
    POLICY_ID VARCHAR(45) NOT NULL,
    STATE VARCHAR(100) NOT NULL,
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT POLICY_STATE_UNIQUE_CONSTRAINT UNIQUE (POLICY_ID, STATE),
    PRIMARY KEY (POLICY_STATE_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_POLICY_ACTION (
    POLICY_ACTION_ID VARCHAR(45) NOT NULL,
    POLICY_ID VARCHAR(45) NOT NULL,
    STATE VARCHAR(100) NOT NULL,
    SEVERITY VARCHAR(45) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (POLICY_ID, STATE) REFERENCES GOV_POLICY_GOVERNABLE_STATE(POLICY_ID, STATE) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT POLICY_ACTION_UNIQUE_CONSTRAINT UNIQUE (POLICY_ID, STATE, SEVERITY, TYPE),
    PRIMARY KEY (POLICY_ACTION_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_POLICY_RULESET_MAPPING (
    POLICY_RULESET_MAPPING_ID VARCHAR(45) NOT NULL,
    POLICY_ID VARCHAR(45) NOT NULL,
    RULESET_ID VARCHAR(45) NOT NULL,
    FOREIGN KEY (POLICY_ID) REFERENCES GOV_POLICY(POLICY_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (RULESET_ID) REFERENCES GOV_RULESET(RULESET_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT POLICY_RULESET_UNIQUE_CONSTRAINT UNIQUE (POLICY_ID, RULESET_ID),
    PRIMARY KEY (POLICY_RULESET_MAPPING_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GOV_EVALUATION_REQUEST (
    REQUEST_ID VARCHAR(45) NOT NULL,
    ARTIFACT_ID VARCHAR(45) NOT NULL,
    ARTIFACT_TYPE VARCHAR(45) NOT NULL,
    POLICY_ID VARCHAR(45) NOT NULL,
    EVALUATION_STATUS VARCHAR(45) NOT NULL DEFAULT 'PENDING',
    ORGANIZATION VARCHAR(100) NOT NULL,
    REQUESTED_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    EVALUATED_TIMESTAMP DATETIME,
    CONSTRAINT EVALUATION_TRACKER_UNIQUE_CONSTRAINT UNIQUE (ARTIFACT_ID, POLICY_ID, EVALUATION_STATUS),
    PRIMARY KEY (REQUEST_ID)
) ENGINE=INNODB;