package org.wso2.carbon.apimgt.impl.portalNotifications;

public enum PortalNotificationType {
    API_STATE_CHANGE,
    API_PRODUCT_STATE_CHANGE,
    API_REVISION_DEPLOYMENT,
    APPLICATION_CREATION,
    SUBSCRIPTION_CREATION,
    SUBSCRIPTION_UPDATE,
    SUBSCRIPTION_DELETION,
    APPLICATION_REGISTRATION_PRODUCTION,
    APPLICATION_REGISTRATION_SANDBOX
}
