--- Start of lifecycle tables ---

CREATE TABLE IF NOT EXISTS LC_DEFINITIONS(
            LC_ID INTEGER NOT NULL AUTO_INCREMENT,
            LC_NAME VARCHAR(255),
            LC_CONTENT LONGBLOB,
            UNIQUE (ID),
            PRIMARY KEY (LC_NAME)
);

CREATE TABLE IF NOT EXISTS LC_DATA(
            LC_STATE_ID VARCHAR(36) NOT NULL ,
            LC_DEFINITION_ID INTEGER ,
            LC_STATUS VARCHAR(255),
            UNIQUE (LC_STATE_ID),
            PRIMARY KEY (LC_STATE_ID),
            FOREIGN KEY (LC_DEFINITION_ID) REFERENCES LC_DEFINITIONS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LC_HISTORY(
            LC_ID INTEGER NOT NULL AUTO_INCREMENT,
            LC_STATE_ID VARCHAR(36),
            PREVIOUS_STATE VARCHAR(255),
            POST_STATE VARCHAR(255),
            USERNAME VARCHAR(255),
            UPDATED_TIME TIMESTAMP,
            UNIQUE (ID)
);