#   Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#---------------------------------------------------------------------------

openapi: "3.0.0"
info:
  title: WSO2 API Manager - Endpoint Registry
  description: |
    This specifies a **RESTful API** for Enpoint Registry.
  version: "1.0"
servers:
  - url: 'https://apis.wso2.com/api/am/endpoint-registry/v1'
  - url: 'http://apis.wso2.com/api/am/endpoint-registry/v1'

paths:
  /registries:
    #-----------------------------------------------------
    # Retrieve the array of all Registries
    #-----------------------------------------------------
    get:
      summary: |
        Retrieve all Registries
      description: |
        This operation provides you an array of available Registries.
      tags:
        - Registries
      security:
        - default:
          - registry:view
      operationId: getRegistries
    #-----------------------------------------------------
    # Create a new Registry
    #-----------------------------------------------------
    post:
      summary: Create a new Registry
      description: |
        This operation can be used to create a new Registry specifying the details of the Registry in the payload.
      security:
        - default:
          - registry:write
      tags:
        - Registries
      operationId: addRegistry
  /registries/{registryId}:
    #-----------------------------------------------------
    # Retrieve the details of a Registry
    #-----------------------------------------------------
    get:
      summary: Get details of a Registry
      description: |
        Using this operation, you can retrieve complete details of a single Registry using the RegistryId.
      security:
        - default:
          - registry:view
      tags:
        - Registries
      operationId: getRegistryByUUID
    #-----------------------------------------------------
    # Update an existing Endpoint Registry
    #-----------------------------------------------------
    put:
      summary: Update an existing Registry
      description: |
        This operation can be used to update an existing Endpoint Registry
      security:
        - default:
          - registry:write
      tags:
        - Registries
      operationId: updateRegistry
    #-----------------------------------------------------
    # Delete an Endpoint Registry
    #-----------------------------------------------------
    delete:
      summary: Delete an Endpoint Registry
      description: |
        This operation can be used to delete an existing Registry proving the Id of the Registry.
      security:
        - default:
          - registry:write
      tags:
       - Registries
      operationId: deleteRegistry
  #-----------------------------------------------------
  # Retrieve all entries in a Registry
  #-----------------------------------------------------
  /registries/{registryId}/entries:
    get:
      summary: Get All entries in the registry
      operationId: getAllEntriesInRegistry
      security:
        - default:
          - registry:entry_view
      tags:
        - Registry Entries
  #-----------------------------------------------------
  # Create new entry in entry in Registry
  #-----------------------------------------------------
  /registries/{registryId}/entry:
    post:
      summary: Create a new Registry Entry
      description: |
        This operation can be used to create a new Registry Entry specifying the details of the Entry in the payload.
      security:
        - default:
          - registry:entry_write
      tags:
        - Registry Entries
      operationId: createRegistryEntry
  /registries/{registryId}/entries/{entryId}:
    #-----------------------------------------------------
    # Retrieve an entry in a Registry
    #-----------------------------------------------------
    get:
      summary: Retrieve a specific Entry in a Registry
      description: |
        Using this operation, you can retrieve a specific entry in a single Registry using the EntryId and RegistryId.
      security:
        - default:
          - registry:entry_view
      operationId: getRegistryEntryByUuid
      tags:
        - Registry Entries
    #-----------------------------------------------------
    # Update an entry in a Registry
    #-----------------------------------------------------
    put:
      summary: Update an existing Entry in a Registry
      description: |
        This operation can be used to update an existing Entry in Registry with the details of the Entry in the payload.
      security:
        - default:
          - registry:entry_write
      operationId: updateRegistryEntry
      tags:
        - Registry Entries
    #-----------------------------------------------------
    # Delete an entry in a Registry
    #-----------------------------------------------------
    delete:
      summary: Delete an Entry in a Registry
      description: |
        This operation can be used to delete an existing Entry in Registry by specifying the registryId and entryId.
      security:
        - default:
          - registry:entry_write
      operationId: deleteRegistryEntry
      tags:
        - Registry Entries
  #-----------------------------------------------------
  # Retrieve definition file of an entry in Registry
  #-----------------------------------------------------
  /registries/{registryId}/entries/{entryId}/definition-file:
    get:
      summary: Retrieve the definition file of a specific Entry in a Registry
      description: |
        Using this operation, you can retrieve the definition file of a specific entry in a Registry using the EntryId and RegistryId.
      security:
        - default:
          - registry:entry_view
      operationId: getEndpointDefinition
      tags:
        - Registry Entries
components:
  #-------------------------------------------------------
  # The security schemes of resources used by some of the APIs
  #-------------------------------------------------------
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://example.com/oauth/authorize
          scopes:
            registry:view: view registry
            registry:write: write registry
            registry:entry_view: view reg entry
            registry:entry_write: write reg entry

  #-------------------------------------------------------
  # The definitions of resources used by some of the APIs
  #-------------------------------------------------------
######################################################
# Parameters - required by some of the APIs above
######################################################