#   Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
################################################################################

swagger: '2.0'
######################################################
# Prolog
######################################################
info:
  version: "v1.2"
  title: "WSO2 API Manager - Admin"
  description: |
    This document specifies a **RESTful API** for WSO2 **API Manager** - Admin Portal.
    Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.5.176/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin/src/main/resources/admin-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification.
  contact:
    name: "WSO2"
    url: "http://wso2.com/products/api-manager/"
    email: "architecture@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

######################################################
# The fixed parts of the URLs of the API
######################################################

# The schemes supported by the API
schemes:
  - https

# The domain of the API.
# This is configured by the customer during deployment.
# The given host is just an example.
host: apis.wso2.com

# The base path of the API.
# Will be prefixed to all paths.
basePath: /api/am/admin/v1

# The following media types can be passed as input in message bodies of the API.
# The actual media type must be specified in the Content-Type header field of the request.
# The default is json, i.e. the Content-Type header is not needed to
# be set, but supporting it serves extensibility.
# The following media types may be passed as output in message bodies of the API.
# The media type(s) consumable by the requestor is specified in the Accept header field
# of the corresponding request.
# The actual media type returned will be specfied in the Content-Type header field
# of the of the response.
# The default of the Accept header is json, i.e. there is not needed to
# set the value, but supporting it serves extensibility.
securityDefinitions:
  OAuth2Security:
    type: oauth2
    flow: password
    tokenUrl: https://localhost:9443/oauth2/token
    scopes:
      openid: Authorize access to user details
      apim:admin: Manage all admin operations
      apim:tier_view: View throttling policies
      apim:tier_manage: Update and delete throttling policies
      apim:bl_view: View deny policies
      apim:bl_manage: Update and delete deny policies
      apim:mediation_policy_view: View mediation policies
      apim:mediation_policy_create: Create and update mediation policies
      apim:app_owner_change: Retrieve and manage applications
      apim:app_import_export: Import and export applications related operations
      apim:api_import_export: Import and export APIs related operations
      apim:api_product_import_export: Import and export API Products related operations
      apim:label_manage: Manage microgateway labels
      apim:label_read: Retrieve microgateway labels
      apim:monetization_usage_publish: Retrieve and publish Monetization related usage records
      apim:api_workflow_approve: Manage workflows
      apim:bot_data: Retrieve bot detection data
      apim:tenantInfo: Retrieve tenant related information
      apim:tenant_theme_manage: Manage tenant themes
      apim:admin_operations: Manage API categories
      apim:admin_settings: Retrieve admin settings
      apim:admin_alert_manage: Manage admin alerts
      apim:api_workflow_view: Retrive workflow requests
      apim:scope_manage: Manage scope

######################################################
# The "API Collection" resource APIs
######################################################
paths:
######################################################
# The "Application Throttling Policy Collection" resource API
######################################################
  '/throttling/policies/application':

#-----------------------------------------------------
# Retrieve all Application level policies
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get all Application Throttling Policies
      description: |
        Retrieves all existing application throttling policies.
      tags:
        - Application Policy (Collection)
#-----------------------------------------------------
# Add a Application level Throttling Policy
#-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Add an Application Throttling Policy
      description: |
        This operation can be used to add a new application level throttling policy.
      tags:
        - Application Policy (Collection)
######################################################
# The "Individual Application Throttling Policy" resource API
######################################################
  '/throttling/policies/application/{policyId}':

#-----------------------------------------------------
# Retrieve a certain Application Policy
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get an Application Policy
      description: |
        Retrieves an Application Policy.
      tags:
        - Application Policy (Individual)
#-----------------------------------------------------
# Delete an Application level throttling policy
#-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Delete an Application Throttling policy
      description: |
        Deletes an Application level throttling policy.
      tags:
        - Application Policy (Individual)
#-----------------------------------------------------
# Update an Application throttling policy
#-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Update an Application Throttling policy
      description: |
        Updates an existing Application level throttling policy. Upon succesfull, you will receive the updated application policy as the response.
      tags:
        - Application Policy (Individual)
  /policies/mediation:
#-----------------------------------------------------------------------------------------
# Retrieving the list of all global mediation sequences under a given search condition
#-----------------------------------------------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:mediation_policy_view
      summary: |
        Get all global mediation policies
      description: |
        This operation provides you a list of available all global level mediation policies.
      tags:
        - Mediation Policy (Collection)
#----------------------------------------------------------------------------
# Upload a global mediation policy
#----------------------------------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:mediation_policy_create
      summary: Add a global mediation policy
      description: |
        This operation can be used to add a new global mediation policy.
      tags:
        - Mediation Policy (Collection)
######################################################
# The "Individual global mediation sequence" resource
######################################################
  /policies/mediation/{mediationPolicyId}:

#-----------------------------------------------------
# Retrieve a particular global mediation policy
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:mediation_policy_view
      summary: Get a global mediation policy
      description: |
        This operation can be used to retrieve a particular global mediation policy.
      tags:
        - Mediation Policy (Individual)
#-----------------------------------------------------
# Delete the mediation policy
#-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:mediation_policy_create
      summary: Delete a global mediation policy
      description: |
        This operation can be used to delete an existing global mediation policy providing the Id of the mediation policy.
      tags:
        - Mediation Policy (Individual)
#-----------------------------------------------------
# Update the a mediation policy
#-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:mediation_policy_create
      summary: Update a global mediation policy
      description: |
        This operation can be used to update an existing global mediation policy.
      tags:
        - Mediation Policy (Individual)
######################################################
# The "Subscription Throttling Policy Collection" resource API
######################################################
  '/throttling/policies/subscription':

#-----------------------------------------------------
# Retrieve all Subscription level policies
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get all Subscription Throttling Policies
      description: |
        This operation can be used to retrieve all Subscription level throttling policies.
      tags:
        - Subscription Policy (Collection)
#-----------------------------------------------------
# Add a Subscription level Throttling Policy
#-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Add a Subscription Throttling Policy
      description: |
        This operation can be used to add a Subscription level throttling policy specifying the details of the policy in the payload.
      tags:
        - Subscription Policy (Collection)
######################################################
# The "Individual Subscription Throttling Policy" resource API
######################################################
  '/throttling/policies/subscription/{policyId}':

#-----------------------------------------------------
# Retrieve a certain Subscription Policy
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get a Subscription Policy
      description: |
        Retrieve a single subscription-level throttling policy. We should provide the Id of the policy as a path parameter.
      tags:
        - Subscription Policy (Individual)
#-----------------------------------------------------
# Delete a Subscription level throttling policy
#-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Delete a Subscription Policy
      description: |
        This operation can be used to delete a subscription-level throttling policy specifying the Id of the policy as a path paramter.
      tags:
        - Subscription Policy (Individual)
#-----------------------------------------------------
# Update a Subscription Throttling Policy
#-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Update a Subscription Policy
      description: |
        Updates an existing subscription-level throttling policy.
      tags:
        - Subscription Policy (Individual)
######################################################
# The "Custom Rule Collection" resource API
######################################################
  '/throttling/policies/custom':

#-----------------------------------------------------
# Retrieve all Custom Rules
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get all Custom Rules
      description: |
        Retrieves all Custom Rules.

        **NOTE:**
        * Only super tenant users are allowed for this operation.
      tags:
        - Custom Rules (Collection)
#-----------------------------------------------------
# Add a Custom Rule
#-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Add a Custom Rule
      description: |
        Adds a new Custom Rule.

        **NOTE:**
        * Only super tenant users are allowed for this operation.
      tags:
        - Custom Rules (Collection)
######################################################
# The "Individual Custom Rule" resource API
######################################################
  '/throttling/policies/custom/{ruleId}':

#-----------------------------------------------------
# Retrieve a certain Custom Rule
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get a Custom Rule
      description: |
        Retrieves a Custom Rule. We need to provide the policy Id as a path parameter.

        **NOTE:**
        * Only super tenant users are allowed for this operation.
      tags:
        - Custom Rules (Individual)
#-----------------------------------------------------
# Delete a Custom Rule
#-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Delete a Custom Rule
      description: |
        Delete a Custom Rule. We need to provide the Id of the policy as a path parameter.

        **NOTE:**
        * Only super tenant users are allowed for this operation.
      tags:
        - Custom Rules (Individual)
#-----------------------------------------------------
# Update a Custom Rule
#-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Update a Custom Rule
      description: |
        Updates an existing Custom Rule.

        **NOTE:**
        * Only super tenant users are allowed for this operation.
      tags:
        - Custom Rules (Individual)
######################################################
# The "Advanced Throttling Policy Collection" resource API
######################################################
  '/throttling/policies/advanced':

#-----------------------------------------------------
# Retrieve all Advanced level policies
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get all Advanced throttling policies.
      description: |
        Retrieves all existing Advanced level throttling policies.
      tags:
        - Advanced Policy (Collection)
#-----------------------------------------------------
# Add an Advanced level throttling policy
#-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Add an Advanced Throttling Policy
      description: |
        Add a new Advanced level throttling policy.
      tags:
        - Advanced Policy (Collection)
######################################################
# The "Individual Advanced Throttling Policy" resource API
######################################################
  '/throttling/policies/advanced/{policyId}':

#-----------------------------------------------------
# Retrieve a certain Advanced Throttling Policy
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get an Advanced Policy
      description: |
        Retrieves an Advanced Policy.
      tags:
        - Advanced Policy (Individual)
#-----------------------------------------------------
# Delete an Advanced level throttling policy
#-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Delete an Advanced Throttling Policy
      description: |
        Deletes an Advanced level throttling policy.
      tags:
        - Advanced Policy (Individual)
#-----------------------------------------------------
# Update an Advanced Throttling Policy
#-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Update an Advanced Throttling Policy
      description: |
        Updates an existing Advanced level throttling policy.
      tags:
        - Advanced Policy (Individual)
######################################################
# The "Blocking Condition Collection" resource API
######################################################
  '/throttling/blacklist':

#-----------------------------------------------------
# Retrieve all Blocking conditions
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bl_view
      summary: Get all blocking condtions
      description: |
        Retrieves all existing blocking condtions.
      tags:
        - Blacklist (Collection)
#-----------------------------------------------------
# Add a Blocking condition
#-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bl_manage
      summary: Add a Blocking condition
      description: |
        Adds a new Blocking condition.
      tags:
        - Blacklist (Collection)
######################################################
# The "Individual Blocking Condition" resource API
######################################################
  '/throttling/blacklist/{conditionId}':

#-----------------------------------------------------
# Retrieve a Blocking condition
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bl_view
      summary: Get a Blocking Condition
      description: |
        Retrieves a Blocking Condition providing the condition Id
      tags:
        - Blacklist (Individual)
#-----------------------------------------------------
# Delete a Blocking condition
#-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bl_manage
      summary: Delete a Blocking condition
      description: |
        Deletes an existing Blocking condition
      tags:
        - Blacklist (Individual)
#-----------------------------------------------------
# Update a blocking condition status
#-----------------------------------------------------
    patch:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bl_manage
      summary: Update a blocking condition
      description: |
        Update a blocking condition by Id
      tags:
        - Blacklist (Individual)
######################################################
# The "Application Collection" resource APIs
######################################################
  /applications:

#-----------------------------------------------------
# Retrieve a list of all applications of a certain subscriber
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:app_owner_change
            - apim:app_import_export
      x-wso2-request: |
        GET https://localhost:9443/api/am/admin/v1/applications
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" \"https://localhost:9443/api/am/admin/v1/applications\""
      x-wso2-response: "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\n   \"previous\": \"\",\n   \"list\":    [\n            {\n         \"groupId\": \"\",\n         \"owner\": \"admin\",\n           \"applicationId\": \"367a2361-8db5-4140-8133-c6c8dc7fa0c4\",\n         \"status\": \"APPROVED\",\n         \"name\": \"app1\"\n      },\n            {\n         \"groupId\": \"\",\n         \"owner\": \"admin\",\n             \"applicationId\": \"896658a0-b4ee-4535-bbfa-806c894a4015\",\n    [...]"
      summary: |
        Retrieve/Search applications
      description: |
        This operation can be used to retrieve list of applications that is belonged to the given user, If no user
        is provided then the application for the user associated with the provided access token will be returned.
      tags:
        - Application (Collection)
######################################################
# The "Individual Application" resource APIs
######################################################
  /applications/{applicationId}:

    #-----------------------------------------------------
    # Delete a certain application
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:app_import_export
      summary: |
        Remove an application
      description: |
        This operation can be used to remove an application specifying its id.
      tags:
        - Applications
######################################################
# The "Change Owner" Function resource API
######################################################
  /applications/{applicationId}/change-owner:

#-----------------------------------------------------
# Change the owner of an Application
#-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:app_owner_change
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X POST \"https://localhost:9443/api/am/admin/v1/applications/890a4f4d-09eb-4877-a323-57f6ce2ed79b/change-owner?owner=admin\""
      x-wso2-request: |
        POST https://localhost:9443/api/am/admin/v1/apis/change-owner?apiId=890a4f4d-09eb-4877-a323-57f6ce2ed79b&action=Publish
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8
      x-wso2-response: "HTTP/1.1 200 OK"
      summary: Change Application Owner
      description: |
        This operation is used to change the owner of an Application.
        In order to change the owner of an application, we need to pass the new application owner as a query parameter
      tags:
        - Application
######################################################
# Export Application Resource API
######################################################
  /export/applications:

    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:app_import_export
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X GET https://localhost:9443/api/am/admin/v1/export/applications?appName=sampleApp&appOwner=admin > admin_sampleApp.zip"
      x-wso2-request: |
        GET https://localhost:9443/api/am/admin/v1/export/applications?appName=sampleApp&appOwner=admin
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8
      x-wso2-response: "HTTP/1.1 200 OK\n Connection: keep-alive\n  Content-Disposition: attachment; filename=\"exported-application.zip\"\n  Content-Type: application/zip"
      summary: Export an Application
      description: |
        This operation can be used to export the details of a particular Application as a zip file.
      tags:
        - Application (Individual)
######################################################
# Import Application Resource API
######################################################
  /import/applications:

    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:app_import_export
      x-wso2-curl: "curl -k -F \"file=@exported.zip\" -X POST -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/admin/v1/import/applications"
      x-wso2-request: |
        POST https://localhost:9443/api/am/admin/v1/import/applications
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8
      x-wso2-response: "HTTP/1.1 201 Created\nLocation: https://localhost:9443/api/am/admin/v1/applications/c30f3a6e-ffa4-4ae7-afce-224d1f820524\nContent-Type: application/json\n\n{\n   \"groupId\": \"\",\n   \"callbackUrl\": \"http://my.server.com/callback\",\n   \"owner\": \"admin\",\n   \"applicationId\": \"c30f3a6e-ffa4-4ae7-afce-224d1f820524\",\n   \"status\": \"APPROVED\",\n   \"name\": \"sampleapp\" \n}"
      summary: Import an Application
      description: |
        This operation can be used to import an Application.
      tags:
        - Application (Individual)
######################################################
# Import Resource API
######################################################
  /import/api:
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_import_export
      x-wso2-curl: "curl -k -F \"file=@exported.zip\" -X POST -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/admin/v1/import/api?preserveProvider=false&overwrite=false"
      x-wso2-request: |
        POST https://localhost:9443/api/am/admin/v1/import/apis
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8
      x-wso2-response: "HTTP/1.1 200 OK\nAPI imported successfully."
      summary: Import an API
      description: |
        This operation can be used to import an API.
      tags:
        - API (Individual)
######################################################
# Export Resource API
######################################################
  /export/api:
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_import_export
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X GET https://localhost:9443/api/am/admin/v1/export/api?name=PizzaShackAPI&version=1.0.0&providerName=admin > exportAPI.zip"
      x-wso2-request: |
        GET https://localhost:9443/api/am/admin/v1/export/api?name=SampleAPI&version=1.0.0&providerName=admin
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8
      x-wso2-response: "HTTP/1.1 200 OK\n Connection: keep-alive\n  Content-Disposition: attachment; filename=\"exported-api.zip\"\n  Content-Type: application/zip"
      summary: Export an API
      description: |
        This operation can be used to export the details of a particular API as a zip file.
      tags:
        - API (Individual)
######################################################
# Import Resource API Product
######################################################
  /import/api-product:

    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_product_import_export
      x-wso2-curl: "curl -k -F \"file=@exported.zip\" -X POST -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" https://localhost:9443/api/am/admin/v1/import/api-product?preserveProvider=false&overwriteAPIs=false&overwriteAPIProduct=false"
      x-wso2-request: |
        POST https://localhost:9443/api/am/admin/v1/import/api-product
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8
      x-wso2-response: "HTTP/1.1 200 OK\nAPI Product imported successfully."
      summary: Import an API Product
      description: |
        This operation can be used to import an API Product.
      tags:
        - API Product (Individual)
######################################################
# Export Resource API Product
######################################################
  /export/api-product:

    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_product_import_export
      x-wso2-curl: "curl -k -H \"Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8\" -X GET https://localhost:9443/api/am/admin/v0.17/export/api-product?name=SampleAPIProduct&version=1.0.0&providerName=admin > exportAPIProduct.zip"
      x-wso2-request: |
        GET https://localhost:9443/api/am/admin/v0.17/export/api-product?name=SampleAPIProduct&version=1.0.0&providerName=admin
        Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8
      x-wso2-response: "HTTP/1.1 200 OK\n Connection: keep-alive\n  Content-Disposition: attachment; filename=\"exported-api-product.zip\"\n  Content-Type: application/zip"
      summary: Export an API Product
      description: |
        This operation can be used to export the details of a particular API Product as a zip file.
      tags:
        - API Product (Individual)
######################################################
# The "Label" resource API
######################################################
  /labels:

#-----------------------------------------------------
# Retrieve all labels
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:label_read
      summary: Get all registered Labels
      description: |
        Get all registered Labels
      tags:
        - Label Collection
#-----------------------------------------------------
# Add a Label
#-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:label_manage
      summary: Add a Label
      description: |
        Add a new gateway Label
      tags:
        - Label
######################################################
# The Bot Detection Data API resources
######################################################

  /bot-detection-data:
  #-----------------------------------------------------
  # Get all bot detection data
  #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bot_data
      operationId: getBotDetectionData
      summary: |
        Get all bot detected data
      description: |
        Get all bot detected data
######################################################
# The "Individual label" resource APIs
######################################################

  /labels/{labelId}:

#-----------------------------------------------------
# Update a Label
#-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:label_manage
      summary: Update a Label
      description: |
        Update a Label by label Id
      tags:
        - Label
#-----------------------------------------------------
# Delete a Label
#-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:label_manage
      summary: Delete a Label
      description: |
        Delete a Label by label Id
      tags:
        - Label
  ######################################################
  # The "Monetization" resource APIs
  ######################################################

  /monetization/publish-usage:

    #-----------------------------------------------------
    # Publish monetization related usage records
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:monetization_usage_publish
      summary: Publish Usage Records
      description: |
        Publish Usage Records of Monetized APIs
      tags:
        - Monetization (Collection)
  /monetization/publish-usage/status:

    #-----------------------------------------------------
    # Retrieve the status monetization usage publish job
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:monetization_usage_publish
      summary: Get the status of Monetization usage publisher
      description: |
        Get the status of Monetization usage publisher
      tags:
        - Monetization (Collection)
  ######################################################
  # The "Workflow Collection" resource APIs
  ######################################################
  '/workflows':

    #---------------------------------------------------
    # Retrieve a list of all workflow pending processes
    #---------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_workflow_view
      summary: |
        Retrieve All pending workflow processes
      description: |
        This operation can be used to retrieve list of workflow pending processes.
      tags:
        - Workflow (Collection)
  #----------------------------------------------------------------
  # Retrieve workflow requests according to the external reference
  #----------------------------------------------------------------
  '/workflows/{externalWorkflowRef}':

    #-----------------------------------------------------
    # Retrieve the Details of a workflow pending process
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_workflow_view
      summary: |
        Get details of the pending workflow request according to the External Workflow Reference.
      description: |
        Using this operation, you can retrieve complete details of a pending workflow request that either belongs to application creation, application subscription, application registration, api state change, user self sign up.. You need to provide the External_Workflow_Reference of the workflow Request to retrive it.
      tags:
        - Workflows (Individual)
  ######################################################
  # The "Workflow approval" resource API
  ######################################################
  /workflows/update-workflow-status:

    #-------------------------------------------------------------------
    # Resume the workflow by approving or rejecting the workflow request
    #-------------------------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_workflow_approve
      summary: Update workflow status
      description: |
        This operation can be used to approve or reject a workflow task.
      tags:
        - Workflows (Individual)
  ######################################################
  # The Tenant Info resource API
  ######################################################
  /tenant-info/{username}:
    #--------------------------------------------------------
    # Retrieve tenant information of the given username
    #--------------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tenantInfo
      summary: |
        Get tenant id of the user
      description: |
        This operation is to get tenant id of the provided Base64 encoded user
      operationId: getTenantInfoByUsername
      tags:
        - Tenants
  ######################################################
  # The Custom URL Info resource API
  ######################################################
  /custom-urls/{tenantDomain}:
    #----------------------------------------------------------
    # Retrieve custom url information of the given tenant domain
    #----------------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tenantInfo
      summary: |
        Get custom-url info of a tenant domain
      description: |
        This operation is to get custom-url information of the provided tenant-domain
      operationId: getCustomUrlInfoByTenantDomain
      tags:
        - Tenants
######################################################
# The "Category Collection" resource API
######################################################
  /api-categories:

#-----------------------------------------------------
# Retrieve all categories
#-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Get all API categories
      description: |
        Get all API categories
      tags:
        - API Category (Collection)
#-----------------------------------------------------
# Add a Category
#-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      description: |
        Add a new API Category
      tags:
        - API Category (Individual)
  ######################################################
  # The "Individual Category" resource APIs
  ######################################################

  /api-categories/{apiCategoryId}:

  #-----------------------------------------------------
  # Update a Category
  #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Update an API Category
      description: |
        Update an API Category by category Id
      tags:
        - API Category (Individual)
  #-----------------------------------------------------
  # Delete an API Category
  #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Delete an API Category
      description: |
        Delete an API Category by API Category Id
      tags:
        - API Category (Individual)
######################################################
# The Admin settings List
######################################################
  /settings:
#-----------------------------------------------------
# Retrieve admin settings
#-----------------------------------------------------
    get:
      summary: Retreive admin settings
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_settings
      description: |
        Retreive admin settings
      tags:
        - Settings
  ####################################################
  # The Admin alert  management REST API
  ####################################################
  '/alert-types':
    #--------------------------------------------------
    # Retrieve the list of admin alert types
    #--------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      operationId: getAdminAlertTypes
      summary: |
        Get the list of admin alert types.
      description: |
        This operation is used to get the list of supportd alert types for the apim admin dashboard
      tags:
        - Alerts
  '/alert-subscriptions':
    #--------------------------------------------------
    # Retrieve the list of alerts subscribed by the admin user
    #--------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      summary: |
        Get the list of API Admin alert types subscribed by the user.
      operationId: getSubscribedAlertTypes
      description: |
        This operation is used to get the list of subscribed alert types by the user.
      tags:
        - Alert Subscriptions
    #--------------------------------------------------
    # Subscribe to the selected alert types by the user.
    #--------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      summary: |
        Subscribe to an admin alert.
      operationId: subscribeToAlerts
      description: |
        This operation is used to subscribe to admin alerts
      tags:
        - Alert Subscriptions
    #--------------------------------------------------
    # Unsubscribe the user from all the admin alerts types
    #--------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      summary: |
        Unsubscribe user from all the admin alert types.
      operationId: unsubscribeAllAlerts
      description: |
        This operation is used to unsubscribe the respective user from all the admin alert types.
      tags:
        - Alert Subscriptions
###########################################################
# The Bot Detection Alert Subscription Management resources
###########################################################

  '/alert-subscriptions/bot-detection':
    #------------------------------------------------------------
    # Retrieve the list of subscriptions for bot detection alerts
    #------------------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      operationId: getBotDetectionAlertSubscriptions
      summary: |
        Get the list of subscriptions for bot detection
      description: |
        Get the list of subscriptions which are subscribed to receive email alerts for bot detection
      tags:
        - Bot Detection Alert Subscriptions
    #-----------------------------------------------------
    # Subscribe for bot detection alerts
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      operationId: subscribeForBotDetectionAlerts
      summary: Subscribe for bot detection alerts
      description: |
        Register a subscription for bot detection alerts
      tags:
        - Bot Detection Alert Subscriptions
  '/alert-subscriptions/bot-detection/{uuid}':
    #-----------------------------------------------------
    # Unsubscribe from bot detection alerts
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      operationId: unsubscribeFromBotDetectionAlerts
      summary: Unsubscribe from bot detection alerts.
      description: |
        Delete a subscription from bot detection alerts.
      tags:
        - Bot Detection Alert Subscriptions
  ######################################################
  # System scopes
  ######################################################
  /system-scopes/{scopeName}:
    #-----------------------------------------------------
    # Retrieve scope settings
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:scope_manage
      operationId: systemScopesScopeNameGet
      summary: Retrieve scopes for a particular user
      description: |
        This operation will return the scope list of particular user
        In order to get it, we need to pass the userId as a query parameter
      tags:
        - System Scopes
  /system-scopes:
    #--------------------------------------------------
    # Retrieve the list of role scope mapping
    #--------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:scope_manage
            - apim:admin
      operationId: systemScopesGet
      summary: |
        Get the list of role scope mapping.
      description: |
        This operation is used to get the list of role scope mapping from tenant-conf for the apim admin dashboard
      tags:
        - System Scopes
    #--------------------------------------------------
    # Update the roles for scopes
    #--------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:scope_manage
      summary: |
        Update Roles For Scope
      operationId: updateRolesForScope
      description: |
        This operation is used to update the roles for all scopes
      tags:
        - System Scopes
  ######################################################
  # The 'Role Alias' Collection API Resource
  ######################################################
  /system-scopes/role-aliases:
    #-----------------------------------------------------
    # Retrieve role alias mappings for system scope roles
    #-----------------------------------------------------
    get:
      summary: Retrieve role alias mappings
      security:
        - OAuth2Security:
            - apim:admin
            - apim:scope_manage
      description: |
        This operation can be used to retreive role alias mapping
      tags:
        - System Scopes
    #-----------------------------------------------------
    # Add a new role alias mapping for system roles
    #-----------------------------------------------------
    put:
      summary: Add a new role alias
      security:
        - OAuth2Security:
            - apim:scope_manage
            - apim:admin
      description: |
        This operation can be used to add a new role alias mapping for system scope roles
      tags:
        - System Scopes
  ######################################################
  # The Tenant Theme resource APIs
  ######################################################
  /tenant-theme:
    #-----------------------------------------------------
    # Export Tenant Theme
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tenant_theme_manage
      operationId: exportTenantTheme
      summary: Export a DevPortal Tenant Theme
      description: |
        This operation can be used to export a DevPortal tenant theme as a zip file.
      tags:
        - Tenant Theme
    #-----------------------------------------------------
    # Import Tenant Theme
    #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tenant_theme_manage
      operationId: importTenantTheme
      summary: Import a DevPortal Tenant Theme
      description: |
        This operation can be used to import a DevPortal tenant theme.
      tags:
        - Tenant Theme
  ######################################################
  # The "Key Manager Collection" resource API
  ######################################################
  /key-managers:

    #-----------------------------------------------------
    # Retrieve all key managers
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations

      summary: Get all Key managers
      description: |
        Get all Key managers
      tags:
        - Key Manager (Collection)
    #-----------------------------------------------------
    # Add a Key Manager
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Add a new API Key Manager
      description: |
        Add a new API Key Manager
      tags:
        - Key Manager (Collection)
  ######################################################
  # The "Individual KeyManager" resource APIs
  ######################################################

  /key-managers/{keyManagerId}:

    #-----------------------------------------------------
    # Retrieve a certain Key Manager Resource
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Get a Key Manager Configuration
      description: |
        Retrieve a single Key Manager Configuration. We should provide the Id of the KeyManager as a path parameter.
      tags:
        - Key Manager (Individual)
    #-----------------------------------------------------
    # Update a Key Manager
    #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Update a Key Manager
      description: |
        Update a Key Manager by keyManager id
      tags:
        - Key Manager (Individual)
    #-----------------------------------------------------
    # Delete a Key Manager
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Delete a Key Manager
      description: |
        Delete a Key Manager by keyManager id
      tags:
        - Key Manager (Individual)
######################################################
# Parameters - required by some of the APIs above
######################################################
# Scope Name
  scopeName:
    name: scopeName
    in: path
    description: |
      scope name to be validated
    required: true
    type: string

# Label Id
# Specified as part of the path expression
  labelId:
    name: labelId
    in: path
    description: |
      Label UUID
    type: string
    required: true

# Throttling Policy Id
# Specified as part of the path expression
  policyId:
    name: policyId
    in: path
    description: |
      Thorttle policy UUID
    type: string
    required: true

# Custom rule Id
# Specified as part of the path expression
  ruleId:
    name: ruleId
    in: path
    description: |
      Custom rule UUID
    type: string
    required: true

# Application Id
# Specified as part of the path expression
  applicationId:
    name: applicationId
    in: path
    description: |
      Application UUID
    type: string
    required: true

# Blocking Condition Id
# Specified as part of the path expression
  conditionId:
    name: conditionId
    in: path
    description: |
      Blocking condition identifier
    type: string
    required: true

# The HTTP Accept header
  Accept:
    name: Accept
    in: header
    description: |
      Media types acceptable for the response. Default is application/json.
    default: application/json
    type: string

# The HTTP Content-Type header
  Content-Type:
    name: Content-Type
    in: header
    description: |
      Media type of the entity in the body. Default is application/json.
    default: application/json
    required: true
    type : string

# The HTTP If-None-Match header
# Used to avoid retrieving data that are already cached
  If-None-Match:
    name: If-None-Match
    in: header
    description: |
      Validator for conditional requests; based on the ETag of the formerly retrieved
      variant of the resource (Will be supported in future).
    type : string

# The HTTP If-Modified-Since header
# Used to avoid retrieving data that are already cached
  If-Modified-Since:
    name: If-Modified-Since
    in: header
    description: |
      Validator for conditional requests; based on Last Modified header of the
      formerly retrieved variant of the resource (Will be supported in future).
    type: string

# The HTTP If-Match header
# Used to avoid concurrent updates
  If-Match:
    name: If-Match
    in: header
    description: |
      Validator for conditional requests; based on ETag (Will be supported in future).
    type: string

# The HTTP If-Unmodified-Since header
# Used to avoid concurrent updates
  If-Unmodified-Since:
    name: If-Unmodified-Since
    in: header
    description: |
      Validator for conditional requests; based on Last Modified header (Will be supported in future).
    type: string

# Used for pagination:
# The maximum number of resoures to be returned by a GET
  limit:
    name: limit
    in: query
    description: |
      Maximum size of resource array to return.
    default: 25
    type: integer

# Used for pagination:
# The order number of an instance in a qualified set of resoures
# at which to start to return the next batch of qualified resources
  offset:
    name: offset
    in: query
    description: |
      Starting point within the complete list of items qualified.
    default: 0
    type: integer

# Mediation policy identifier
# Specified as part of the path expression
  mediationPolicyId:
    name: mediationPolicyId
    in: path
    description: |
      Mediation policy Id
    required: true
    type: string

# Group Identifier of the application
  user:
    name: user
    in: query
    description: |
      username of the application creator
    required: false
    type: string

  # Workflow reference ID
  # Specified as part of the path expression
  workflowReferenceId-Q:
    name: workflowReferenceId
    in: query
    description: |
      Workflow reference id
    required: true
    type: string

  # API Category Id
  # Specified as part of the path expression
  apiCategoryId:
    name: apiCategoryId
    in: path
    description: |
      API Category UUID
    type: string
    required: true

  # Key Manager Id
  # Specified as part of the path expression
  keyManagerId:
    name: keyManagerId
    in: path
    description: |
      Key Manager UUID
    type: string
    required: true

######################################################
# The resources used by some of the APIs above within the message body
######################################################
#-----------------------------------------------------
# The Error resource
#-----------------------------------------------------
  Error:
    title: Error object returned with 4XX HTTP status
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int64
        description: Error code
      message:
        type: string
        description: Error message.
      description:
        type: string
        description: |
          A detail description about the error message.
      moreInfo:
        type: string
        description: |
          Preferably an url with more details about the error.
      error:
        type: array
        description: |
          If there are more than one error list them out.
          For example, list out validation errors by each field.
        items:
          $ref: '#/definitions/ErrorListItem'

#-----------------------------------------------------
# The Error List Item resource
#-----------------------------------------------------
  ErrorListItem:
    title: Description of individual errors that may have occurred during a request.
    required:
      - code
      - message
    properties:
      code:
        type: string
        description: Error code
      message:
        type: string
        description: |
          Description about individual errors occurred

#-----------------------------------------------------
# The Throttling Policy resource
#-----------------------------------------------------
  ThrottlePolicy :
    discriminator: policyName
    title: Generic Throttling Policy
    required:
      - policyName
    properties:
      policyId:
        type: string
        description: Id of policy
      policyName:
        type: string
        description: Name of policy
      displayName:
        type: string
        description: Display name of the policy
      description:
        type: string
        description: Description of the policy
      isDeployed:
        type: boolean
        default: false
        description: Indicates whether the policy is deployed successfully or not.

#-----------------------------------------------------
# The Advanced Throttling Policy Info resource
#-----------------------------------------------------
  AdvancedThrottlePolicyInfo :
    title: Advanced Throttling Policy
    required:
      - defaultLimit
    allOf:
      - $ref: '#/definitions/ThrottlePolicy'
      - properties:
          defaultLimit:
            $ref: '#/definitions/ThrottleLimit'

#-----------------------------------------------------
# The Advanced Throttling Policy resource
#-----------------------------------------------------
  AdvancedThrottlePolicy :
    title: Advanced Throttling Policy
    allOf:
      - $ref: '#/definitions/ThrottlePolicy'
      - required:
        - defaultLimit
        properties:
          defaultLimit:
            $ref: '#/definitions/ThrottleLimit'
          conditionalGroups:
            type: array
            description: |
              Group of conditions which allow adding different parameter conditions to the throttling limit.
            items:
              $ref: '#/definitions/ConditionalGroup'

#-----------------------------------------------------
# The Advanced Throttling Policy List resource
#-----------------------------------------------------
  AdvancedThrottlePolicyList:
    title: Advanced Throttling Policy List
    properties:
      count:
        type: integer
        description: |
          Number of Advanced Throttling Policies returned.
      list:
        type: array
        items:
          $ref: '#/definitions/AdvancedThrottlePolicyInfo'

#-----------------------------------------------------
# The Application Throttling Policy resource
#-----------------------------------------------------
  ApplicationThrottlePolicy:
    title: Application Throttling Policy
    allOf:
      - $ref: '#/definitions/ThrottlePolicy'
      - required:
        - defaultLimit
        properties:
          defaultLimit:
            $ref: '#/definitions/ThrottleLimit'

#-----------------------------------------------------
# The Advanced Throttling Policy List resource
#-----------------------------------------------------
  ApplicationThrottlePolicyList:
    title: Application Level Throttling Policy List
    properties:
      count:
        type: integer
        description: |
          Number of Application Throttling Policies returned.
      list:
        type: array
        items:
          $ref: '#/definitions/ApplicationThrottlePolicy'

#-----------------------------------------------------
# The Subscription Throttling Policy resource
#-----------------------------------------------------
  SubscriptionThrottlePolicy:
    title: Subscription Throttling Policy
    allOf:
      - $ref: '#/definitions/ThrottlePolicy'
      - $ref: '#/definitions/GraphQLQuery'
      - required:
        - defaultLimit
        properties:
          defaultLimit:
            $ref: '#/definitions/ThrottleLimit'
          monetization:
            $ref: '#/definitions/MonetizationInfo'
          rateLimitCount:
            type: integer
            default: 0
            description: Burst control request count
          rateLimitTimeUnit:
            type: string
            description: Burst control time unit
          customAttributes:
            description: |
              Custom attributes added to the Subscription Throttling Policy
            type: array
            items:
              $ref: '#/definitions/CustomAttribute'
            additionalProperties:
              type: string
          stopOnQuotaReach:
            type: boolean
            default: false
            description: |
             This indicates the action to be taken when a user goes beyond the allocated quota. If checked, the user's requests will be dropped. If unchecked, the requests will be allowed to pass through.
          billingPlan:
            type: string
            description: |
              define whether this is Paid or a Free plan. Allowed values are FREE or COMMERCIAL.

#-----------------------------------------------------
# The GraphQL Query resource
#-----------------------------------------------------
  GraphQLQuery:
    title: GraphQL Query
    properties:
      graphQLMaxComplexity:
        type: integer
        description: Maximum Complexity of the GraphQL query
      graphQLMaxDepth:
        type: integer
        description: Maximum Depth of the GraphQL query
#-----------------------------------------------------
# The Subscription Throttling Policy List resource
#-----------------------------------------------------
  SubscriptionThrottlePolicyList:
    title: Subscription Level Throttling Policy List
    properties:
      count:
        type: integer
        description: |
          Number of Subscription Throttling Policies returned.
      list:
        type: array
        items:
          $ref: '#/definitions/SubscriptionThrottlePolicy'

#-----------------------------------------------------
# The Custom Rule resource
#-----------------------------------------------------
  CustomRule:
    title: Custom Rule
    allOf:
      - $ref: '#/definitions/ThrottlePolicy'
      - required:
        - siddhiQuery
        - keyTemplate
        properties:
          siddhiQuery:
            type: string
            description: Siddhi query which represents the custom throttling policy
          keyTemplate:
            type: string
            description: The specific combination of attributes that are checked in the policy.
#-----------------------------------------------------
# The Custom Rule List resource
#-----------------------------------------------------
  CustomRuleList:
    title: Custom Rule List
    properties:
      count:
        type: integer
        description: |
          Number of Custom Rules returned.
      list:
        type: array
        items:
          $ref: '#/definitions/CustomRule'

#-----------------------------------------------------
# The Conditional Group resource
#-----------------------------------------------------
  ConditionalGroup:
    title: Conditional Groups for Throttling
    required:
      - limit
      - conditions
    properties:
      description:
        type: string
        description: Description of the Conditional Group
      conditions:
        type: array
        items:
          $ref: '#/definitions/ThrottleCondition'
        description: |
          Individual throttling conditions. They can be defined as either HeaderCondition, IPCondition, JWTClaimsCondition, QueryParameterCondition
          Please see schemas of each of those throttling condition in Definitions section.
      limit:
        $ref: '#/definitions/ThrottleLimit'

#-----------------------------------------------------
# The Throttling Condition resource
#-----------------------------------------------------
  ThrottleCondition:
    title: Throttling Conditions
    description: Conditions used for Throttling
    required:
      - type
    properties:
      type:
        type: string
        enum:
          - HEADERCONDITION
          - IPCONDITION
          - JWTCLAIMSCONDITION
          - QUERYPARAMETERCONDITION
        description: |
          Type of the throttling condition. Allowed values are "HEADERCONDITION", "IPCONDITION", "JWTCLAIMSCONDITION"
          and "QUERYPARAMETERCONDITION".
      invertCondition:
        type: boolean
        default: false
        description: |
          Specifies whether inversion of the condition to be matched against the request.

          **Note:** When you add conditional groups for advanced throttling policies, this paramater should have the
          same value ('true' or 'false') for the same type of conditional group.
      headerCondition:
        $ref: '#/definitions/HeaderCondition'
      ipCondition:
        $ref: '#/definitions/IPCondition'
      jwtClaimsCondition:
        $ref: '#/definitions/JWTClaimsCondition'
      queryParameterCondition:
        $ref: '#/definitions/QueryParameterCondition'

#-----------------------------------------------------
# The Throttling HTTP Header Condition resource
#-----------------------------------------------------
  HeaderCondition:
    title: HTTP Header based throttling condition
    required:
      - headerName
      - headerValue
    properties:
      headerName:
        type: string
        description: Name of the header
      headerValue:
        type: string
        description: Value of the header

#-----------------------------------------------------
# The Throttling IP Condition resource
#-----------------------------------------------------
  IPCondition:
    title: IP based throttling condition
    required:
      - specificIP
    properties:
      ipConditionType:
        type: string
        enum:
          - IPRANGE
          - IPSPECIFIC
        description: Type of the IP condition. Allowed values are "IPRANGE" and "IPSPECIFIC"
      specificIP:
        type: string
        description: Specific IP when "IPSPECIFIC" is used as the ipConditionType
      startingIP:
        type: string
        description: Staring IP when "IPRANGE" is used as the ipConditionType
      endingIP:
        type: string
        description: Ending IP when "IPRANGE" is used as the ipConditionType

#-----------------------------------------------------
# The JWT Claims Condition resource
#-----------------------------------------------------
  JWTClaimsCondition:
    title:  JWT claim attibute based throttling condition
    required:
      - claimUrl
      - attribute
    properties:
      claimUrl:
        type: string
        description: JWT claim URL
      attribute:
        type: string
        description: Attribute to be matched

#-----------------------------------------------------
# The Query Parameter Condition resource
#-----------------------------------------------------
  QueryParameterCondition:
    title: Query parameter based throttling condition
    required:
      - parameterName
      - parameterValue
    properties:
      parameterName:
        type: string
        description: Name of the query parameter
      parameterValue:
        type: string
        description: Value of the query parameter to be matched

#-----------------------------------------------------
# The Throttling Limit Base resource
#-----------------------------------------------------
  ThrottleLimitBase:
    title: Throttle Limit Base
    required:
      - timeUnit
      - unitTime
    properties:
      timeUnit:
        type: string
        description: Unit of the time. Allowed values are "sec", "min", "hour", "day"
      unitTime:
        type: integer
        default: 0
        description: Time limit that the throttling limit applies.
#-----------------------------------------------------
# The Throttling Limit resource
#-----------------------------------------------------
  ThrottleLimit:
    title: Throttle Limit
    required:
      - type
    properties:
      type:
        type: string
        enum:
          - REQUESTCOUNTLIMIT
          - BANDWIDTHLIMIT
        description: |
          Type of the throttling limit. Allowed values are "REQUESTCOUNTLIMIT" and "BANDWIDTHLIMIT".
          Please see schemas of "RequestCountLimit" and "BandwidthLimit" throttling limit types in
          Definitions section.
      requestCount:
        $ref: '#/definitions/RequestCountLimit'
      bandwidth:
        $ref: '#/definitions/BandwidthLimit'

#-----------------------------------------------------
# The Monetization Info resource
#-----------------------------------------------------
  MonetizationInfo:
    title: API monetization details object
    required:
      - monetizationPlan
      - properties
    properties:
      monetizationPlan:
        type: string
        description: Flag to indicate the monetization plan
        enum:
          - FixedRate
          - DynamicRate
      properties:
        type: object
        description: Map of custom properties related to each monetization plan
        additionalProperties:
          type: string

#-----------------------------------------------------
# The Throttling Bandwidth Limit resource
#-----------------------------------------------------
  BandwidthLimit:
    title: Bandwidth Limit object
    allOf:
      - $ref: '#/definitions/ThrottleLimitBase'
      - required:
        - dataAmount
        - dataUnit
        properties:
          dataAmount:
            type: integer
            format: int64
            description: Amount of data allowed to be transfered
          dataUnit:
            type: string
            description: Unit of data allowed to be transfered. Allowed values are "KB", "MB" and "GB"
#-----------------------------------------------------
# The Throttling Request Count Limit resource
#-----------------------------------------------------
  RequestCountLimit:
    title: Request Count Limit object
    allOf:
      - $ref: '#/definitions/ThrottleLimitBase'
      - required:
        - requestCount
        properties:
          requestCount:
            type: integer
            format: int64
            description: Maximum number of requests allowed
#-----------------------------------------------------
# The Throttling Blocking Condition resource
#-----------------------------------------------------
  BlockingCondition:
    title: Blocking Conditions
    description: Blocking Conditions
    required:
      - conditionType
      - conditionValue
    properties:
      conditionId:
        type: string
        description: Id of the blocking condition
      conditionType:
        type: string
        description: Type of the blocking condition
      conditionValue:
        type: object
        description: Value of the blocking condition
      conditionStatus:
        type: boolean
        description: Status of the blocking condition
#-----------------------------------------------------
# The Throttling Blocking Condition List resource
#-----------------------------------------------------
  BlockingConditionList:
    title: Blocking Conditions List
    properties:
      count:
        type: integer
        description: |
          Number of Blocking Conditions returned.
      list:
        type: array
        items:
          $ref: '#/definitions/BlockingCondition'
#-----------------------------------------------------
# The Throttling Blocking Condition Status resource
#-----------------------------------------------------
  BlockingConditionStatus:
    title: Blocking Conditions Status
    description: Blocking Conditions Status
    required:
      - conditionStatus
    properties:
      conditionId:
        type: string
        description: Id of the blocking condition
      conditionStatus:
        type: boolean
        description: Status of the blocking condition
#-----------------------------------------------------
# Custom Attribute object
#-----------------------------------------------------
  CustomAttribute:
    title: Name-Value pair
    required:
      - name
      - value
    properties:
      name:
        type: string
        description: Name of the custom attribute
      value:
        type: string
        description: Value of the custom attribute
#-----------------------------------------------------
# The Mediation List resource
#-----------------------------------------------------
  mediationList:
    title: Mediation List
    properties:
      count:
        type: integer
        description: |
          Number of mediation sequences returned.
      next:
        type: string
        description: |
          Link to the next subset of sequences qualified.
          Empty if no more sequences are to be returned.
      previous:
        type: string
        description: |
          Link to the previous subset of sequences qualified.
          Empty if current subset is the first subset returned.
      list:
        type: array
        items:
          $ref: '#/definitions/MediationInfo'

#-----------------------------------------------------
# The MediationInfo resource
#-----------------------------------------------------
  MediationInfo:
    title: MediationInfo
    required:
      - name
      - type
      - id
    properties:
      name:
        type: string
      id:
        type: string
      type:
        type: string
        enum:
          - in
          - out
          - fault
#-----------------------------------------------------
# The Mediation resource
#-----------------------------------------------------
  Mediation:
    title: Mediation
    required:
      - name
      - type
      - config
    properties:
      id:
        type: string
      name:
        type: string
      type:
        type: string
        enum:
          - in
          - out
          - fault
      config:
        type: string
#-----------------------------------------------------
# The Application List resource
#-----------------------------------------------------
  ApplicationList:
    title: Application List
    properties:
      count:
        type: integer
        description: |
          Number of applications returned.
      next:
        type: string
        description: |
          Link to the next subset of resources qualified.
          Empty if no more resources are to be returned.
      previous:
        type: string
        description: |
          Link to the previous subset of resources qualified.
          Empty if current subset is the first subset returned.
      list:
        type: array
        items:
          $ref: '#/definitions/ApplicationInfo'

#-----------------------------------------------------
# The Application Info resource
#-----------------------------------------------------
  ApplicationInfo:
    title: Application info object with basic application details
    properties:
      applicationId:
        type: string
      name:
        type: string
      owner:
        type: string
      status:
        type: string
      groupId:
        type: string
#-----------------------------------------------------
# The API Info List resource
#-----------------------------------------------------
  APIInfoList:
    title: API Info List
    properties:
      count:
        type: integer
        description: |
          Number of API Info objects returned.
      list:
        type: array
        items:
          $ref: '#/definitions/APIInfo'

#-----------------------------------------------------
# The API Info resource
#-----------------------------------------------------
  APIInfo:
    title: API info object with basic API details
    properties:
      name:
        type: string
        description: The name of the API.
      version:
        type: string
        description: The version of the API
      provider:
        type: string
        description: The provider of the API
#-----------------------------------------------------
# The Label resource
#-----------------------------------------------------
  Label:
    title: Label
    required:
    - name
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      accessUrls:
        type: array
        items:
          type: string
#-----------------------------------------------------
# The Label List resource
#-----------------------------------------------------
  LabelList:
    title: Label List
    properties:
      count:
        type: integer
        description: |
          Number of Labels returned.
      list:
        type: array
        items:
          $ref: '#/definitions/Label'

  #-----------------------------------------------------
  # The publish status resource
  #-----------------------------------------------------
  PublishStatus:
    title: Usage publish status
    properties:
      status:
        type: string
        description: Status of the usage publish request
      message:
        type: string
        description: detailed message of the status

  #-----------------------------------------------------
  # The publish status resource
  #-----------------------------------------------------
  MonetizationUsagePublishInfo:
    title: Usage publish status
    properties:
      state:
        type: string
        description: State of usage publish job
      status:
        type: string
        description: Status of usage publish job
      startedTime:
        type: string
        description: Timestamp of the started time of the Job
      lastPublsihedTime:
        type: string
        description: Timestamp of the last published time

  #-----------------------------------------------------
  # The workflow response resource
  #-----------------------------------------------------
  Workflow:
    title: workflow
    required:
      - status
    properties:
      status:
        description: |
          This attribute declares whether this workflow task is approved or rejected.
        type: string
        enum:
          - APPROVED
          - REJECTED
      attributes:
        description: |
          Custom attributes to complete the workflow task
        type: object
        additionalProperties:
          type: string
      description:
        type: string
  #-----------------------------------------------------
  # The Tenant info response resource
  #-----------------------------------------------------
  TenantInfo:
    title: Tenant information
    type: object
    description: The tenant information of the user
    properties:
      username:
        type: string
      tenantDomain:
        type: string
      tenantId:
        type: integer
  #-----------------------------------------------------
  # The CustomURL info response resource
  #-----------------------------------------------------
  CustomUrlInfo:
    title: Custom url information
    type: object
    description: The custom url information of the tenant domain
    properties:
      tenantDomain:
        type: string
      tenantAdminUsername:
        type: string
      enabled:
        type: boolean
      devPortal:
        type: object
        properties:
          url:
            type: string
  #-----------------------------------------------------
  # The Category resource
  #-----------------------------------------------------
  APICategory:
    title: API Category
    required:
      - name
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      numberOfAPIs:
        type: integer
  #-----------------------------------------------------
  # The Category List resource
  #-----------------------------------------------------
  APICategoryList:
    title: API Category List
    properties:
      count:
        type: integer
        description: |
          Number of API categories returned.
      list:
        type: array
        items:
          $ref: '#/definitions/APICategory'

  #-----------------------------------------------------
  # The File Information resource
  #-----------------------------------------------------
  FileInfo :
    title: File Information including meta data
    properties:
      relativePath:
        type: string
        description: relative location of the file (excluding the base context and host of the Admin API)
      mediaType:
        type: string
        description: media-type of the file
  #-----------------------------------------------------
  # The Settings resource
  #-----------------------------------------------------
  Settings:
    title: Settings
    properties:
      scopes:
        type: array
        items:
          type: string
      keyManagerConfiguration:
        type: array
        items:
          properties:
            type:
              type: string
            configurations:
              type: array
              items:
                $ref: '#/definitions/KeyManagerConfiguration'
      analyticsEnabled:
        type: boolean
        description: To determine whether analytics is enabled or not
  #-----------------------------------------------------
  # The Scope Role Mapping List resource
  #-----------------------------------------------------
  ScopeList:
    title: Scope Role Mapping List
    properties:
      count:
        type: integer
        description: |
          Number of scopes available for tenant.
      list:
        type: array
        items:
          $ref: '#/definitions/Scope'

  #-----------------------------------------------------
  # The Scope resource
  #-----------------------------------------------------
  Scope:
    title: Scope Role
    properties:
      tag:
        type: string
        description: |
          Portal name.
      name:
        type: string
        description: |
          Scope name.
      description:
        type: string
        description: |
          About scope.
      roles:
        schema:
          type: array
          items:
            type: string
        description: |
          Roles for the particular scope.
  #-----------------------------------------------------
  # The KeyManager resource
  #-----------------------------------------------------
  KeyManager:
    title: Key Manager
    required:
      - name
      - type
    properties:
      id:
        type: string
      name:
        type: string
      displayName:
        type: string
        description: |
          display name of Key Manager to  show in UI
      type:
        type: string
      description:
        type: string
      introspectionEndpoint:
        type: string
      clientRegistrationEndpoint:
        type: string
      tokenEndpoint:
        type: string
      revokeEndpoint:
        type: string
      userInfoEndpoint:
        type: string
      authorizeEndpoint:
        type: string
      certificates:
        type: object
        properties:
          type:
            type: string
            enum:
              - JWKS
              - PEM
          value:
            type: string
      issuer:
        type: string
      scopeManagementEndpoint:
        type: string
      availableGrantTypes:
        type: array
        items:
          type: string
      enableTokenGeneration:
        type: boolean
      enableTokenEncryption:
        type: boolean
        default: false
      enableTokenHashing:
        type: boolean
        default: false
      enableMapOAuthConsumerApps:
        type: boolean
        default: false
      enableOAuthAppCreation:
        type: boolean
        default: false
      enableSelfValidationJWT:
        type: boolean
        default: true
      claimMapping:
        type: array
        items:
          $ref: '#/definitions/ClaimMappingEntry'
      consumerKeyClaim:
        type: string
      scopesClaim:
        type: string
      tokenValidation:
        type: array
        items:
          $ref: '#/definitions/TokenValidation'
      enabled:
        type: boolean
      additionalProperties:
        type: object

  #-----------------------------------------------------
  # The KeyManager resource
  #-----------------------------------------------------
  KeyManagerInfo:
    title: Key Manager Info
    required:
      - name
      - type
    properties:
      id:
        type: string
      name:
        type: string
      type:
        type: string
      description:
        type: string
      enabled:
        type: boolean
  #-----------------------------------------------------
  # The KeyManager resource
  #-----------------------------------------------------
  KeyManagerConfiguration:
    title: Key Manager Configuration
    properties:
      name:
        type: string
      label:
        type: string
      type:
        type: string
      required:
        type: boolean
      mask:
        type: boolean
      multiple:
        type: boolean
      tooltip:
        type: string
      default:
        type: object
      values:
        type: array
        items:
          type: object

  #-----------------------------------------------------
  # The KeyManager List resource
  #-----------------------------------------------------
  KeyManagerList:
    title: Key Manager List
    properties:
      count:
        type: integer
        description: |
          Number of Key managers returned.
      list:
        type: array
        items:
          $ref: '#/definitions/KeyManagerInfo'
  #-----------------------------------------------------
  # The Claim Mapping Resource
  #-----------------------------------------------------

  ClaimMappingEntry:
    title: Claim Mapping Configuration
    properties:
      remoteClaim:
        type: string
      localClaim:
        type: string
  TokenValidation:
    title: Token handling Configuration
    properties:
      id:
        type: integer
      enable:
        type: boolean
        default: true
      type:
        type: string
        enum:
          - REFERENCE
          - JWT
          - CUSTOM
      value:
        type: object

  #-----------------------------------------------------
  # The Scope Settings resource
  #-----------------------------------------------------
  ScopeSettings:
    title: Settings
    properties:
      name:
        type: string
        items:
          type: string


    #----------------------------------------------
  # The Alert list resource.
  #----------------------------------------------
  AlertTypesList:
    title: Alert Types List
    properties:
      count:
        type: integer
        description: The number of alerts
      alerts:
        type: array
        items:
          $ref: '#/definitions/AlertType'

  #----------------------------------------------
  # The AlertType resource.
  #----------------------------------------------
  AlertType:
    title: Alert Type
    properties:
      id:
        type: string
        description: The alert Id
      name:
        type: string
        description: The name of the alert.
  #-----------------------------------------------
  # The Alerts Subscription resource definition.
  #-----------------------------------------------
  AlertsSubscription:
    title: Alerts Subscription
    properties:
      alerts:
        type: array
        items:
          $ref: '#/definitions/AlertType'
      emailList:
        type: array
        items:
          type: string
  #-----------------------------------------------------
  # The Bot Detection Alert Subscription List resource
  #-----------------------------------------------------
  BotDetectionAlertSubscriptionList:
    title: Bot Detection Alert Subscription List
    properties:
      count:
        type: integer
        description: |
          Number of Bot Detection Alert Subscriptions returned.
      list:
        type: array
        items:
          $ref: '#/definitions/BotDetectionAlertSubscription'

  #-----------------------------------------------------
  # The Bot Detection Alert Subscription resource
  #-----------------------------------------------------
  BotDetectionAlertSubscription:
    title: Bot Detection Alert Subscription
    required:
      - email
    properties:
      uuid:
        type: string
        description: UUID of the subscription
      email:
        type: string
        description: email
    #-----------------------------------------------------
  # The Workflow List resource
  #-----------------------------------------------------
  WorkflowList:
    title: WorkflowList
    properties:
      count:
        type: integer
        description: |
          Number of workflow processes returned.
      next:
        type: string
        description: |
          Link to the next subset of resources qualified.
          Empty if no more resources are to be returned.
      previous:
        type: string
        description: |
          Link to the previous subset of resources qualified.
          Empty if current subset is the first subset returned.
      list:
        type: array
        items:
          $ref: '#/definitions/WorkflowInfo'

  #-----------------------------------------------------
  # The Workflow Info resource
  #-----------------------------------------------------
  WorkflowInfo:
    title: Workflow info object with basic workflow details
    properties:
      workflowType:
        type: string
        enum:
          - APPLICATION_CREATION
          - SUBSCRIPTION_CREATION
          - USER_SIGNUP
          - APPLICATION_REGISTRATION_PRODUCTION
          - APPLICATION_REGISTRATION_SANDBOX
          - APPLICATION_DELETION
          - API_STATE
          - SUBSCRIPTION_DELETION
          - SUBSCRIPTION_UPDATE
        description: |
          Type of the Workflow Request. It shows which type of request is it.
      workflowStatus:
        type: string
        enum:
          - APPROVED
          - CREATED
        description: |
          Show the Status of the the workflow request whether it is approved or created.
      createdTime:
        type: string
        description: |
          Time of the the workflow request created.
      updatedTime:
        type: string
        description: |
          Time of the the workflow request updated.
      referenceId:
        type: string
        description: |
          Workflow external reference is used to identify the workflow requests uniquely.
      properties:
        type: object
      description:
        type: string
        description: |
          description is a message with basic details about the workflow request.

  #-----------------------------------------------------
  # The workflow executor's response resource
  #-----------------------------------------------------
  WorkflowResponse:
    title: workflow Response
    required:
      - workflowStatus
    properties:
      workflowStatus:
        description: |
          This attribute declares whether this workflow task is approved or rejected.
        type: string
        enum:
          - CREATED
          - APPROVED
          - REJECTED
          - REGISTERED
      jsonPayload:
        description: |
          Attributes that returned after the workflow execution
        type: string

  #-----------------------------------------------------
  # The Bot Detection Data List resource
  #-----------------------------------------------------
  BotDetectionDataList:
    title: Bot Detection Data List
    properties:
      count:
        type: integer
        description: |
          Number of Bot Detection Data returned.
      list:
        type: array
        items:
          $ref: '#/definitions/BotDetectionData'

  #-----------------------------------------------------
  # The Bot Detection Data resource
  #-----------------------------------------------------
  BotDetectionData:
    title: Bot Detection Data
    properties:
      recordedTime:
        type: integer
        format: int64
        description: The time of detection
      messageID:
        type: string
        description: The message ID
      apiMethod:
        type: string
        description: The api method
      headerSet:
        type: string
        description: The header set
      messageBody:
        type: string
        description: The content of the message body
      clientIp:
        type: string
        description: The IP of the client
  #-----------------------------------------------
  # The Role Alias resource definition.
  #-----------------------------------------------
  RoleAliasList:
    title: Role alias list
    properties:
      count:
        type: integer
        description: The number of role aliases
      list:
        type: array
        items:
          $ref: '#/definitions/RoleAlias'

  #-----------------------------------------------
  # The Role Alias resource definition.
  #-----------------------------------------------
  RoleAlias:
    title: Role alias
    properties:
      role:
        type: string
        description: The original role
      aliases:
        schema:
          type: array
          items:
            type: string
        description: The role mapping for role alias
#-----------------------------------------------------
# END-OF-FILE
#-----------------------------------------------------
