#   Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
################################################################################

swagger: '2.0'
######################################################
# Prolog
######################################################
info:
  version: "v1.2"
  title: "WSO2 API Manager - Admin"
  description: |
    This document specifies a **RESTful API** for WSO2 **API Manager** - **Admin Portal**.
    Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.7.206/components/apimgt/org.wso2.carbon.apimgt.rest.api.admin.v1/src/main/resources/admin-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification.

    # Authentication
    Our REST APIs are protected using OAuth2 and access control is achieved through scopes. Before you start invoking
    the the API you need to obtain an access token with the required scopes. This guide will walk you through the steps
    that you will need to follow to obtain an access token.
    First you need to obtain the consumer key/secret key pair by calling the dynamic client registration (DCR) endpoint. You can add your preferred grant types
    in the payload. A sample payload is shown below.
    ```
      {
      "callbackUrl":"www.google.lk",
      "clientName":"rest_api_admin",
      "owner":"admin",
      "grantType":"client_credentials password refresh_token",
      "saasApp":true
      }
    ```
    Create a file (payload.json) with the above sample payload, and use the cURL shown bellow to invoke the DCR endpoint. Authorization header of this should contain the
    base64 encoded admin username and password.
    **Format of the request**
    ```
      curl -X POST -H "Authorization: Basic Base64(admin_username:admin_password)" -H "Content-Type: application/json"
      \ -d @payload.json https://<host>:<servlet_port>/client-registration/v0.17/register
    ```
    **Sample request**
    ```
      curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json"
      \ -d @payload.json https://localhost:9443/client-registration/v0.17/register
    ```
    Following is a sample response after invoking the above curl.
    ```
    {
    "clientId": "fOCi4vNJ59PpHucC2CAYfYuADdMa",
    "clientName": "rest_api_admin",
    "callBackURL": "www.google.lk",
    "clientSecret": "a4FwHlq0iCIKVs2MPIIDnepZnYMa",
    "isSaasApplication": true,
    "appOwner": "admin",
    "jsonString": "{\"grant_types\":\"client_credentials password refresh_token\",\"redirect_uris\":\"www.google.lk\",\"client_name\":\"rest_api_admin\"}",
    "jsonAppAttribute": "{}",
    "tokenType": null
    }
    ```
    Next you must use the above client id and secret to obtain the access token.
    We will be using the password grant type for this, you can use any grant type you desire.
    You also need to add the proper **scope** when getting the access token. All possible scopes for Admin REST API can be viewed in **OAuth2 Security** section
    of this document and scope for each resource is given in **authorizations** section of resource documentation.
    Following is the format of the request if you are using the password grant type.
    ```
    curl -k -d "grant_type=password&username=<admin_username>&password=<admin_passowrd>&scope=<scopes seperated by space>"
    \ -H "Authorization: Basic base64(cliet_id:client_secret)"
    \ https://<host>:<gateway_port>/token
    ```
    **Sample request**
    ```
    curl https://localhost:8243/token -k \
    -H "Authorization: Basic Zk9DaTR2Tko1OVBwSHVjQzJDQVlmWXVBRGRNYTphNEZ3SGxxMGlDSUtWczJNUElJRG5lcFpuWU1h" \
    -d "grant_type=password&username=admin&password=admin&scope=apim:admin apim:tier_view"
    ```
    Shown below is a sample response to the above request.
    ```
    {
    "access_token": "e79bda48-3406-3178-acce-f6e4dbdcbb12",
    "refresh_token": "a757795d-e69f-38b8-bd85-9aded677a97c",
    "scope": "apim:admin apim:tier_view",
    "token_type": "Bearer",
    "expires_in": 3600
    }
    ```
    Now you have a valid access token, which you can use to invoke an API.
    Navigate through the API descriptions to find the required API, obtain an access token as described above and invoke the API with the authentication header.
    If you use a different authentication mechanism, this process may change.

    # Try out in Postman
    If you want to try-out the embedded postman collection with "Run in Postman" option, please follow the guidelines listed below.
    * All of the OAuth2 secured endpoints have been configured with an Authorization Bearer header with a parameterized access token. Before invoking any REST API resource make sure you run the `Register DCR Application` and `Generate Access Token` requests to fetch an access token with all required scopes.
    * Make sure you have an API Manager instance up and running.
    * Update the `basepath` parameter to match the hostname and port of the APIM instance.

    [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/f5ac2ca9fb22afef6ed6)
  contact:
    name: "WSO2"
    url: "http://wso2.com/products/api-manager/"
    email: "architecture@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

######################################################
# The fixed parts of the URLs of the API
######################################################

# The schemes supported by the API
schemes:
  - https

# The domain of the API.
# This is configured by the customer during deployment.
# The given host is just an example.
host: apis.wso2.com

# The base path of the API.
# Will be prefixed to all paths.
basePath: /api/am/admin/v1

# The following media types can be passed as input in message bodies of the API.
# The actual media type must be specified in the Content-Type header field of the request.
# The default is json, i.e. the Content-Type header is not needed to
# be set, but supporting it serves extensibility.
# The following media types may be passed as output in message bodies of the API.
# The media type(s) consumable by the requestor is specified in the Accept header field
# of the corresponding request.
# The actual media type returned will be specfied in the Content-Type header field
# of the of the response.
# The default of the Accept header is json, i.e. there is not needed to
# set the value, but supporting it serves extensibility.
securityDefinitions:
  OAuth2Security:
    type: oauth2
    flow: password
    tokenUrl: https://localhost:9443/oauth2/token
    scopes:
      openid: Authorize access to user details
      apim:admin: Manage all admin operations
      apim:tier_view: View throttling policies
      apim:tier_manage: Update and delete throttling policies
      apim:bl_view: View deny policies
      apim:bl_manage: Update and delete deny policies
      apim:mediation_policy_view: View mediation policies
      apim:mediation_policy_create: Create and update mediation policies
      apim:app_owner_change: Retrieve and manage applications
      apim:app_import_export: Import and export applications related operations
      apim:api_import_export: Import and export APIs related operations
      apim:api_product_import_export: Import and export API Products related operations
      apim:label_manage: Manage microgateway labels
      apim:label_read: Retrieve microgateway labels
      apim:monetization_usage_publish: Retrieve and publish Monetization related usage records
      apim:api_workflow_approve: Manage workflows
      apim:bot_data: Retrieve bot detection data
      apim:tenantInfo: Retrieve tenant related information
      apim:tenant_theme_manage: Manage tenant themes
      apim:admin_operations: Manage API categories and Key Managers related operations
      apim:admin_settings: Retrieve admin settings
      apim:admin_alert_manage: Manage admin alerts
      apim:api_workflow_view: Retrive workflow requests
      apim:scope_manage: Manage system scopes

######################################################
# The "API Collection" resource APIs
######################################################
paths:
  ######################################################
  # The "Application Throttling Policy Collection" resource API
  ######################################################
  '/throttling/policies/application':

    #-----------------------------------------------------
    # Retrieve all Application level policies
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get all Application Throttling Policies
      description: |
        Retrieves all existing application throttling policies.
      tags:
        - Application Policy (Collection)
    #-----------------------------------------------------
    # Add a Application level Throttling Policy
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Add an Application Throttling Policy
      description: |
        This operation can be used to add a new application level throttling policy.
      tags:
        - Application Policy (Collection)
  ######################################################
  # The "Individual Application Throttling Policy" resource API
  ######################################################
  '/throttling/policies/application/{policyId}':

    #-----------------------------------------------------
    # Retrieve a certain Application Policy
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get an Application Throttling Policy
      description: |
        Retrieves an application throttling policy.
      tags:
        - Application Policy (Individual)
    #-----------------------------------------------------
    # Delete an Application level throttling policy
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Delete an Application Throttling policy
      description: |
        Deletes an application level throttling policy.
      tags:
        - Application Policy (Individual)
    #-----------------------------------------------------
    # Update an Application throttling policy
    #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Update an Application Throttling policy
      description: |
        Updates an existing application level throttling policy. Upon a succesfull update, you will receive the updated application policy as the response.
      tags:
        - Application Policy (Individual)
  /policies/mediation:
    #-----------------------------------------------------------------------------------------
    # Retrieving the list of all global mediation sequences under a given search condition
    #-----------------------------------------------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:mediation_policy_view
      summary: |
        Get all Global Mediation Policies
      description: |
        This operation provides you a list of all available global mediation policies.
      tags:
        - Mediation Policy (Collection)
    #----------------------------------------------------------------------------
    # Upload a global mediation policy
    #----------------------------------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:mediation_policy_create
      summary: Add a Global Mediation Policy
      description: |
        This operation can be used to add a new global mediation policy.
      tags:
        - Mediation Policy (Collection)
  ######################################################
  # The "Individual global mediation sequence" resource
  ######################################################
  /policies/mediation/{mediationPolicyId}:

    #-----------------------------------------------------
    # Retrieve a particular global mediation policy
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:mediation_policy_view
      summary: Get a Global Mediation Policy
      description: |
        This operation can be used to retrieve a particular global mediation policy.
      tags:
        - Mediation Policy (Individual)
    #-----------------------------------------------------
    # Delete the mediation policy
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:mediation_policy_create
      summary: Delete a Global Mediation Policy
      description: |
        This operation can be used to delete an existing global mediation policy providing the Id of the mediation policy.
      tags:
        - Mediation Policy (Individual)
    #-----------------------------------------------------
    # Update a mediation policy
    #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:mediation_policy_create
      summary: Update a Global Mediation Policy
      description: |
        This operation can be used to update an existing global mediation policy.
      tags:
        - Mediation Policy (Individual)
  ######################################################
  # The "Subscription Throttling Policy Collection" resource API
  ######################################################
  '/throttling/policies/subscription':

    #-----------------------------------------------------
    # Retrieve all Subscription level policies
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get all Subscription Throttling Policies
      description: |
        This operation can be used to retrieve all Subscription level throttling policies.
      tags:
        - Subscription Policy (Collection)
    #-----------------------------------------------------
    # Add a Subscription level Throttling Policy
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Add a Subscription Throttling Policy
      description: |
        This operation can be used to add a Subscription level throttling policy specifying the details of the policy in the payload.
      tags:
        - Subscription Policy (Collection)
  ######################################################
  # The "Individual Subscription Throttling Policy" resource API
  ######################################################
  '/throttling/policies/subscription/{policyId}':

    #-----------------------------------------------------
    # Retrieve a certain Subscription Policy
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get a Subscription Policy
      description: |
        This operation can be used to retrieves subscription level throttling policy by specifying the Id of the policy as a path paramter
      tags:
        - Subscription Policy (Individual)
    #-----------------------------------------------------
    # Delete a Subscription level throttling policy
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Delete a Subscription Policy
      description: |
        This operation can be used to delete a subscription level throttling policy by specifying the Id of the policy as a path paramter.
      tags:
        - Subscription Policy (Individual)
    #-----------------------------------------------------
    # Update a Subscription Throttling Policy
    #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Update a Subscription Policy
      description: |
        Updates an existing subscription level throttling policy.
      tags:
        - Subscription Policy (Individual)
  ######################################################
  # The "Custom Rule Collection" resource API
  ######################################################
  '/throttling/policies/custom':

    #-----------------------------------------------------
    # Retrieve all Custom Rules
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get all Custom Rules
      description: |
        Retrieves all custom rules.

        **NOTE:**
        * Only super tenant users are allowed for this operation.
      tags:
        - Custom Rules (Collection)
    #-----------------------------------------------------
    # Add a Custom Rule
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Add a Custom Rule
      description: |
        Adds a new custom rule.

        **NOTE:**
        * Only super tenant users are allowed for this operation.
      tags:
        - Custom Rules (Collection)
  ######################################################
  # The "Individual Custom Rule" resource API
  ######################################################
  '/throttling/policies/custom/{ruleId}':

    #-----------------------------------------------------
    # Retrieve a certain Custom Rule
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get a Custom Rule
      description: |
        Retrieves a custom rule. We need to provide the policy Id as a path parameter.

        **NOTE:**
        * Only super tenant users are allowed for this operation.
      tags:
        - Custom Rules (Individual)
    #-----------------------------------------------------
    # Delete a Custom Rule
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Delete a Custom Rule
      description: |
        Delete a custom rule. We need to provide the Id of the policy as a path parameter.

        **NOTE:**
        * Only super tenant users are allowed for this operation.
      tags:
        - Custom Rules (Individual)
    #-----------------------------------------------------
    # Update a Custom Rule
    #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Update a Custom Rule
      description: |
        Updates an existing custom rule.

        **NOTE:**
        * Only super tenant users are allowed for this operation.
      tags:
        - Custom Rules (Individual)
  ######################################################
  # The "Advanced Throttling Policy Collection" resource API
  ######################################################
  '/throttling/policies/advanced':

    #-----------------------------------------------------
    # Retrieve all Advanced level policies
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get all Advanced Throttling Policies
      description: |
        Retrieves all existing advanced throttling policies.
      tags:
        - Advanced Policy (Collection)
    #-----------------------------------------------------
    # Add an Advanced level throttling policy
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Add an Advanced Throttling Policy
      description: |
        Add a new advanced throttling policy.
      tags:
        - Advanced Policy (Collection)
  ######################################################
  # The "Individual Advanced Throttling Policy" resource API
  ######################################################
  '/throttling/policies/advanced/{policyId}':

    #-----------------------------------------------------
    # Retrieve a certain Advanced Throttling Policy
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_view
      summary: Get an Advanced Throttling Policy
      description: |
        Retrieves an advanced throttling policy.
      tags:
        - Advanced Policy (Individual)
    #-----------------------------------------------------
    # Delete an Advanced level throttling policy
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Delete an Advanced Throttling Policy
      description: |
        Deletes an advanced throttling policy.
      tags:
        - Advanced Policy (Individual)
    #-----------------------------------------------------
    # Update an Advanced Throttling Policy
    #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tier_manage
      summary: Update an Advanced Throttling Policy
      description: |
        Updates an existing Advanced throttling policy.
      tags:
        - Advanced Policy (Individual)
  ######################################################
  # The "Blocking Condition Collection" resource API
  ######################################################
  '/throttling/blacklist':

    #-----------------------------------------------------
    # Retrieve all Blocking conditions
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bl_view
      summary: Get all Blocking Condtions
      description: |
        Retrieves all existing blocking condtions.
      tags:
        - Blacklist (Collection)
    #-----------------------------------------------------
    # Add a Custom Rule
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bl_manage
      summary: Add a Blocking Condition
      description: |
        Adds a new blocking condition.
      tags:
        - Blacklist (Collection)
  ######################################################
  # The "Individual Blocking Condition" resource API
  ######################################################
  '/throttling/blacklist/{conditionId}':

    #-----------------------------------------------------
    # Retrieve a Blocking condition
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bl_view
      summary: Get a Blocking Condition
      description: |
        Retrieves a Blocking Condition providing the condition Id
      tags:
        - Blacklist (Individual)
    #-----------------------------------------------------
    # Delete a Blocking condition
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bl_manage
      summary: Delete a Blocking Condition
      description: |
        Deletes an existing blocking condition
      tags:
        - Blacklist (Individual)
    #-----------------------------------------------------
    # Update a blocking condition status
    #-----------------------------------------------------
    patch:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bl_manage
      summary: Update a Blocking Condition
      description: |
        Update a blocking condition by Id
      tags:
        - Blacklist (Individual)
  ######################################################
  # The "Application Collection" resource APIs
  ######################################################
  /applications:

    #-----------------------------------------------------
    # Retrieve a list of all applications of a certain subscriber
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:app_owner_change
            - apim:app_import_export
      summary: |
        Retrieve/Search Applications
      description: |
        This operation can be used to retrieve list of applications owned by the given user, If no user
        is provided, the applications owned by the user associated with the provided access token will be returned.
      tags:
        - Application (Collection)
  ######################################################
  # The "Individual Application" resource APIs
  ######################################################
  /applications/{applicationId}:

    #-----------------------------------------------------
    # Delete a certain application
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:app_import_export
      summary: |
        Delete an Application
      description: |
        This operation can be used to delete an application by specifying its id.
      tags:
        - Applications
  ######################################################
  # The "Change Owner" Function resource API
  ######################################################
  /applications/{applicationId}/change-owner:

    #-----------------------------------------------------
    # Change the owner of an Application
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:app_owner_change
      summary: Change Application Owner
      description: |
        This operation is used to change the owner of an Application.
        In order to change the owner of an application, we need to pass the new application owner as a query parameter
      tags:
        - Application
  ######################################################
  # Export Application Resource API
  ######################################################
  /export/applications:

    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:app_import_export
      summary: Export an Application
      description: |
        This operation can be used to export the details of a particular application as a zip file.
      tags:
        - Application (Individual)
  ######################################################
  # Import Application Resource API
  ######################################################
  /import/applications:

    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:app_import_export
      summary: Import an Application
      description: |
        This operation can be used to import an application.
      tags:
        - Application (Individual)
  ######################################################
  # Import Resource API
  ######################################################
  /import/api:

    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_import_export
      summary: Import an API
      description: |
        This operation can be used to import an API.
      tags:
        - API (Individual)
  ######################################################
  # Export Resource API
  ######################################################
  /export/api:

    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_import_export
      summary: Export an API
      description: |
        This operation can be used to export the details of a particular API as a zip file.
      tags:
        - API (Individual)
  ######################################################
  # Import Resource API Product
  ######################################################
  /import/api-product:

    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_product_import_export
      summary: Import an API Product
      description: |
        This operation can be used to import an API Product.
      tags:
        - API Product (Individual)
  ######################################################
  # Export Resource API Product
  ######################################################
  /export/api-product:

    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_product_import_export
      summary: Export an API Product
      description: |
        This operation can be used to export the details of a particular API Product as a zip file.
      tags:
        - API Product (Individual)
  ######################################################
  # The "Label" resource API
  ######################################################
  /labels:

    #-----------------------------------------------------
    # Retrieve all labels
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:label_read
      summary: Get all registered Labels
      description: |
        Get all Registered Labels
      tags:
        - Label Collection
    #-----------------------------------------------------
    # Add a Label
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:label_manage
      summary: Add a Label
      description: |
        Add a new gateway label
      tags:
        - Label
  ######################################################
  # The Bot Detection Data API resources
  ######################################################

  /bot-detection-data:
    #-----------------------------------------------------
    # Get all bot detection data
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:bot_data
      operationId: getBotDetectionData
      summary: |
        Get all Bot Detected Data
      description: |
        Get all bot detected data
      tags:
        - Bot Detection Data
  ######################################################
  # The "Individual label" resource APIs
  ######################################################

  /labels/{labelId}:

    #-----------------------------------------------------
    # Update a Label
    #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:label_manage
      summary: Update a Label
      description: |
        Update a Label by label Id
      tags:
        - Label
    #-----------------------------------------------------
    # Delete a Label
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:label_manage
      summary: Delete a Label
      description: |
        Delete a Label by label Id
      tags:
        - Label
  ######################################################
  # The "Monetization" resource APIs
  ######################################################

  /monetization/publish-usage:

    #-----------------------------------------------------
    # Publish monetization related usage records
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:monetization_usage_publish
      summary: Publish Usage Records
      description: |
        Publish usage records of monetized APIs
      tags:
        - Monetization (Collection)
  /monetization/publish-usage/status:

    #-----------------------------------------------------
    # Retrieve the status monetization usage publsih job
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:monetization_usage_publish
      summary: Get the Status of Monetization Usage Publisher
      description: |
        Get the status of monetization usage publisher
      tags:
        - Monetization (Collection)
  ######################################################
  # The "Workflow Collection" resource APIs
  ######################################################
  '/workflows':

    #---------------------------------------------------
    # Retrieve a list of all workflow pending processes
    #---------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_workflow_view
      summary: |
        Retrieve All Pending Workflow Processes
      description: |
        This operation can be used to retrieve list of workflow pending processes.
      tags:
        - Workflow (Collection)
  #----------------------------------------------------------------
  # Retrieve workflow requests according to the external reference
  #----------------------------------------------------------------
  '/workflows/{externalWorkflowRef}':

    #-----------------------------------------------------
    # Retrieve the Details of a workflow pendding process
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_workflow_view
      summary: |
        Get Pending Workflow Details by External Workflow Reference
      description: |
        Using this operation, you can retrieve complete details of a pending workflow request that either belongs to application creation, application subscription, application registration, api state change, user self sign up.. You need to provide the External_Workflow_Reference of the workflow Request to retrive it.

      tags:
        - Workflows (Individual)
  ######################################################
  # The "Workflow approval" resource API
  ######################################################
  /workflows/update-workflow-status:

    #-------------------------------------------------------------------
    # Resume the workflow by approving or rejecting the workflow request
    #-------------------------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:api_workflow_approve
      summary: Update Workflow Status
      description: |
        This operation can be used to approve or reject a workflow task.
      tags:
        - Workflows (Individual)
  ######################################################
  # The Tenant Info resource API
  ######################################################
  /tenant-info/{username}:
    #--------------------------------------------------------
    # Retrieve tenant information of the given username
    #--------------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tenantInfo
      summary: |
        Get Tenant Id of User
      description: |
        This operation is to get tenant id of the provided user
      operationId: getTenantInfoByUsername
      tags:
        - Tenants
  ######################################################
  # The Custom URL Info resource API
  ######################################################
  /custom-urls/{tenantDomain}:
    #----------------------------------------------------------
    # Retrieve custom url information of the given tenant domain
    #----------------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tenantInfo
      summary: |
        Get Custom URL Info of a Tenant Domain
      description: |
        This operation is to get custom-url information of the provided tenant-domain
      operationId: getCustomUrlInfoByTenantDomain
      tags:
        - Tenants
  ######################################################
  # The "Category Collection" resource API
  ######################################################
  /api-categories:

    #-----------------------------------------------------
    # Retrieve all categories
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Get all API Categories
      description: |
        Get all API categories
      tags:
        - API Category (Collection)
    #-----------------------------------------------------
    # Add a Category
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Add API Category
      description: |
        Add a new API category
      tags:
        - API Category (Individual)
  ######################################################
  # The "Individual Category" resource APIs
  ######################################################

  /api-categories/{apiCategoryId}:

    #-----------------------------------------------------
    # Update a Category
    #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Update an API Category
      description: |
        Update an API Category by category Id
      tags:
        - API Category (Individual)
    #-----------------------------------------------------
    # Delete an API Category
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Delete an API Category
      description: |
        Delete an API Category by API Category Id
      tags:
        - API Category (Individual)
  ######################################################
  # The Admin settings List
  ######################################################
  /settings:
    #-----------------------------------------------------
    # Retrieve admin settings
    #-----------------------------------------------------
    get:
      summary: Retreive Admin Settings
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_settings
      description: |
        Retreive admin settings
      tags:
        - Settings
  ####################################################
  # The Admin alert  management REST API
  ####################################################
  '/alert-types':
    #--------------------------------------------------
    # Retrieve the list of admin alert types
    #--------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      operationId: getAdminAlertTypes
      summary: |
        Get all Admin Alert Types
      description: |
        This operation is used to get the list of supportd alert types for the apim admin dashboard
      tags:
        - Alerts
  '/alert-subscriptions':
    #--------------------------------------------------
    # Retrieve the list of alerts subscribed by the admin user
    #--------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      summary: |
        Get Subscribed Alert Types
      operationId: getSubscribedAlertTypes
      description: |
        This operation is used to get the list of subscribed alert types by the user.
      tags:
        - Alert Subscriptions
    #--------------------------------------------------
    # Subscribe to the selected alert types by the user.
    #--------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      summary: |
        Subscribe to an Admin Alert
      operationId: subscribeToAlerts
      description: |
        This operation is used to subscribe to admin alerts
      tags:
        - Alert Subscriptions
    #--------------------------------------------------
    # Unsubscribe the user from all the admin alerts types
    #--------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      summary: |
        Unsubscribe User from all Admin Alerts
      operationId: unsubscribeAllAlerts
      description: |
        This operation is used to unsubscribe the respective user from all the admin alert types.
      tags:
        - Alert Subscriptions
  ###########################################################
  # The Bot Detection Alert Subscription Management resources
  ###########################################################

  '/alert-subscriptions/bot-detection':
    #------------------------------------------------------------
    # Retrieve the list of subscriptions for bot detection alerts
    #------------------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      operationId: getBotDetectionAlertSubscriptions
      summary: |
        Get Subscriptions for Bot Detection
      description: |
        Get the list of subscriptions which are subscribed to receive email alerts for bot detection
      tags:
        - Bot Detection Alert Subscriptions
    #-----------------------------------------------------
    # Subscribe for bot detection alerts
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      operationId: subscribeForBotDetectionAlerts
      summary: Subscribe for Bot Detection Alerts
      description: |
        Register a subscription for bot detection alerts
      tags:
        - Bot Detection Alert Subscriptions
  '/alert-subscriptions/bot-detection/{uuid}':
    #-----------------------------------------------------
    # Unsubscribe from bot detection alerts
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_alert_manage
      operationId: unsubscribeFromBotDetectionAlerts
      summary: Unsubscribe from bot detection alerts.
      description: |
        Delete a Bot Detection Alert Subscription
      tags:
        - Bot Detection Alert Subscriptions
  ######################################################
  # System scopes
  ######################################################
  /system-scopes/{scopeName}:
    #-----------------------------------------------------
    # Retrieve scope settings
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:scope_manage
      operationId: systemScopesScopeNameGet
      summary: Retrieve Scopes for a Particular User
      description: |
        This operation will return the scope list of particular user
        In order to get it, we need to pass the userId as a query parameter
      tags:
        - System Scopes
  /system-scopes:
    #--------------------------------------------------
    # Retrieve the list of role scope mapping
    #--------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:scope_manage
            - apim:admin
      operationId: systemScopesGet
      summary: |
        Get Role Scope Mappings
      description: |
        This operation is used to get the list of role scope mapping from tenant-conf for the apim admin dashboard
      tags:
        - System Scopes
    #--------------------------------------------------
    # Update the roles for scopes
    #--------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:scope_manage
      summary: |
        Update Roles For Scope
      operationId: updateRolesForScope
      description: |
        This operation is used to update the roles for all scopes
      tags:
        - System Scopes
  ######################################################
  # The 'Role Alias' Collection API Resource
  ######################################################
  /system-scopes/role-aliases:
    #-----------------------------------------------------
    # Retrieve role alias mappings for system scope roles
    #-----------------------------------------------------
    get:
      summary: Retrieve Role Alias Mappings
      security:
        - OAuth2Security:
            - apim:admin
            - apim:scope_manage
      description: |
        This operation can be used to retreive role alias mapping
      tags:
        - System Scopes
    #-----------------------------------------------------
    # Add a new role alias mapping for system roles
    #-----------------------------------------------------
    put:
      summary: Add a New Role Alias
      security:
        - OAuth2Security:
            - apim:scope_manage
            - apim:admin
      description: |
        This operation can be used to add a new role alias mapping for system scope roles
      tags:
        - System Scopes
  ######################################################
  # The Tenant Theme resource APIs
  ######################################################
  /tenant-theme:
    #-----------------------------------------------------
    # Export Tenant Theme
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tenant_theme_manage
      operationId: exportTenantTheme
      summary: Export a DevPortal Tenant Theme
      description: |
        This operation can be used to export a DevPortal tenant theme as a zip file.
      tags:
        - Tenant Theme
    #-----------------------------------------------------
    # Import Tenant Theme
    #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:tenant_theme_manage
      operationId: importTenantTheme
      summary: Import a DevPortal Tenant Theme
      description: |
        This operation can be used to import a DevPortal tenant theme.
      tags:
        - Tenant Theme
  ######################################################
  # The "Key Manager Collection" resource API
  ######################################################
  /key-managers:

    #-----------------------------------------------------
    # Retrieve all key managers
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Get all Key managers
      description: |
        Get all Key managers
      tags:
        - Key Manager (Collection)
    #-----------------------------------------------------
    # Add a Key Manager
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Add a new API Key Manager
      description: |
        Add a new API Key Manager
      tags:
        - Key Manager (Collection)
  ######################################################
  # The "Individual KeyManager" resource APIs
  ######################################################

  /key-managers/{keyManagerId}:

    #-----------------------------------------------------
    # Retrieve a certain Key Manager Resource
    #-----------------------------------------------------
    get:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Get a Key Manager Configuration
      description: |
        Retrieve a single Key Manager Configuration. We should provide the Id of the KeyManager as a path parameter.
      tags:
        - Key Manager (Individual)
    #-----------------------------------------------------
    # Update a Key Manager
    #-----------------------------------------------------
    put:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Update a Key Manager
      description: |
        Update a Key Manager by keyManager id
      tags:
        - Key Manager (Individual)
    #-----------------------------------------------------
    # Delete a Key Manager
    #-----------------------------------------------------
    delete:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Delete a Key Manager
      description: |
        Delete a Key Manager by keyManager id
      tags:
        - Key Manager (Individual)
  ######################################################
  # The "Key Manager Collection" resource API
  ######################################################
  /key-managers/discover:

    #-----------------------------------------------------
    # Retrieve Information from Well-known Endpoint.
    #-----------------------------------------------------
    post:
      security:
        - OAuth2Security:
            - apim:admin
            - apim:admin_operations
      summary: Retrieve Well-known information from Key Manager Well-known Endpoint
      description: |
        Retrieve well-known information from key manager's well-known endpoint
      tags:
        - Key Manager (Collection)
######################################################
# Parameters - required by some of the APIs above
######################################################
######################################################
# The response schemas used by the API resources
######################################################
######################################################
# The resources used by some of the APIs above within the message body
######################################################
#-----------------------------------------------------
# The GraphQL Query resource
#-----------------------------------------------------
  GraphQLQuery:
    title: GraphQL Query
    properties:
      graphQLMaxComplexity:
        type: integer
        description: Maximum Complexity of the GraphQL query
      graphQLMaxDepth:
        type: integer
        description: Maximum Depth of the GraphQL query
  #-----------------------------------------------------
  # The Subscription Throttling Policy List resource
  #-----------------------------------------------------
  SubscriptionThrottlePolicyList:
    title: Subscription Level Throttling Policy List
    properties:
      count:
        type: integer
        description: |
          Number of Subscription Throttling Policies returned.
      list:
        type: array
        items:
          $ref: '#/definitions/SubscriptionThrottlePolicy'

  #-----------------------------------------------------
  # The Custom Rule resource
  #-----------------------------------------------------
  CustomRule:
    title: Custom Rule
    allOf:
      - $ref: '#/definitions/ThrottlePolicy'
      - required:
          - siddhiQuery
          - keyTemplate
        properties:
          siddhiQuery:
            type: string
            description: Siddhi query which represents the custom throttling policy
          keyTemplate:
            type: string
            description: The specific combination of attributes that are checked in the policy.
  #-----------------------------------------------------
  # The Custom Rule List resource
  #-----------------------------------------------------
  CustomRuleList:
    title: Custom Rule List
    properties:
      count:
        type: integer
        description: |
          Number of Custom Rules returned.
      list:
        type: array
        items:
          $ref: '#/definitions/CustomRule'

  #-----------------------------------------------------
  # The Conditional Group resource
  #-----------------------------------------------------
  ConditionalGroup:
    title: Conditional Groups for Throttling
    required:
      - limit
      - conditions
    properties:
      description:
        type: string
        description: Description of the Conditional Group
      conditions:
        type: array
        items:
          $ref: '#/definitions/ThrottleCondition'
        description: |
          Individual throttling conditions. They can be defined as either HeaderCondition, IPCondition, JWTClaimsCondition, QueryParameterCondition
          Please see schemas of each of those throttling condition in Definitions section.
      limit:
        $ref: '#/definitions/ThrottleLimit'

  #-----------------------------------------------------
  # The Throttling Condition resource
  #-----------------------------------------------------
  ThrottleCondition:
    title: Throttling Conditions
    description: Conditions used for Throttling
    required:
      - type
    properties:
      type:
        type: string
        enum:
          - HEADERCONDITION
          - IPCONDITION
          - JWTCLAIMSCONDITION
          - QUERYPARAMETERCONDITION
        description: |
          Type of the throttling condition. Allowed values are "HEADERCONDITION", "IPCONDITION", "JWTCLAIMSCONDITION"
          and "QUERYPARAMETERCONDITION".
      invertCondition:
        type: boolean
        default: false
        description: |
          Specifies whether inversion of the condition to be matched against the request.

          **Note:** When you add conditional groups for advanced throttling policies, this paramater should have the
          same value ('true' or 'false') for the same type of conditional group.
      headerCondition:
        $ref: '#/definitions/HeaderCondition'
      ipCondition:
        $ref: '#/definitions/IPCondition'
      jwtClaimsCondition:
        $ref: '#/definitions/JWTClaimsCondition'
      queryParameterCondition:
        $ref: '#/definitions/QueryParameterCondition'

  #-----------------------------------------------------
  # The Throttling HTTP Header Condition resource
  #-----------------------------------------------------
  HeaderCondition:
    title: HTTP Header based throttling condition
    required:
      - headerName
      - headerValue
    properties:
      headerName:
        type: string
        description: Name of the header
      headerValue:
        type: string
        description: Value of the header

  #-----------------------------------------------------
  # The Throttling IP Condition resource
  #-----------------------------------------------------
  IPCondition:
    title: IP based throttling condition
    required:
      - specificIP
    properties:
      ipConditionType:
        type: string
        enum:
          - IPRANGE
          - IPSPECIFIC
        description: Type of the IP condition. Allowed values are "IPRANGE" and "IPSPECIFIC"
      specificIP:
        type: string
        description: Specific IP when "IPSPECIFIC" is used as the ipConditionType
      startingIP:
        type: string
        description: Staring IP when "IPRANGE" is used as the ipConditionType
      endingIP:
        type: string
        description: Ending IP when "IPRANGE" is used as the ipConditionType

  #-----------------------------------------------------
  # The JWT Claims Condition resource
  #-----------------------------------------------------
  JWTClaimsCondition:
    title:  JWT claim attibute based throttling condition
    required:
      - claimUrl
      - attribute
    properties:
      claimUrl:
        type: string
        description: JWT claim URL
      attribute:
        type: string
        description: Attribute to be matched

  #-----------------------------------------------------
  # The Query Parameter Condition resource
  #-----------------------------------------------------
  QueryParameterCondition:
    title: Query parameter based throttling condition
    required:
      - parameterName
      - parameterValue
    properties:
      parameterName:
        type: string
        description: Name of the query parameter
      parameterValue:
        type: string
        description: Value of the query parameter to be matched

  #-----------------------------------------------------
  # The Throttling Limit Base resource
  #-----------------------------------------------------
  ThrottleLimitBase:
    title: Throttle Limit Base
    required:
      - timeUnit
      - unitTime
    properties:
      timeUnit:
        type: string
        description: Unit of the time. Allowed values are "sec", "min", "hour", "day"
      unitTime:
        type: integer
        default: 0
        description: Time limit that the throttling limit applies.
  #-----------------------------------------------------
  # The Throttling Limit resource
  #-----------------------------------------------------
  ThrottleLimit:
    title: Throttle Limit
    required:
      - type
    properties:
      type:
        type: string
        enum:
          - REQUESTCOUNTLIMIT
          - BANDWIDTHLIMIT
        description: |
          Type of the throttling limit. Allowed values are "REQUESTCOUNTLIMIT" and "BANDWIDTHLIMIT".
          Please see schemas of "RequestCountLimit" and "BandwidthLimit" throttling limit types in
          Definitions section.
      requestCount:
        $ref: '#/definitions/RequestCountLimit'
      bandwidth:
        $ref: '#/definitions/BandwidthLimit'

  #-----------------------------------------------------
  # The Monetization Info resource
  #-----------------------------------------------------
  MonetizationInfo:
    title: API monetization details object
    required:
      - monetizationPlan
      - properties
    properties:
      monetizationPlan:
        type: string
        description: Flag to indicate the monetization plan
        enum:
          - FixedRate
          - DynamicRate
      properties:
        type: object
        description: Map of custom properties related to each monetization plan
        additionalProperties:
          type: string

  #-----------------------------------------------------
  # The Throttling Bandwidth Limit resource
  #-----------------------------------------------------
  BandwidthLimit:
    title: Bandwidth Limit object
    allOf:
      - $ref: '#/definitions/ThrottleLimitBase'
      - required:
          - dataAmount
          - dataUnit
        properties:
          dataAmount:
            type: integer
            format: int64
            description: Amount of data allowed to be transfered
          dataUnit:
            type: string
            description: Unit of data allowed to be transfered. Allowed values are "KB", "MB" and "GB"
  #-----------------------------------------------------
  # The Throttling Request Count Limit resource
  #-----------------------------------------------------
  RequestCountLimit:
    title: Request Count Limit object
    allOf:
      - $ref: '#/definitions/ThrottleLimitBase'
      - required:
          - requestCount
        properties:
          requestCount:
            type: integer
            format: int64
            description: Maximum number of requests allowed
  #-----------------------------------------------------
  # The Throttling Blocking Condition resource
  #-----------------------------------------------------
  BlockingCondition:
    title: Blocking Conditions
    description: Blocking Conditions
    required:
      - conditionType
      - conditionValue
    properties:
      conditionId:
        type: string
        description: Id of the blocking condition
      conditionType:
        type: string
        description: Type of the blocking condition
        enum:
          - API
          - APPLICATION
          - IP
          - IPRANGE
          - USER
      conditionValue:
        type: object
        description: Value of the blocking condition
      conditionStatus:
        type: boolean
        description: Status of the blocking condition
  #-----------------------------------------------------
  # The Throttling Blocking Condition List resource
  #-----------------------------------------------------
  BlockingConditionList:
    title: Blocking Conditions List
    properties:
      count:
        type: integer
        description: |
          Number of Blocking Conditions returned.
      list:
        type: array
        items:
          $ref: '#/definitions/BlockingCondition'
  #-----------------------------------------------------
  # The Throttling Blocking Condition Status resource
  #-----------------------------------------------------
  BlockingConditionStatus:
    title: Blocking Conditions Status
    description: Blocking Conditions Status
    required:
      - conditionStatus
    properties:
      conditionId:
        type: string
        description: Id of the blocking condition
      conditionStatus:
        type: boolean
        description: Status of the blocking condition
  #-----------------------------------------------------
  # Custom Attribute object
  #-----------------------------------------------------
  CustomAttribute:
    title: Name-Value pair
    required:
      - name
      - value
    properties:
      name:
        type: string
        description: Name of the custom attribute
      value:
        type: string
        description: Value of the custom attribute
  #-----------------------------------------------------
  # The Mediation List resource
  #-----------------------------------------------------
  mediationList:
    title: Mediation List
    properties:
      count:
        type: integer
        description: |
          Number of mediation sequences returned.
      next:
        type: string
        description: |
          Link to the next subset of sequences qualified.
          Empty if no more sequences are to be returned.
      previous:
        type: string
        description: |
          Link to the previous subset of sequences qualified.
          Empty if current subset is the first subset returned.
      list:
        type: array
        items:
          $ref: '#/definitions/MediationInfo'

  #-----------------------------------------------------
  # The MediationInfo resource
  #-----------------------------------------------------
  MediationInfo:
    title: MediationInfo
    required:
      - name
      - type
      - id
    properties:
      name:
        type: string
      id:
        type: string
      type:
        type: string
        enum:
          - in
          - out
          - fault
  #-----------------------------------------------------
  # The Mediation resource
  #-----------------------------------------------------
  Mediation:
    title: Mediation
    required:
      - name
      - type
      - config
    properties:
      id:
        type: string
        readOnly: true
      name:
        type: string
      type:
        type: string
        enum:
          - in
          - out
          - fault
      config:
        type: string
  #-----------------------------------------------------
  # The Application List resource
  #-----------------------------------------------------
  ApplicationList:
    title: Application List
    properties:
      count:
        type: integer
        description: |
          Number of applications returned.
      next:
        type: string
        description: |
          Link to the next subset of resources qualified.
          Empty if no more resources are to be returned.
      previous:
        type: string
        description: |
          Link to the previous subset of resources qualified.
          Empty if current subset is the first subset returned.
      list:
        type: array
        items:
          $ref: '#/definitions/ApplicationInfo'

  #-----------------------------------------------------
  # The Application Info resource
  #-----------------------------------------------------
  ApplicationInfo:
    title: Application info object with basic application details
    properties:
      applicationId:
        type: string
      name:
        type: string
      owner:
        type: string
      status:
        type: string
      groupId:
        type: string
  #-----------------------------------------------------
  # The API Info List resource
  #-----------------------------------------------------
  APIInfoList:
    title: API Info List
    properties:
      count:
        type: integer
        description: |
          Number of API Info objects returned.
      list:
        type: array
        items:
          $ref: '#/definitions/APIInfo'

  #-----------------------------------------------------
  # The API Info resource
  #-----------------------------------------------------
  APIInfo:
    title: API info object with basic API details
    properties:
      name:
        type: string
        description: The name of the API.
      version:
        type: string
        description: The version of the API
      provider:
        type: string
        description: The provider of the API
  #-----------------------------------------------------
  # The Label resource
  #-----------------------------------------------------
  Label:
    title: Label
    required:
      - name
    properties:
      id:
        type: string
        readOnly: true
      name:
        type: string
        minLength: 1
        maxLength: 255
      description:
        type: string
        maxLength: 1024
      accessUrls:
        type: array
        items:
          type: string
  #-----------------------------------------------------
  # The Label List resource
  #-----------------------------------------------------
  LabelList:
    title: Label List
    properties:
      count:
        type: integer
        description: |
          Number of Labels returned.
      list:
        type: array
        items:
          $ref: '#/definitions/Label'

  #-----------------------------------------------------
  # The publish status resource
  #-----------------------------------------------------
  PublishStatus:
    title: Usage publish status
    properties:
      status:
        type: string
        description: Status of the usage publish request
      message:
        type: string
        description: detailed message of the status
  #-----------------------------------------------------
  # The publish status resource
  #-----------------------------------------------------
  MonetizationUsagePublishInfo:
    title: Usage publish status
    properties:
      state:
        type: string
        description: State of usage publish job
      status:
        type: string
        description: Status of usage publish job
      startedTime:
        type: string
        description: Timestamp of the started time of the Job
      lastPublsihedTime:
        type: string
        description: Timestamp of the last published time
  #-----------------------------------------------------
  # The workflow response resource
  #-----------------------------------------------------
  Workflow:
    title: workflow
    required:
      - status
    properties:
      status:
        description: |
          This attribute declares whether this workflow task is approved or rejected.
        type: string
        enum:
          - APPROVED
          - REJECTED
      attributes:
        description: |
          Custom attributes to complete the workflow task
        type: object
        additionalProperties:
          type: string
      description:
        type: string
  #-----------------------------------------------------
  # The Tenant info response resource
  #-----------------------------------------------------
  TenantInfo:
    title: Tenant information
    type: object
    description: The tenant information of the user
    properties:
      username:
        type: string
      tenantDomain:
        type: string
      tenantId:
        type: integer
  #-----------------------------------------------------
  # The CustomURL info response resource
  #-----------------------------------------------------
  CustomUrlInfo:
    title: Custom url information
    type: object
    description: The custom url information of the tenant domain
    properties:
      tenantDomain:
        type: string
      tenantAdminUsername:
        type: string
      enabled:
        type: boolean
      devPortal:
        type: object
        properties:
          url:
            type: string
  #-----------------------------------------------------
  # The Category resource
  #-----------------------------------------------------
  APICategory:
    title: API Category
    required:
      - name
    properties:
      id:
        type: string
        readOnly: true
      name:
        type: string
        minLength: 1
        maxLength: 255
      description:
        type: string
        maxLength: 1024
      numberOfAPIs:
        type: integer
        readOnly: true
  #-----------------------------------------------------
  # The Category List resource
  #-----------------------------------------------------
  APICategoryList:
    title: API Category List
    properties:
      count:
        type: integer
        description: |
          Number of API categories returned.
      list:
        type: array
        items:
          $ref: '#/definitions/APICategory'

  #-----------------------------------------------------
  # The File Information resource
  #-----------------------------------------------------
  FileInfo :
    title: File Information including meta data
    properties:
      relativePath:
        type: string
        description: relative location of the file (excluding the base context and host of the Admin API)
      mediaType:
        type: string
        description: media-type of the file
  #-----------------------------------------------------
  # The Settings resource
  #-----------------------------------------------------
  Settings:
    title: Settings
    properties:
      scopes:
        type: array
        items:
          type: string
      keyManagerConfiguration:
        type: array
        items:
          properties:
            type:
              type: string
            displayName:
              type: string
            defaultConsumerKeyClaim:
              type: string
            defaultScopesClaim:
              type: string
            configurations:
              type: array
              items:
                $ref: '#/definitions/KeyManagerConfiguration'
      analyticsEnabled:
        type: boolean
        description: To determine whether analytics is enabled or not
  #-----------------------------------------------------
  # The Scope Role Mapping List resource
  #-----------------------------------------------------
  ScopeList:
    title: Scope Role Mapping List
    properties:
      count:
        type: integer
        description: |
          Number of scopes available for tenant.
        readOnly: true
      list:
        type: array
        items:
          $ref: '#/definitions/Scope'

  #-----------------------------------------------------
  # The Scope resource
  #-----------------------------------------------------
  Scope:
    title: Scope Role
    properties:
      tag:
        type: string
        description: |
          Portal name.
      name:
        type: string
        description: |
          Scope name.
      description:
        type: string
        description: |
          About scope.
      roles:
        type: array
        items:
          type: string
        description: |
          Roles for the particular scope.
  #-----------------------------------------------------
  # The KeyManager Well Known Response.
  #-----------------------------------------------------
  KeyManagerWellKnownResponse:
    title: Key Manager Well-Known Response.
    properties:
      valid:
        type: boolean
        default: false
      value:
        $ref: '#/definitions/KeyManager'

  #-----------------------------------------------------
  # The KeyManager resource
  #-----------------------------------------------------
  KeyManager:
    title: Key Manager
    required:
      - name
      - type
    properties:
      id:
        type: string
        readOnly: true
      name:
        type: string
        minLength: 1
        maxLength: 100
      displayName:
        type: string
        description: |
          display name of Key Manager to  show in UI
        maxLength: 100
      type:
        type: string
        minLength: 1
        maxLength: 45
      description:
        type: string
        maxLength: 256
      wellKnownEndpoint:
        description: |
          Well-Known Endpoint of Identity Provider.
        type: string
      introspectionEndpoint:
        type: string
      clientRegistrationEndpoint:
        type: string
      tokenEndpoint:
        type: string
      revokeEndpoint:
        type: string
      userInfoEndpoint:
        type: string
      authorizeEndpoint:
        type: string
      certificates:
        type: object
        properties:
          type:
            type: string
            enum:
              - JWKS
              - PEM
          value:
            type: string
      issuer:
        type: string
      scopeManagementEndpoint:
        type: string
      availableGrantTypes:
        type: array
        items:
          type: string
      enableTokenGeneration:
        type: boolean
      enableTokenEncryption:
        type: boolean
        default: false
      enableTokenHashing:
        type: boolean
        default: false
      enableMapOAuthConsumerApps:
        type: boolean
        default: false
      enableOAuthAppCreation:
        type: boolean
        default: false
      enableSelfValidationJWT:
        type: boolean
        default: true
      claimMapping:
        type: array
        items:
          $ref: '#/definitions/ClaimMappingEntry'
      consumerKeyClaim:
        type: string
      scopesClaim:
        type: string
      tokenValidation:
        type: array
        items:
          $ref: '#/definitions/TokenValidation'
      enabled:
        type: boolean
      additionalProperties:
        type: object
  #-----------------------------------------------------
  # The KeyManager resource
  #-----------------------------------------------------
  KeyManagerInfo:
    title: Key Manager Info
    required:
      - name
      - type
    properties:
      id:
        type: string
      name:
        type: string
      type:
        type: string
      description:
        type: string
      enabled:
        type: boolean
  #-----------------------------------------------------
  # The KeyManager resource
  #-----------------------------------------------------
  KeyManagerConfiguration:
    title: Key Manager Configuration
    properties:
      name:
        type: string
      label:
        type: string
      type:
        type: string
      required:
        type: boolean
      mask:
        type: boolean
      multiple:
        type: boolean
      tooltip:
        type: string
      default:
        type: object
      values:
        type: array
        items:
          type: object

  #-----------------------------------------------------
  # The KeyManager List resource
  #-----------------------------------------------------
  KeyManagerList:
    title: Key Manager List
    properties:
      count:
        type: integer
        description: |
          Number of Key managers returned.
      list:
        type: array
        items:
          $ref: '#/definitions/KeyManagerInfo'
  #-----------------------------------------------------
  # The Claim Mapping Resource
  #-----------------------------------------------------

  ClaimMappingEntry:
    title: Claim Mapping Configuration
    properties:
      remoteClaim:
        type: string
      localClaim:
        type: string
  TokenValidation:
    title: Token handling Configuration
    properties:
      id:
        type: integer
      enable:
        type: boolean
        default: true
      type:
        type: string
        enum:
          - REFERENCE
          - JWT
          - CUSTOM
      value:
        type: object

  #-----------------------------------------------------
  # The Scope Settings resource
  #-----------------------------------------------------
  ScopeSettings:
    title: Settings
    properties:
      name:
        type: string
        items:
          type: string

  #----------------------------------------------
  # The Alert list resource.
  #----------------------------------------------
  AlertTypesList:
    title: Alert Types List
    properties:
      count:
        type: integer
        description: The number of alerts
      alerts:
        type: array
        items:
          $ref: '#/definitions/AlertType'

  #----------------------------------------------
  # The AlertType resource.
  #----------------------------------------------
  AlertType:
    title: Alert Type
    properties:
      id:
        type: string
        description: The alert Id
      name:
        type: string
        description: The name of the alert.
  #-----------------------------------------------
  # The Alerts Subscription resource definition.
  #-----------------------------------------------
  AlertsSubscription:
    title: Alerts Subscription
    properties:
      alerts:
        type: array
        items:
          $ref: '#/definitions/AlertType'
      emailList:
        type: array
        items:
          type: string
          format: email
  #-----------------------------------------------------
  # The Bot Detection Alert Subscription List resource
  #-----------------------------------------------------
  BotDetectionAlertSubscriptionList:
    title: Bot Detection Alert Subscription List
    properties:
      count:
        type: integer
        description: |
          Number of Bot Detection Alert Subscriptions returned.
      list:
        type: array
        items:
          $ref: '#/definitions/BotDetectionAlertSubscription'

  #-----------------------------------------------------
  # The Bot Detection Alert Subscription resource
  #-----------------------------------------------------
  BotDetectionAlertSubscription:
    title: Bot Detection Alert Subscription
    required:
      - email
    properties:
      uuid:
        type: string
        description: UUID of the subscription
      email:
        type: string
        description: email
    #-----------------------------------------------------
  # The Workflow List resource
  #-----------------------------------------------------
  WorkflowList:
    title: WorkflowList
    properties:
      count:
        type: integer
        description: |
          Number of workflow processes returned.
      next:
        type: string
        description: |
          Link to the next subset of resources qualified.
          Empty if no more resources are to be returned.
      previous:
        type: string
        description: |
          Link to the previous subset of resources qualified.
          Empty if current subset is the first subset returned.
      list:
        type: array
        items:
          $ref: '#/definitions/WorkflowInfo'

  #-----------------------------------------------------
  # The Workflow Info resource
  #-----------------------------------------------------
  WorkflowInfo:
    title: Workflow info object with basic workflow details
    properties:
      workflowType:
        type: string
        enum:
          - APPLICATION_CREATION
          - SUBSCRIPTION_CREATION
          - USER_SIGNUP
          - APPLICATION_REGISTRATION_PRODUCTION
          - APPLICATION_REGISTRATION_SANDBOX
          - APPLICATION_DELETION
          - API_STATE
          - SUBSCRIPTION_DELETION
          - SUBSCRIPTION_UPDATE
        description: |
          Type of the Workflow Request. It shows which type of request is it.
      workflowStatus:
        type: string
        enum:
          - APPROVED
          - CREATED
        description: |
          Show the Status of the the workflow request whether it is approved or created.
      createdTime:
        type: string
        description: |
          Time of the the workflow request created.
      updatedTime:
        type: string
        description: |
          Time of the the workflow request updated.
      referenceId:
        type: string
        description: |
          Workflow external reference is used to identify the workflow requests uniquely.
      properties:
        type: object
      description:
        type: string
        description: |
          description is a message with basic details about the workflow request.

  #-----------------------------------------------------
  # The workflow executor's response resource
  #-----------------------------------------------------
  WorkflowResponse:
    title: workflow Response
    required:
      - workflowStatus
    properties:
      workflowStatus:
        description: |
          This attribute declares whether this workflow task is approved or rejected.
        type: string
        enum:
          - CREATED
          - APPROVED
          - REJECTED
          - REGISTERED
      jsonPayload:
        description: |
          Attributes that returned after the workflow execution
        type: string

  #-----------------------------------------------------
  # The Bot Detection Data List resource
  #-----------------------------------------------------
  BotDetectionDataList:
    title: Bot Detection Data List
    properties:
      count:
        type: integer
        description: |
          Number of Bot Detection Data returned.
      list:
        type: array
        items:
          $ref: '#/definitions/BotDetectionData'

  #-----------------------------------------------------
  # The Bot Detection Data resource
  #-----------------------------------------------------
  BotDetectionData:
    title: Bot Detection Data
    properties:
      recordedTime:
        type: integer
        format: int64
        description: The time of detection
      messageID:
        type: string
        description: The message ID
      apiMethod:
        type: string
        description: The api method
      headerSet:
        type: string
        description: The header set
      messageBody:
        type: string
        description: The content of the message body
      clientIp:
        type: string
        description: The IP of the client
  #-----------------------------------------------
  # The Role Alias resource definition.
  #-----------------------------------------------
  RoleAliasList:
    title: Role alias list
    properties:
      count:
        type: integer
        description: The number of role aliases
      list:
        type: array
        items:
          $ref: '#/definitions/RoleAlias'

  #-----------------------------------------------
  # The Role Alias resource definition.
  #-----------------------------------------------
  RoleAlias:
    title: Role alias
    properties:
      role:
        type: string
        description: The original role
      aliases:
        type: array
        items:
          type: string
        description: The role mapping for role alias
#-----------------------------------------------------
# END-OF-FILE
#-----------------------------------------------------
