<?xml version="1.0"?>
<wsdl:definitions
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:tns="http://schemas.cordys.com/KIOSKWsApps"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:cordys="http://schemas.cordys.com/General/1.0/"
        name="KioskUtility_WS"
        targetNamespace="http://schemas.cordys.com/KIOSKWsApps">
    <wsdl:types>
        <xsd:schema
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wcp="http://schemas.cordys.com/"
                xmlns=""
                xmlns:cordys="http://schemas.cordys.com/General/1.0/"
                attributeFormDefault="unqualified"
                elementFormDefault="qualified"
                targetNamespace="http://schemas.cordys.com/KIOSKWsApps">
            <xsd:include
                    schemaLocation="sample.xsd"
            />
            <xsd:element
                    name="InvokeClaimGeniousDataIntoCordysElement">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element ref="cordys:LocalizableMessage"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message
            name="InvokeClaimGeniousDataIntoCordysMessage">

    </wsdl:message>
    <wsdl:portType
            name="KioskUtility_I">
        <wsdl:operation
                name="InvokeClaimGeniousDataIntoCordysPortOperation">
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding
            name="KioskUtility_I"
            type="tns:KioskUtility_I">
        <soap:binding
                style="document"
                transport="http://schemas.xmlsoap.org/soap/http"
        />
        <wsdl:operation
                name="InvokeClaimGeniousDataIntoCordysBindingOperation">
            <soap:operation
                    soapAction=""
                    style="document"
            />
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service
            name="KioskUtility_IService">
    </wsdl:service>
</wsdl:definitions>
